### ISSUE TITLE
add the ability to change the prefix "icon-" to "some-ico" or other different

### ISSUE THREAD

**Issue by royriojas** [fontello/fontello#133]
It would be very useful to be able to change the icon- prefix to any other prefix. to play nicely with other icon- stylesheets. It could be another config value in the exported json

**Comment by aniljadhavmca** [comment]
You can change prefix and icon library name as well. Please check below screenshot.

http://screenshots.sharkz.in/anil/2017/01/2017-01-04_16-46-53.png
