### ISSUE TITLE
Fontello as a CDN (+ accounts)

### ISSUE THREAD

**Issue by nicooprat** [fontello/fontello#143]
As a front-end developer, I'm now using fontello for months as a daily tool. It saves me a lot of time and make my work more enjoyable.

When developing a website, we're constantly adding or removing some icons from our "custom-pack". So the more time consuming part is to download the pack again, unzip it, replace all the right files at the right place, remember to keep the last config.json and copy-paste the new stylesheet classes.

I thought it could be really interesting to have the possibility to simply link to a single remote stylesheet (like Google Webfonts does) that is always up to date when we save it on Fontello.

I know there already are some online services for this like Icomoon, but these are paid ones (and I prefer Fontello :)). I also know I can't ask for a free one that does the same. Actually I was thinking at something we could use for development only, not for production : maybe something with a very low access per month and not-so-good performances ?

The second idea that comes with it is the possibility to create an account on Fontello where we could manage icon packs associated with projects. This way we won't need to re-import a well-hidden-in-a-deep-folder config.json every time we have to work on an old project : simply login, go to the project, edit the font pack, download.

I think it could be a little, but precious value added.

Of course these are ideas that need more reflexions, but what do you think ?

**Comment by prakash230891** [comment]
use fontwesome. :)
