### ISSUE TITLE
Aliases for search terms

### ISSUE THREAD

**Issue by waldyrious** [fontello/fontello#145]
I have tried to find icons for the commonly-called "speech balloons" or "speech bubbles", but those searches returned no results. Only when I used the exact term "comment" I managed to find the icons I wanted. It should be possible to suggest aliases for search terms (or contribute them directly as PRs in github).

**Comment by dotnetwise** [comment]
+1 This is mandatory... who searches for icons visually?

Please add the names!

**Comment by puzrin** [comment]
Close in favour of #483 - all ideas moved there.
