### ISSUE TITLE
Firefox shows illegal character instead of Icon 

### ISSUE THREAD

**Issue by OrangeWacko** [fontello/fontello#156]
Okay, here is the website that has issues in Firefox: http://wp.skinny-guy-big-guy.com/

As you can see, the Download Button supposed to have download icon and also for the articles in the footer it supposed to show comment icon and also twitter icon above and email icon ALL not showing in Firefox, looks fine in Safari and Chrome... Please help, is there something I did not do correctly? I swear it worked when it got launched... Is there something in the permissions that I need to do for the font extension on the server or what would cause this?... Thanks!

**Comment by moeiscool** [comment]
I have fixed this issue by linking my css file directly. I was running my font through a minifier and that is what messed me up. In case others are using minifiers, just use the <link> tag for fontello.
