### ISSUE TITLE
Disable icons packs (better performances ?)

### ISSUE THREAD

**Issue by nicooprat** [fontello/fontello#234]
Sometimes Fontello is a bit laggy on my machine, especially when scrolling (Mac OS Chrome).

I wonder if performances would be better if we could deactivate some icons packs ? 90% of the time I'm using only one or two packs, often the same. This info could simply be in the local storage. This will certainly be more and more important as new icons packs are added.

I should precise that just "hiding" them doesn't seem to change anything.

**Comment by puzrin** [comment]
Close in favour of #484. New design has "Collections" tab.
