### ISSUE TITLE
Chrome v32 + Win8. Icons with 3-bytes code sometime not displayed

### ISSUE THREAD

**Issue by ericbollman** [fontello/fontello#255]
---

added by @puzrin:

**This looks like Crome v32 bug - codes from the latests (6.0+) unicode specs now not displayed under Win8. If you are affected, please go to https://code.google.com/p/chromium/issues/detail?id=338644 and star this issue.**

**If anyone has direct contacts with Chrome devs - ask them to increase priority of that bug**.

As temporary solution - use PUA codes range (Settings -> Advanced). After settings change, you should reselect glyphs or change codes manually. Note, that fontello use PUA range by default, and majority of users should not suffer from this problem.

---

Several of my fontello icons are not appearing for PC users. Only able to reproduce this issue in Chrome 32 on PC. What's strange is that some icons appear and some do not. The files are set to PUA and I see nothing in the CSS or Json file that would cause this issue. Important to note that the icons render fine on a Mac on Chrome 32. Also renders fine on Firefox and Safari

**Comment by ozgurkuru** [comment]
We have same issue on mac with chrome version  43.0.2357.124 m
