### ISSUE TITLE
print issues in IE/HP

### ISSUE THREAD

**Issue by drewkimrey** [fontello/fontello#264]
Several of my users have let me know that they are unable to print. I narrowed it down to  an 49.4c02 on my printer here in the office. I'm able to print the same page on osx, and on chrome in windows, however when I and several of my users print, they are receiving printer errors. I narrowed it down to HP printers from windows/ie. 

I have a work around in which I can submit a pull request, but its a bit of a hack. And I'm hoping its a temporary fix. I do a media query for print, in IE and change the font family and display properties for [class^="icon-"].

I did do some tests where i was able to print font-awesome under the same circumstances outside of fontello, which leads me to believe that there is a somewhat easy fix.

Here is my config file
https://gist.github.com/drewkimrey/870fc2a1f4a9cc19fdbb

**Comment by puzrin** [comment]
Is this still a problem?

**Comment by puzrin** [comment]
Let's close as outdated.
