### ISSUE TITLE
Support to export font as symbol SVG

### ISSUE THREAD

**Issue by phaseOne** [fontello/fontello#326]
For the uninitiated: http://css-tricks.com/svg-symbol-good-choice-icons/

This would allow users to inline embed an SVG file into their HTML, and then call it with `use`:

``` XML
<svg class="icon">
  <use xlink:href="#icon-facebook" />
</svg>
```

**Comment by msaspence** [comment]
Surely the same issue applies to breaking up fonts and bundling them into a new font?

**Comment by puzrin** [comment]
When you zip multiple files to archive, that does not requires a separate licence for archive :). But fonts have SIL license and i'm not sure it cover use out of font format (as separate icons).

It's better to discuss this topic with someone more experienced about licences, not with me. Or ask font authors directly to add licence for icons.

**Comment by puzrin** [comment]
In theory, it's possoble to allow icons export and warn users that they can break licence for some collections. Everyone will ignore it, but that will be not fontello's problem :)

But i'd prefer more straight solution, if possible. If anyone interested - contact font authors about add CC-xx licence for icons (if not exists) and let me know on success.
