### ISSUE TITLE
Exported an SVG from AI CC; showing up blank in Fontello

### ISSUE THREAD

**Issue by geebru** [fontello/fontello#358]
I know this has been reported, but not lately.

Attempting to add an icon to my font:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="2760 0 100 100" enable-background="new 2760 0 100 100" xml:space="preserve">
<path d="M2852.193,42.966h-84.387c-3.888,0-7.036,3.148-7.036,7.036c0,3.884,3.148,7.027,7.036,7.027h84.387
	c3.888,0,7.036-3.144,7.036-7.027C2859.229,46.114,2856.081,42.966,2852.193,42.966z"/>
<path d="M2767.807,28.899h84.387c3.888,0,7.036-3.144,7.036-7.027c0-3.888-3.148-7.036-7.036-7.036h-84.387
	c-3.888,0-7.036,3.148-7.036,7.036C2760.771,25.755,2763.919,28.899,2767.807,28.899z"/>
<path d="M2852.193,71.101h-84.387c-3.888,0-7.036,3.144-7.036,7.027c0,3.888,3.148,7.036,7.036,7.036h84.387
	c3.888,0,7.036-3.148,7.036-7.036C2859.229,74.245,2856.081,71.101,2852.193,71.101z"/>
</svg>
```

Comes up as a blank icon. If I try to upload any previous icons from the same set they also show up as blanks. Any ideas?

**Comment by msandrew** [comment]
Having the same problem since upgrading from from CS6 to CC. I have used the exact setting in both applications. 

Did you manage to find a fix?

**Comment by russomike** [comment]
major necro here but @geebru @msandrew did you ever find a workaround?
the "blank" icon aka horribly offset glyph is killing me, thanks

**Comment by geebru** [comment]
@msandrew / @russomike - I never did. I moved shortly after this issue to using IcoMoon or non-font SVG's. I also switched to Sketch for icon / sprite creation (I'm a developer so I don't do a lot of hard design) and their SVG exporting is stellar.

My only guess, based on an increased knowledge of SVG's now is to check Illustrator CC's output in regards to the viewBox (which in my example is "2760 0 100 100") as it's significantly larger than the actual icon. Problem being this would mean editing every exported CC SVG to make sure it works in Fontello (or anywhere for that matter).

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-use-custom-images

SVG should be converted to compount path, because filling in font is defined by contour direction. I don't know how to do it in AI, but there are examples in help for another programs.
