### ISSUE TITLE
Persistent custom icon set (like the core ones)

### ISSUE THREAD

**Issue by skullcrasher** [fontello/fontello#368]
Can anybody tell me, if there is a description on how to store a custom icon font pack persistent (on a selfhosted environment)?
Just as the core fonts like fontawesome, fontelico etc, so that the font is always present and can be downloaded/chosen from.

So basically, which steps do I need to do the same as the fontello team does, after receiving a font recommendation to add the font to the fontello installation.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/blob/master/Makefile#L35 start from this point

1. Clone one of existing font repo and modify it for your needs. See `Makefile` in it.
2. Add front to `support/src` folder
3. Update [font list](https://github.com/fontello/fontello/blob/master/Makefile#L9-L22)
3. run `make rebuild`

In short - there are no easy way to change persistent fonts without programming skills.
