### ISSUE TITLE
Design input

### ISSUE THREAD

**Issue by jegtnes** [fontello/fontello#370]
Hey, folks! Thanks a bunch for Fontello, we use it for every project at work and it's a fantastic resource. Since you said you were after some design input, I have a suggestion. Even after extensive use, I still mistake the font name field for the search box as they look nearly identical if there's no input in them. I suggest this could be improved by adding labels to the input fields and use the placeholder attribute for an example of the content that goes in it instead, e.g. `warning, save` for the search field, and `my-awesome-font` for the font name field. In addition to being more obvious, [this is also better for accessibility](http://www.nngroup.com/articles/form-design-placeholders/).

If you're happy with this change, I'll shoot over a pull request. Let me know!

**Comment by puzrin** [comment]
I think, will be improved in new design. Close, since nobody else voted.
