### ISSUE TITLE
"Cheatsheet" - copy characters to clipboard

### ISSUE THREAD

**Issue by iamzozo** [fontello/fontello#379]
I didn't found any option to copy characters to use them in my design software.
Could be a great feature for these fonts, as here: http://fontawesome.io/cheatsheet/

**Comment by puzrin** [comment]
Do it from demo, available in each generated font.

**Comment by raduamarie** [comment]
@iamzozo you can use this dirty fix: https://github.com/fontello/fontello/issues/381#issuecomment-71369722

After you download the demo, add that right before the </body> and you will be able to copy the character afterwords :)
