### ISSUE TITLE
Upgrade Existing Font to it's latest version?

### ISSUE THREAD

**Issue by tschofen** [fontello/fontello#380]
What would need to happen to upgrade an existing Font to a new version?
I'm looking at FontAwesome 4.3.

Follow the same steps as outlined in https://github.com/fontello/fontello/wiki/How-to-suggest-font-to-fontello#how-to-prepare-a-font-for-use-with-fontello?

**Comment by puzrin** [comment]
Someone can make PR to this repo http://forum.rcdesign.ru/rules/ or wait until i do it. Or anyone can import FA svg font as custom

**Comment by puzrin** [comment]
closed in flavour of #384
