### ISSUE TITLE
Custom Function Request [Custom Select Icons]

### ISSUE THREAD

**Issue by raduamarie** [fontello/fontello#383]
Hi everyone,

@puzrin, thanks for the ticket that allows easy copy for Photoshop users of the demo page :)

I have another request that will ease the life of Photoshop users and Coders as well.

For example: I have a prototype in photoshop that uses around 40 icons (of the whole 2100+ fonts that fontello has), I would love if I could get all the unique icons that were used there, I have made a photoshop script that gets all the layers and gets all the icons used in a psd file. 

Example:
![screen shot 2015-01-25 at 19 52 20](https://cloud.githubusercontent.com/assets/2953026/5892551/d18f2f5a-a4cb-11e4-854b-0a06cdd55c5d.png)

It outputs: `Icon contents: ,`

It would be awesome if I had an input where I could paste those icons and fontello would auto-select the icons that I have used.

I have written a small script to do just that (I pasted that into the console whith the Select Icons page active and it works)

```javascript
var iconsInput = ','; //Here can be the icons that the user pastes
var icons = iconsInput.split(',');

$('.selector__glyph').each( function(){
	if( icons.indexOf( $(this).find('span').text() ) != -1 ){
		$(this).find('div').click();
	}
});
```

Also, the JSX script for Photoshop is this one: 
```jsx
#target photoshop
#script "Get Fontello used Icons"
#strict on


app.bringToFront(); // just in case

var icons = [];

function unique ( str )
    {
        var n = {},r=[];
        for(var i = 0; i < str.length; i++)
        {
            if (!n[str[i]])
            {
                n[str[i]] = true;
                r.push(str[i]);
            }
        }
        return r;
    }

function getIcons(layerNode) {
    
    for (var i=0; i<layerNode.length; i++) {
            var layer=layerNode[i];
            if (layer.kind == LayerKind.TEXT && layer.textItem.font == 'fontello') {
    
                var str = layer.textItem.contents;

                for(var q=0; q < str.length; q++){
                    icons.push(str[q]);
                }

            }
    }

    alert('Icon contents: ' + unique(icons) );
}

getIcons(app.activeDocument.artLayers);
```

I can also write an article for the homepage to ease the work of Photoshop Designers with Fontello :) I think this will attract a lot of people.

Best regards,
Radu

**Comment by puzrin** [comment]
How do you suggest to match images from photoshop with fontello icons?

Each icon is edentified by long id like "c64623255a4a7c72436b199b05296c4f", because names and codes can be duplicated between collections. As far as i understand, you don't have id-s in photoshop.

> I can also write an article for the homepage to ease the work of Photoshop Designers with Fontello :) I think this will attract a lot of people.

Any kind of tutorial will be awesome. I'm not designer at all

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport

If you know how to extract IDs, then API is the most simple way to open browser with required selection from script.

**Comment by raduamarie** [comment]
It doesn't have IDs,

If you go to the frontpage, you have all the icons in things like

`<span data-bind="text: charRef" class="selector__glyph-image"></span>`

There's a character there, that character goes when you generate the .ttf and it's also the same character that's in the `:before` content of icons.

When you use it in photoshop, you use that exact character which when selecting the fontello Font it transform into the icon, the scrips grabs all the characters used, and searches for them in all the span from the frontpage. When it finds the character that was used, it auto-clicks on it :)

That's how it works for the moment and it works for the current 2100+ icons that you guys have :)

I don't see conflicts :)

**Comment by puzrin** [comment]
@raduamarie `charRef` is local identifier, it's autogenerated on [fonts aggregation](https://github.com/fontello/fontello/blob/master/Makefile#L35) and not guaranteed to be unique when collections change.

**Comment by raduamarie** [comment]
Wouldn't it be better to set some reserved identifiers for the default
icons available with Fontello?

**Comment by puzrin** [comment]
Different collections have similar icons. They can have the same css names and the same codes. Collisions are resolved dynamically on selection.

Unique identifiers are `id`, those are saved to config, but are not human-friendly.

Solution can be to use collection-slecific prefixed, but that requires too big rewrite.

**Comment by raduamarie** [comment]
Actually if I think about it, it doesn't need to be unique identifiers, they need to be the same charRef for that user between the website, the demo.html and the fontello.ttf :)

That would be enough :)

**Comment by raduamarie** [comment]
Yeah, actually we have a huge problem, if adding another icon to the list (Fontello) + 1 custom icon, all the charcodes are recreated and don't match the old ones.

I think the best solution will be that the default Fontello Icons (3162 icons) have their own non-changing `charRef`, or the custom icons to go after the Fontello Icons so that adding an icon before will not ruin all the `charRef` ids

**Comment by puzrin** [comment]
Those already have unique identifier, `id`.

**Comment by raduamarie** [comment]
It's the same problem for which I opened  #381, the problem wasn't that I could not copy from the demo.html, the problem was that the icon `charRef` would not equal the `:before` content.

First let's get to the first problem.

Fontello has 3162 icons, that when selected you say they have their unique identifier (I was talking about the fact that they should have their unique `charRef` as well).

![screen shot 2015-01-26 at 13 24 18](https://cloud.githubusercontent.com/assets/2953026/5899184/7caf58e4-a560-11e4-81b8-c924020eda4c.png)

3162 selected icons, the first smiley face has a code of `U+E800`, when I upload my custom icon, and I come back to it: 

![screen shot 2015-01-26 at 13 31 12](https://cloud.githubusercontent.com/assets/2953026/5899194/a019a028-a560-11e4-91ad-48e896fabdf0.png)

3163 icons, my icon is the first place, and it shifted the codes for all the icons, now the smiley face is `U+E801` this should not happen, they should all keep their codes.

The next problem which I wanted to identify in #381 was about the fact that the icon `:before` does not equal to their `charRef`, and visual example of this, is that when I try to copy the smiley icon: 

![screen shot 2015-01-26 at 13 33 26](https://cloud.githubusercontent.com/assets/2953026/5899224/f2411d72-a560-11e4-952a-7d26223ab335.png)

and try to search for it, I find the smiley icon (obviously), and the second resoult is the `customChar` of a totally different icon:

![screen shot 2015-01-26 at 13 33 18](https://cloud.githubusercontent.com/assets/2953026/5899265/8a0bc2a6-a561-11e4-83a4-8233453e5fa1.jpg)

If you do this: #382 the problem will be, I will copy an icon from the demo.html page and when I paste in Photoshop I paste a totally different icon.

Thanks!
Radu

**Comment by puzrin** [comment]
@raduamarie , `charRef` is internal provate thing and NOT intended to be used outside. You try to hack the middle without respect to existing architecture, instead of formalizing the real problem and use cases.

The real problem is something like "how to copypaste to photoshop". Focus on it, try to suggest variants of acceptable user behaviours (steps to do). Then it will be possible to select technically possible.

**Comment by raduamarie** [comment]
Ok, I'll focus just on the user.

As a photoshop user I would like to go to Fontello, get all the icons and install them on my local machine, after that look in the `demo.html` page and copy-paste icons into my design, after I have finished the design, to be able to select only the icons I used in my design and create a custom font for use on the website.

I would also want to be able to add a custom icon and reinstall the font without loosing the relation between the used icons in Photoshop and what the new icons are.

I think that's about it :)

Thanks! :grinning:

**Comment by paul2moro** [comment]
I totally agree. I have the pleasure to work with raduamarie and here's what we need (basically what he said but maybe in other words).
we're working on a project from scratch so here's what would be our workflow/necessities:
1) Selected all icons from fontello
2) Installed the font
3) Opened demo
3.1) Thanks to Radu, the icons are selectable and I can directly paste them into Photoshop, in a text layer with Fontello as selected word.
4) Continue development, realise we need a new SVG icon.

Here's what would need to happen next:
1) Create a new SVG icon in Illustrator
2) Save SVG file (according to https://github.com/fontello/fontello/wiki/How-to-use-custom-images)
3) Go to fontello, import my existing Fontello font
4) Add my NEW SVG icon
5) Export/download NEW font (that has all Fontello + new icon)
6) Install the new font (overwrite current Fontello font)
7) Go to the newly generated demo page, where all the codes are the same as before downloading the new font, but I also get to see the NEW icon, which has a custom codes (no other code altered).

This would be an amazing way to work with Fontello, and would definitely make it one of the best services out there. :)

**Comment by puzrin** [comment]
@raduamarie How do you determine, what icons you have used? If you know icon codes (for example), then it's possible to write script for this thing:

- take demo config, and determine `id` by codes
- build new config, makring required IDs as selected
- open fontello with your selection via API.

Will it work for you? Key point, that i don't understand, is how do you know from your PSD file which icons you used? Sorry, if question is stupind, but i never worked with photoshop

**Comment by raduamarie** [comment]
Hi @puzrin, thanks for the answer, I wrote a jsx script for Photoshop that extracts all the used icons but I can only get the `charRef`.

If we are using just the default Fontello icons the current workflow works: Select all icons, copy-paste them from demo to photoshop prototype, run script to get all the used icons, paste custom javascript in console that searches and auto-selects from the fontello frontpage based on `charRef`, but when we added a new custom icon, this workflow did not longer work because `charRef` had changed because of the new icon addition :(

**Comment by puzrin** [comment]
@raduamarie i guess, from photoshop you extract not `charRef` but real code from generated demo. Then that should be enougth to determine ID with demo config, as i described.

You need to convert data this way: `demo codes` + `demo config` -> `IDs` -> API -> fontello site. Your problem was because you tryed to use private `charRef`, that is not intender for this thing.

Do you understand my explanation or should i add more details? Will it solve your problem (after i fix demo)?

**Comment by puzrin** [comment]
- this is id https://github.com/fontello/fontello/blob/master/assets/icons/src/config.json#L16 , it's globally unique
- this is code https://github.com/fontello/fontello/blob/master/assets/icons/src/config.json#L18 , it's unique per demo, and not changed until you unselect glyph.

**Comment by raduamarie** [comment]
@puzrin Your explanation will: Make my life harder because of all the things I need to do in plus, but yeah, probably using the real codes generated in the demo to search for the unique id to make a request to the API to select the icons, it will definitely work (overkill that is, but it will work).

But that is 30% of the problem.

The huge problem is that if I add custom icons to the font and re-download the font, the codes will be regenerated and when I install the fonts, Photoshop will change all the icons I used before, making them  irrelevant and pointless. :( It will literally show different icons and not the expected ones.

**Comment by puzrin** [comment]
> The huge problem is that if I add custom icons to the font and re-download the font, the codes will be regenerated and

That looks like a bug, if you don't make something wrong. Imported config should keep icon codes for all selected icons. Report it to separate ticket

**Comment by raduamarie** [comment]
Ok, now I understand, I need to import the config file, upload my desired icons and then deselect the ones I do not need. Exactly in this order.

If I deselect all and then select the ones I need the codes would change. Darn. Thanks!

I will write that Fontello for Photoshop article will all the tips and tricks :)
