### ISSUE TITLE
Not loading Font / Icon

### ISSUE THREAD

**Issue by developer-prosenjit** [fontello/fontello#386]
Error generate in console.
Uncaught ReferenceError: Unable to process binding "text: function (){return charRef }"
Message: charRef is not defined

**Comment by puzrin** [comment]
Not enougth info to reproduce. Please, describe step-by-step what to do.

**Comment by developer-prosenjit** [comment]
When I visit the fontello.com, No icon displayed and Error generated in
console.

Thanks
Prosenjit Manna

**Comment by puzrin** [comment]
That's not fontello bug. Something at your side breaks javascript. Try from another computer/provider.

**Comment by developer-prosenjit** [comment]
I check with 5 PC but same problem with Firefox and Chrome Browser.

**Comment by puzrin** [comment]
May be you have corporate firewall or ads blocker. I can't reproduce your bug. Also, here would be a tons of reports, of FF / Chrome were broken.

**Comment by developer-prosenjit** [comment]
Fine with my mobile device.

**Comment by developer-prosenjit** [comment]
Also From desktop, Today.
