### ISSUE TITLE
Add woff2 format to file downloads

### ISSUE THREAD

**Issue by kblagojevic** [fontello/fontello#388]
This would be a great feature enhancement!

**Comment by dandv** [comment]
:+1: ! Woff2 is even smaller than woff!

**Comment by puzrin** [comment]
I can leave this ticket open for volunteers, but have no plan to do it myself.

This feature requires to implement ttf2woff2 convertor, which needs [brotli](https://github.com/google/brotli) implementation in JS. I know about autotranslated project [brotly.js](https://github.com/devongovett/brotli.js) but it has very big size.

So, if anyone wish to help - do brotly port. Use [pako](https://github.com/nodeca/pako) project structure and wrappers, that api was well tested with JS.

**Comment by collinbarrett** [comment]
It would be great if there was a way, even manually after the fact, to get a fontello woff2 file. I just tried using the fontello ttf to get a woff2 via the font squirrel generator, but my social media icons came out as some Asian character set. I'd love to help implement this, but I unfortunately have very little knowledge of how to work with fonts.
