### ISSUE TITLE
Control on CSS generation

### ISSUE THREAD

**Issue by AlgoTrader** [fontello/fontello#392]
Fontello generates somewhat 'opinionated' CSS that cause issues in complex markups. All stuff is in single class 'icon-somewhat'.

Font Awesome, for example,  provides fa class that style element itself, and fa-stuff that styles element::before.

Is there any way to customize CSS generation?

**Comment by AlgoTrader** [comment]
After some sex with generated css I switched to fontello-codes.css and made a static css for other stuff. What I need is:

![image](https://cloud.githubusercontent.com/assets/1556262/6388402/96f7fdac-bdaa-11e4-8cf2-16bfdb6f3a4d.png)

I made a class 'icon', put all the styling there and use <span class="icon icon-plane"/>. All the positioning problems gone, I style span itself, not it's first child ::before

Original CSS is difficult to use. FA's CSS is in contrary very convenient and has lots of bonuses like scalings and rotations

**Comment by puzrin** [comment]
I understand, that styles are a bit outdated, but we should keep compatibility with lot of previously downloaded projects.

If you need something very specific, you can take `config.json` and generate CSS with custom script as you wish.

**Comment by AlgoTrader** [comment]
If compatibility is a major issue then it stop innovations. I think, it's possible to generate fontello.css and fontelllo-compat.css for those who need compatibility.

I do not need something very specific. I need a very basic thing. I want to have several things

1) ability to place icons into 'div' for precise positioning
2) ability to scale icons like in FA
3) ability to rotate icons like in FA
4) no weird sex with 0.2em margins 

Font Awesome has exellent CSS that allows me to do simple things out of box and complex things are still possible. In Fontello, simple things are tough, complex things are very tough.

I spent an hour to get two icons overlapped and properly positioned. That's because of ugly selector
```
[class^="icon-"]:before, [class*=" icon-"]:before
```
It causes majority of problems with Fontello CSS. I have almost always to style the element itself, not ::before child.

**Comment by puzrin** [comment]
`fontello-codes.css` already can solve your request. It's specially done for situations, when default font definition is not suitable.

**Comment by AlgoTrader** [comment]
I resolved all my problems with custom CSS that imports 'fontello-codes.css'. You are right.

But FA solves all my problems out of box, while Fontello want me to write scalers, rotators, proper parent styling classes. 

Making a user solving problems is an easy way to go.

**Comment by puzrin** [comment]
I don't see problem with it, seriously. If FA would be as good as you describe, you would not use fontello :) . It's impossible to solve all possible problems and keep interface simple. Fontello tries to provide extendable result, and i hope it does it well. I understand your reasons, but those are not enougth to generate one more css file or break compatibility.

**Comment by AlgoTrader** [comment]
I understand that user experience is not much important for you. I also understand FA mentioning is not pleasant.

There are tasks, that are hell of difficult to do with Fontello. The most wanted thing is stacking - overlapping icons to combine several icons into a new one:

```
<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-twitter fa-stack-1x"></i>
</span>
```

I have to use Fontello, I just about do all the work manually. Placing a Fontello icon to div is pain, positioning it is double pain

**Comment by puzrin** [comment]
That become not constructive. Sorry.
