### ISSUE TITLE
How to Remove the query string from fontello.css and make sure any future updates don't re-add it?

### ISSUE THREAD

**Issue by sbha5516** [fontello/fontello#394]
Fontello by default generates all the font url()}}s with a query string including a timestamp for decaching, e.g. {{fontello.woff?254634634.  I need to Remove the query string from fontello.css and make sure any future updates don't re-add it. How to do so?

**Comment by puzrin** [comment]
Use pure `fontello-codes.css` and do any header you wish in external file.
