### ISSUE TITLE
Improve tags/search

### ISSUE THREAD

**Issue by slavafomin** [fontello/fontello#397]
Hello!

Great project you have here!

However, the search is far from ideal right now. When you enter «letter» in the search field it shows nothing. However, when you enter «mail», there are a lot of letter icons.

Maybe you should add tag synonyms and provide users with ability to suggest additional tags?

Thank you!

**Comment by puzrin** [comment]
All fontello fonts are published here https://github.com/fontello in separate repos. Aliases can be updated by editing `config.yml` file in each repo root. If you know missed aliases - do PR.
