### ISSUE TITLE
Option to use SCSS files when exporting

### ISSUE THREAD

**Issue by tehtrav** [fontello/fontello#401]
I use fontello in an SCSS environment — I convert the fontello files to SCSS so I do things like 

    .modal-close {
        @extend .fontello;
        @extend .icon-cancel;
    }

This is massively helpful in keeping my markup clean of presentational classes. Unfortunately it's tedious to maintain as I have to do two things every time I update my font: 

1. Change the file format of fontello files
2. Modify the main css declaration to also include a "dumb" selector so I can apply the styles with an @extend rule

```
[class^="icon-"]:before, 
[class*=" icon-"]:before,
.fontello {
    font-family: "fontello";
    font-style: normal;
    font-weight: normal;
    ...
```

I would love it if something like this could be supported through a preference in the font settings.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport there are different kinds of scripts to automate workflow. You can create one more to generate SCSS directly from JSON file.

**Comment by tehtrav** [comment]
Thanks. Unfortunately I have no idea how I'd accomplish what I'm trying to do using any of those options.

**Comment by puzrin** [comment]
Every downloaded archive contains `config.json` file. It can be used to generate stylesheet in any format. You can write a script for your needs and avoid manual work.

**Comment by HandHugs** [comment]
it would be nice if when you download the css file it didn't contain all those non UTF characters in it. they mess up the scss parser.
