### ISSUE TITLE
square and square-o icons missing

### ISSUE THREAD

**Issue by AgDude** [fontello/fontello#402]
These two icons have been in Font Awesome since v2.0, but they are not available in Fontello.

http://fortawesome.github.io/Font-Awesome/icon/square/

http://fortawesome.github.io/Font-Awesome/icon/square-o/

**Comment by AgDude** [comment]
Looks like perhaps they are there, under the names: ```blank``` and ```check-empty```.

Did these names change in a font awesome version? Was this a design decision by Fontello to change the names?  I just spend a half hour trying to add these two simple icons to my set. Consider this a request to improve the search function to include all of the names from the underlying font libraries.

**Comment by puzrin** [comment]
Idea was to have something similar across all fonts, because it's not FA only.

I think, solution could be to add different FA names as search aliases. Anyone can do it here https://github.com/fontello/awesome-uni.font/blob/master/config.yml
