### ISSUE TITLE
if empty

### ISSUE THREAD

**Issue by janwagner** [fontello/fontello#403]
Hi :)

I was wondering if it is maybe possible to add something like this, to remove the default margin from icons without text.

:empty:before { margin:0 }

**Comment by puzrin** [comment]
That's impossible directly. But you can add secondary class to override margin

**Comment by janwagner** [comment]
hi puzrin,
I always use it like this:

[class^="icon-"]:not(:empty):before, [class*=" icon-"]:not(:empty):before {
    margin-right: .2em;
    /* Animation center compensation - margins should be symmetric */
    /* remove if not needed */
    margin-left: .2em;
}

**Comment by puzrin** [comment]
Didn't new that.

You are right about blowing CSS, but solution already exists - use css with codes only, and rewrite font declaration as you wish in another file of you project. In this case you will not need to patch anything when you update font with new version
