### ISSUE TITLE
Add OpenStreetMap icons (Osmic) in the default sets

### ISSUE THREAD

**Issue by rastapopougros** [fontello/fontello#406]
There is now a set of icons for OSM : 
http://www.openstreetmap.org/user/nebulon42/diary/34709

And the author made an icon font for that, here on github : 
https://github.com/nebulon42/osmic/tree/master/font

So it would be great if Fontello integrates it directly. :)

**Comment by nebulon42** [comment]
I'm currently trying to figure out how to do this automatically by looking at the docs.

**Comment by puzrin** [comment]
I'd say it's better to add link to those into wiki https://github.com/fontello/fontello/wiki

**Comment by nebulon42** [comment]
@puzrin I have prepared a config file for integration: https://github.com/nebulon42/osmic-fontello/blob/master/config.json
Maybe you could re-open this issue?
