### ISSUE TITLE
Font awesome icons have different codes

### ISSUE THREAD

**Issue by djixas** [fontello/fontello#407]
Hi,

There seems to be a  pretty annoying issue, which does not allow current sites that have implemented font awesome, do change to the fontello version.

For example, font awesome has the following code:

.fa-twitter:before{content:"\f099"}.

While fontello exports to something like this:

.icon-twitter:before { content: '\e816'; } 

While I could do search & replace for icon to fa, the e816 is completely different from f099 and there is no way to export without using E+(ID).

Proposal:

Allow to export with code, which match that of font awesome or allow to change E+ letter to F+ and syncronize id's with font awesome id numbers.

**Comment by francoismassart** [comment]
What you can do, is use LESS or SCSS preprocessors and save the unicode value inside variables then, you won't have problem with search/replace unicodes each time you add/remove icons

**Comment by francoismassart** [comment]
I did this using `gulp`...

My gulp task is parsing the downloaded `config.json` file and it builds a scss file containing all variables.

Here is my gulp task:

```javascript
var convertDecimalToCSSHex = function(decimalValue) {
    decimalValue = String(decimalValue).replace(/\D/g, '');
    var hexValue = Number(decimalValue).toString(16);
    while(hexValue.length<4){
        hexValue = '0' + hexValue;
    }
    if (isNaN(decimalValue)) {
        return '';
    }
    return '\\' + hexValue;
};

gulp.task('fontello', function () {
  var pkg = require('./path/to/fontello/config.json')
  var fs = require('fs');
  
  var warningHeader = '// WARNING This file is generated by gulp !\n';
  warningHeader    += '// Your changes will get overwritten, DO NOT edit this file!\n\n';
  
  var variablesContent = warningHeader;
  
  variablesContent += '$fa-version: "' + new Date().getTime() + '"; // Used for busting the cache when we add/remove icons \n\n';

  var iconsContent = warningHeader;
  
  var tot = pkg.glyphs.length;
  var pre = pkg.css_prefix_text;
  var icon = null;
  for (var i = 0; i < tot; i++) {
      icon = pkg.glyphs[i];
      if (''!=icon.css && true===icon.selected) {
          // e.g. $ico-var-search: '\e803';
          variablesContent += '$' + pre + 'var-' + icon.css + ': \'' + convertDecimalToCSSHex(icon.code) + '\';\n';
          // e.g. .ico-search:before { content: $ico-var-search; }
          iconsContent += '.' + pre + icon.css + ':before { content: $' + pre + 'var-' + icon.css + '; }\n';
      }
  }
  fs.writeFile('./path/to/scss/folder/fontello/_gulp-variables-fontello.scss', variablesContent);
  fs.writeFile('./path/to/scss/folder/fontello/_gulp-icons-fontello.scss', iconsContent);
});
```

Which generates files like:

`_gulp-variables-fontello.scss`
```scss
// WARNING This file is generated by gulp !
// Your changes will get overwritten, DO NOT edit this file!

$fa-version: "1433861377149"; // Used for busting the cache when we add/remove icons 

$ico-var-music: '\e83b';
...
$ico-var-envelope-o: '\e81d';
```

`_gulp-icons-fontello.scss`
```scss
// WARNING This file is generated by gulp !
// Your changes will get overwritten, DO NOT edit this file!

.ico-music:before { content: $ico-var-music; }
...
.ico-envelope-o:before { content: $ico-var-envelope-o; }
```

**Comment by puzrin** [comment]
I don't like idea to customize fontello specially for FA. Current codes were set to be compatible with unicode set (if you wish to show similar symbols until font loaded).

Probably someone will wish to write webapp, that will "normalize" generated font to FA-style. That requires only clien-side coding. Everything else can be done via fontello api.
