### ISSUE TITLE
Way to easily grab config nodes for icons

### ISSUE THREAD

**Issue by alisman** [fontello/fontello#410]
First of all, Fontello is awesome!  Thanks for building this.   We're using the node cli.  

One thing I would like is to be able to easily graph json config for new icons as I need to add them to config in our project and then run cli.   In other words, rather than loading config into browser, making changes, then having to download the zip, extract, copy configuration into my project, I would like to be able to just copy config nodes for icons to clipboard so I can paste it into my existing config and then run install.  This seems to me like optimal workflow.   Can that already be done?

**Comment by puzrin** [comment]
Such automation can be done in a bit different way via API https://github.com/fontello/fontello#developers-api, wiki has more axamples for different languages.
