### ISSUE TITLE
Assets init error. Refresh page & try again. If problem still exists - contact administrator.

### ISSUE THREAD

**Issue by miladd3** [fontello/fontello#413]
i reset my firefox browser and now when i go to website a JS alert shows up and say:
"Assets init error. Refresh page & try again. If problem still exists - contact administrator."

and the website wont load.

**Comment by puzrin** [comment]
Is it still issue? If yes - in which browser/os, and what happens in another browser?

**Comment by miladd3** [comment]
yes it still exist in firefox windows 7. in other browsers its ok

**Comment by puzrin** [comment]
is FF latest there?

**Comment by miladd3** [comment]
yes its version 38

**Comment by puzrin** [comment]
Could you try again? I have no idea how to reproduce, but fontello got a bit update and probably your issue could disappear.

**Comment by puzrin** [comment]
Close as outdated. Let me know if should be reopened.

**Comment by DevinXian** [comment]
Oops! `fontello.com` can not init asset, here it comes

    /assets/bundle-lib.en-US-11cbd00….js:63 TypeError: Cannot read property 'apiPath' of undefined(…)
    exports.(anonymous function) @ /assets/bundle-lib.en-US-11cbd00….js:63
    (anonymous function) @ bundle-fontello.en-US-779b76a….js:81
    (anonymous function) @ /assets/bundle-lib.en-US-11cbd00….js:20

Notice that all network requests return OK(200).

**Comment by puzrin** [comment]
@DevinXian there was a bug with babelification, appeared in Safary, should be fixed in on of core sync with nodeca.

**Comment by Eblinkoff** [comment]
Good afternoon. Writes in the console like this:
Uncaught TypeError: Cannot read property 'load' of undefined
    at Object.<anonymous> (/assets/bundle-fontello.en-US-b2009306be04bc9b10d25ca91aab6b3d.js:2)
    at Object.l [as execute] ((index):2)
    at /assets/bundle-fontello.en-US-b2009306be04bc9b10d25ca91aab6b3d.js:1
    at Object.application/javascript ((index):2)
    at m ((index):2)
    at (index):2
    at <anonymous>
like a previous commenter shows loading...
also outputs a modal window in which writes: "assets load error: N.Wire unavailable after asset load."

**Comment by puzrin** [comment]
ctrl+f5 or something else with cache reset should help
