### ISSUE TITLE
Sometimes icons don't show on reload

### ISSUE THREAD

**Issue by aepedraza** [fontello/fontello#414]
Hi, I'm having this issue, sometimes the icons don't show where they should, and making several reloads to the page, sometimes you have the icons, and sometimes don't.
Here is the code:
```
<div class="socialize row">
    		<div class="col-md-4">
    			<button class="btn btn-github">
						<i class="demo-icon icon-github-circled"><!----></i>
						GitHub
    			</button>
    			<p>7 352 Followers</p>
    		</div>
    		<div class="col-md-4">
    			<button class="btn btn-twitter">
    				<i class="demo-icon icon-twitter"><!----></i>
    				Twitter
    			</button>
    			<p>136 312 Followers</p>
    		</div>
    		<div class="col-md-4">
    			<button class="btn btn-facebook">
    				<i class="demo-icon icon-facebook-1"></i>
    				Facebook</button>
    			<p>218 092 Subscribers</p>
    		</div>
    	</div>
```
The page is a local file. I tried in Chrome and is erratic. I uncommented the Chrome hack within the fontellos css
```
@media screen and (-webkit-min-device-pixel-ratio:0) {
  @font-face {
    font-family: 'fontello';
    src: url('../font/fontello.svg?87529430#fontello') format('svg');
  }
}
```
but the result is the same. The funny thing is that I wrote the code testing it in Chrome but in a PC with Win7 as a OS, and I'm having the issue in the very same Chrome but in a notebook with WXP as a OS. In both machines the Chrome version is the lastest and the only difference is the screen resolution, assuming that the OS doesn't interferes in this case.
Also I tried in Firefox and has the same error but it seems to be a little more stable
¿Any idea what could it be? Thanks so much in advance.

**Comment by puzrin** [comment]
No ideas. Can anyone reproduce it ?

**Comment by DarkSide666** [comment]
yeah, I have the same issue with my WinXP and latest Chrome :(

**Comment by puzrin** [comment]
Is it still a problem (i've updated font builder)?

**Comment by vykulakov** [comment]
I have the same problem in Windows XP. See #464 for detail.

**Comment by puzrin** [comment]
Let's close it in favor of #464 

@aepedraza , @DarkSide666 try to apply ttfautohint manually, as described in https://github.com/fontello/fontello/issues/464#issuecomment-201380787
