### ISSUE TITLE
Include the Material Design Icon font

### ISSUE THREAD

**Issue by shyndman** [fontello/fontello#415]
I'd be great to see our icons up on Fontello. :)

https://github.com/google/material-design-icons

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-suggest-font-to-fontello#how-to-prepare-a-font-for-use-with-fontello

Could you help to prepare this font? Need search aliases. ZIP file as described in Wiki will be enougth, i'll create then all repo things myself.

**Comment by kristofzerbe** [comment]
I have started to import at least 797 material design icons from Google's github page (the 48px SVG's). Could I seperate them into parts and you put it together afterwards?

**Comment by puzrin** [comment]
@kristofzerbe Look into typical fontello's prepared fon repo https://github.com/fontello/brandico.font

I finally need `config.yml` file & `src` folder. In any format that can be processed by simple scipt without manual work.

**Comment by kristofzerbe** [comment]
@puzrin Hmm, as suggested on https://github.com/fontello/fontello/wiki/How-to-suggest-font-to-fontello#how-to-prepare-a-font-for-use-with-fontello I have to download the webfont as ZIP, but it doesn't include src folder or config.yml?

**Comment by puzrin** [comment]
@kristofzerbe zip will be fine too. I'll convert it myself from `config.json`.

**Comment by kristofzerbe** [comment]
@puzrin I jave submitted a fontello font with at least 756 icons and created a new issue on that... :)

**Comment by shyndman** [comment]
Wow, thanks Kristof!

**Comment by puzrin** [comment]
Closing in flavour of #417

**Comment by puzrin** [comment]
> with at least 756 icons

@kristofzerbe does it means that more icons have to be added or something else?

**Comment by shyndman** [comment]
We have 795 icons, so something does seem off
