### ISSUE TITLE
bootstrap glyphicons are displayed not in the center vertically 

### ISSUE THREAD

**Issue by Deathangel908** [fontello/fontello#418]
I uploaded [bootsrap](http://getbootstrap.com/components/#glyphicons) svg glyphicons to fontello and found out that they are shifted to top compared to others. [Here](http://s2.postimg.org/a6nqn046h/bootsrap.png) the home icon is the bootsrap's one and the volume is Elusive (present by default on site).  Dotted line is firefox selection. So the icon takes extra space on top. The issue is that I can't shift it back with custom css. Nor margin border or padding affect on fontello icons. Could you please give an advice how to shift icons back to middle or probably fix this. Thank you in advance!

**Comment by puzrin** [comment]
Those are drawn in different ways. Ones are baseline-aligned, others are ~ middle-line aligned. You can open in fontforge to check.

Not combine-able without redraw.

**Comment by puzrin** [comment]
You can try to cheat in https://raw.githubusercontent.com/twbs/bootstrap/master/fonts/glyphicons-halflings-regular.svg with line

```
<font-face units-per-em="1200" ascent="960" descent="-240" />
```

set it to 

```
<font-face units-per-em="1200" ascent="1200" descent="0" />
```

but i don't guarantee anything...

**Comment by puzrin** [comment]
Seems bootstrap font is really drawn with bad offset. I don't know is it intentional or not.

**Comment by Deathangel908** [comment]
Thank you, that's it !

**Comment by puzrin** [comment]
Reported to https://github.com/twbs/bootstrap/issues/16633
