### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by demsking** [fontello/fontello#419]
Hi,

I cannot use fontello font on my project. I get this error on Chrome:
```
Failed to decode downloaded font: file:///tmp/site/font/icon.woff?74494834
Failed to decode downloaded font: file:///tmp/site/font/icon.ttf?74494834
```
And these error on Firefox:
```
downloadable font: cmap: out of order start range (59392 <= 59392) (font-family: "icon" style:normal weight:normal stretch:normal src index:1) source: file:///tmp/site/font/icon.woff?74494834 demo.html:230:12
downloadable font: cmap: Failed to parse format 4 cmap subtable 0 (font-family: "icon" style:normal weight:normal stretch:normal src index:1) source: file:///tmp/site/font/icon.woff?74494834 demo.html:230:12
downloadable font: cmap: failed to parse table (font-family: "icon" style:normal weight:normal stretch:normal src index:1) source: file:///tmp/site/font/icon.woff?74494834 demo.html:230:12
downloadable font: rejected by sanitizer (font-family: "icon" style:normal weight:normal stretch:normal src index:1) source: file:///tmp/site/font/icon.woff?74494834 demo.html:230:12
downloadable font: cmap: out of order start range (59392 <= 59392) (font-family: "icon" style:normal weight:normal stretch:normal src index:2) source: file:///tmp/site/font/icon.ttf?74494834 demo.html:230:12
downloadable font: cmap: Failed to parse format 4 cmap subtable 0 (font-family: "icon" style:normal weight:normal stretch:normal src index:2) source: file:///tmp/site/font/icon.ttf?74494834 demo.html:230:12
downloadable font: cmap: failed to parse table (font-family: "icon" style:normal weight:normal stretch:normal src index:2) source: file:///tmp/site/font/icon.ttf?74494834 demo.html:230:12
downloadable font: rejected by sanitizer (font-family: "icon" style:normal weight:normal stretch:normal src index:2) source: file:///tmp/site/font/icon.ttf?74494834
```
I checked each of fontello genered font (eot, ttf, woff) with http://www.fontsquirrel.com/tools/webfont-generator and the website told me that fonts was corrupted.

When I opened the demo.html file with old browser like Konqueror, there are no errors.

I'm using Ubuntu 15.04 and Chrome Version 43.0.2357.124 (64-bit).
I used Fontello API to download a zip file.

But after I imported config.json file to fontello and downloaded manually, it works.

How to fix the problem for API downloading?

[fontello.zip](https://docs.google.com/viewer?a=v&pid=forums&srcid=MDUyNzM2MTc1NDI1MDIxMTk1MDQBMDUzMDk3NjIyMDkyODIwNzk0OTcBRHJvbVB4Z1BzOEFKATAuMQEBdjI)

**Comment by puzrin** [comment]
I guess, problem is somewhere in your script.

https://github.com/fontello/fontello/blob/master/Makefile#L104-L135 - i've checked now fontello's script, it works without problems.

**Comment by demsking** [comment]
My Makefile:

```makefile
# Edit here - set path to you directory with config.json & fonts

FONT_DIR      ?= /tmp/fontello

### Don't edit below ###

FONTELLO_HOST ?= http://fontello.com

fontopen:
	@if test ! `which curl` ; then \
		echo 'Install curl first.' >&2 ; \
		exit 128 ; \
	fi
	curl --silent --show-error --fail --output .fontello \
		--form "config=@${FONT_DIR}/config.json" \
		${FONTELLO_HOST}
	curl --silent --show-error --fail ${FONTELLO_HOST}/`cat .fontello`


fontsave:
	@if test ! `which unzip` ; then \
		echo 'Install unzip first.' >&2 ; \
		exit 128 ; \
	fi
	@if test ! -e .fontello ; then \
		echo 'Run `make fontopen` first.' >&2 ; \
		exit 128 ; \
	fi
	cd ${FONT_DIR}
	rm -rf .fontello.src .fontello.zip css font
	curl --silent --show-error --fail --output .fontello.zip \
		${FONTELLO_HOST}/`cat .fontello`/get
	unzip .fontello.zip -d .fontello.src
	rm -rf ${FONT_DIR}/fontello-*
	mv -f `find ./.fontello.src -maxdepth 1 -name 'fontello-*'` ${FONT_DIR}
	mv -f ./fontello-*/* .
	rm -rf .fontello.src .fontello.zip ./fontello-*
```

**Comment by puzrin** [comment]
Please, create a repo with minimal possible set of nesessary files and instruction how to reprocude. Not enougth info to decide anything. As i said, api works with my data.

**Comment by mystadio** [comment]
I was just about to post about this issue, and while copy-pasting the error log, I noticed the include path were wrong (my fault though).

I created a less file which makes working with the font more flexible in my project. But when creating it, I kept the same path as the css file... Changed the paths and now it works.

@demsking Make sure the path "file:///tmp/site/font/icon.woff?74494834" doesn't yeild a 404 and/or is not requested from a http/s protocol.

Hope this helps!

**Comment by demsking** [comment]
Thank you @mystadio for your reply.
But, I don't get any 404 errors. The Chrome's errors are cleary:
```
Failed to decode downloaded font: file:///tmp/site/font/icon.woff?74494834
Failed to decode downloaded font: file:///tmp/site/font/icon.ttf?74494834
```
Files has been correctly downloaded, but decoding failed !
But I don't have this problem in the older browsers like Konqueror on PC or on Android with the default browser.

So, what is the problem?

**Comment by mystadio** [comment]
I had the exact same error messages. Chrome might be trying to parse *nothing*, which will fail.

Also, are you sure you can load fonts from the 'file' protocol? If you say the demo provided in the downloaded zip works, then the font files are properly encoded.

Good luck!

**Comment by demsking** [comment]
I tried to open ttf file with my system font program, and its work correctly. I can see all my icons's glyphs.
I also tried to open fonts from the 'file' protocol, and Chrome opening the download dialog.
```
file:///tmp/fontello-a184edfc/font/icon.ttf?94078742
```
But when I'm trying to open the same file with the Chrome's console, it don't show me the icons's glyphs, but the glyphs of alpha chars.

**Comment by demsking** [comment]
My problem was resoluted. My config.json was incorect. 
Thanks for your help.

**Comment by thujone** [comment]
fyi, rake assets:clobber seemed to help me

**Comment by ThorstenHans** [comment]
we're facing the same issue with electron `0.36.4` when packaging the contents of the app as `asar` package. The web-font is part of the asar package. The strange thing is that it works sometimes and sometimes not. it's not easy to reproduce. 

2 of 4 builds were fine. Loading the font works on both OSX and Windows. A few minutes later, another build (no changes made just package the app once again) generates an electron app that isn't able to decode the downloaded font. And to add another condition, it's not bound to a platform sometimes it breaks on windows and sometimes on OSX. 

We ended up in **deactivating asar packaging for the app** and all the problems were gone.

**Comment by himanshuwt** [comment]
![image](https://user-images.githubusercontent.com/21654174/39113026-eff5d936-46f7-11e8-9dbc-af60066bfce9.png)
same here, how can i fix it?

**Comment by himanshuwt** [comment]
Still getting this error.
