### ISSUE TITLE
Bug in Chrome / Windows XP - Icons distort

### ISSUE THREAD

**Issue by valeriabo** [fontello/fontello#420]
Im having a big issue. It happens in Chrome with Windows XP.
You first load the page and its ok but after a few minutes while you are navigating or even staying in the same page... the icon fonts seem to enlarge, distort. 
I already try a lot of stuff that I've found here or othere forums and nothing seems to work.

I attached an image ( i blured the products image on purpose for client reasons) but you can see the icons all distort.
![iconsdistort](https://cloud.githubusercontent.com/assets/12901768/8170599/7a52bf34-1377-11e5-9e44-4dcf93877faa.jpg)

Note: I generate a package with custom icons and some font awesome icons. 

Please help!

**Comment by puzrin** [comment]
No ideas. May be you have some problems with browser cache or override CSS selectors?

**Comment by puzrin** [comment]
Is it still a problem? can not reproduce.

**Comment by puzrin** [comment]
Close - can't reproduce, no feedback.
