### ISSUE TITLE
Custom SVG at the end

### ISSUE THREAD

**Issue by gladtobe** [fontello/fontello#421]
Hi, thanks for a such a wonderfull tool :) 

But i have a problem with custom svg. I wanted to add new svg icon and combine with entypo set which i use on my website. The problem is that new icon appears as the first one and all the unicode's are changed, which generating a problem. The result is, all the icons are moved one position forward.
Is there a chance, that I could generate webfont selecting custom svg which would be at the end? That would not change all the entypo unicode's inside the webfonts and I would be super happy.

**Comment by ixti** [comment]
Codes are automagically moved only upon conflicts. So, what you can do is:

- reset all existing changes
- import custom svg
- select imported icons
- (!) go to *Customize Codes* and set codes which are not in conflict with Entypo
- select Entypo icons

**Comment by puzrin** [comment]
See #283
