### ISSUE TITLE
how to create ligatures?

### ISSUE THREAD

**Issue by loominade** [fontello/fontello#423]
I need the symbols  📖, 💿, and a third symbol which combines the two.

But in the last one the  💿 should cover just the upper right corner of the 📖. My idea was to create a third icon which is a ligature for the string ```📖💿```

The *customise codes* interface only uses the first character added:
![the fiirst character to be added](https://cloud.githubusercontent.com/assets/11677380/8312178/799b5028-19db-11e5-8b21-b730c2bbd2fc.png)

Aren't ligatures possible?

**Comment by loominade** [comment]
The interface in this case could look like this:
![mokup](https://cloud.githubusercontent.com/assets/11677380/8312357/587cee78-19dc-11e5-9d5d-4962f03e75ee.png)

**Comment by puzrin** [comment]
Ligatures are not possible, although technical possibility was added to `svg2ttf` several months ago.

Is this feature still needed?

**Comment by puzrin** [comment]
Close in favour of #484. New design has mode for ligatures input.
