### ISSUE TITLE
Different unicode ranges have inverted escapements in generated CSS

### ISSUE THREAD

**Issue by johndrinkwater** [fontello/fontello#424]
Noticed this while migrating the glyphs from their autoassigned PUA codes, to their equivalent Unicode codepoints. As you can see in the link, Emoji characters are escaped in the comments, and use their byte representation in the CSS attribute, whereas the glyphs in the BMP are escaped in the CSS, and their byte representation in the comments! Thought this was a little odd, so reporting. 

https://github.com/SteamLUG/steamlug-font/blob/962e1349e185c56148ee79de790ba033e68503c9/css/font-awesome-trimmed.css#L72-L79

**Comment by puzrin** [comment]
That's workaround for Chrome, it had problems with escaped 3-byte chars in CSS. I don't know current sutiation with Chrome, but that's not a bug.

**Comment by johndrinkwater** [comment]
Ah, thanks, I didn’t know - found the related collection of reports here https://github.com/fontello/fontello/issues/255

**Comment by puzrin** [comment]
That was another bug, specific for Win8 displaying. This one is about CSS parse.
