### ISSUE TITLE
Syntactically identical configs produce corrupted font files

### ISSUE THREAD

**Issue by Romanx** [fontello/fontello#425]
Hey,

We had an issue with the output file from your API recently. We made a request using our config (find below) which succeeded, returned a session key and then we made a get request to the user to download the ZIP file. Everything seemed to be correct and then when trying to load the .woff file we found that it had gotten corrupted. 

Assuming a one-time problem we tried multiple times for just the same result. After attempting to do it manually i started testing our process piece by piece using the config file output in the zip file. It turns out that this config.json which is syntactically identical to ours (apart from the ordering of glyphs which i'm not sure should cause this kind of error) works and does not return a corrupted .woff file.

- Browser: None
- Steps: 
  - Request Session using Config
   - Use Session Key to Download files
   - Validate that .woff is not corrupted
- Data Files:
  - [Original Config (Broken)](https://www.masterofmalt.com/external_resources/github/files/mom_fontello_config.json)
  - [Downloaded Config (Working)](https://www.masterofmalt.com/external_resources/github/files/config.json)

**Comment by puzrin** [comment]
I don't know how you did it, but your first file contains 2 glyphs with the same codes:

```json
    {
      "uid": "95c84da411a955a12baff8b0859c9276",
      "css": "lock",
      "code": 59392,
      "src": "websymbols"
    },
    {
      "uid": "2cc73cc335f054682c04fe63439c4dcb",
      "css": "trash",
      "code": 59392,
      "src": "linecons"
    },
```

Second one has no dupes.
