### ISSUE TITLE
Can't import 'fontello-[...].zip' - unknown format

### ISSUE THREAD

**Issue by BoffinbraiN** [fontello/fontello#426]
I've always been able to load my Fontello config before by dragging the project zip file into the page, and the documentation still says this is possible.

However, there's been a regression in the last month or so that results in the above error message when trying to load a zip file.

Fortunately, dragging the config.json file still works.

**Comment by puzrin** [comment]
Can't reproduce. Is it still an issue? Could you provide your broken zip?

**Comment by puzrin** [comment]
\+ differend bugs in Chrome/FF:

- en-US: No translation for [fontello.app.import.err_bad_zip]
- Can't import 'fontello-8b95394d.zip' - unknown format

**Comment by BoffinbraiN** [comment]
Seems to be working now. Thanks!
