### ISSUE TITLE
Download Fails on node 0.12.2

### ISSUE THREAD

**Issue by jamespero** [fontello/fontello#428]
When attempting to download the selected glyphs the following error occurs on Mac OS X Yosemite 10.10:

[FATAL] system - 127.0.0.1 - "RPC fontello.font.generate?name=kitedesk&css_prefix_text=icon-&css_use_suffix=false&hi HTTP/1.1" - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" - [500] TypeError: undefined is not a function
    at ttf2woff (/Users/jamesperojr/Repositories/fontello/node_modules/ttf2woff/index.js:198:39)
    at /Users/jamesperojr/Repositories/fontello/server/font/_lib/worker.js:254:20
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:607:21
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:246:17
    at iterate (/Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:146:13)
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:157:25
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:248:21
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:612:34
    at /Users/jamesperojr/Repositories/fontello/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by puzrin** [comment]
That's strange. Try to comment woff generation https://github.com/fontello/fontello/blob/master/server/font/_lib/worker.js#L252-L260 and send me your downloaded zip archive. Need to take a look at config & ttf files.

**Comment by jamespero** [comment]
Ok, commented out woff, download queued but was followed by this error with no downloaded zip created:

[FATAL] system - UNCAUGHT EXCEPTION !!! TypeError: Cannot read property 'length' of undefined
    at Object.uint8ToBase64 (/Users/jamesperojr/Repositories/fontello/node_modules/base64-js/lib/b64.js:84:22)
    at /Users/jamesperojr/Repositories/fontello/server/font/_lib/worker.js:278:55
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:607:21
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:246:17
    at iterate (/Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:146:13)
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:157:25
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:248:21
    at /Users/jamesperojr/Repositories/fontello/node_modules/async/lib/async.js:612:34
    at /Users/jamesperojr/Repositories/fontello/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/blob/master/server/font/_lib/worker.js#L277-L282

Comment this lines too. See line numbers in error trace, if more errors happens and comment those blocks.

**Comment by puzrin** [comment]
Sorry, only this lines have to be commented

https://github.com/fontello/fontello/blob/master/server/font/_lib/worker.js#L278-L279

**Comment by jamespero** [comment]
Ok, that got me a zip. Sending now.

**Comment by puzrin** [comment]
Got it. Don't see anything suspicious. Imported config to fontello site and downloaded font without problems.

What happens if you roll back patches, import `config.json` from zip and try to download? Is error happens too, or only after you select glyphs manually?

**Comment by jamespero** [comment]
Rolled back changes, relaunched, cleared out the previously imported, and imported the config from the zip and everything worked fine, but no woff was generated in the resulting zip.

**Comment by jamespero** [comment]
I'm also noticing that there is no demo html or css being generated, not sure if that's related...

**Comment by puzrin** [comment]
Ah, clear `./public/downbload` folder, it cache previous result and don't create a new one.

**Comment by jamespero** [comment]
Ok, cleared that, reset everything, cleared everything, relaunch, imported config, and I'm seeing the original error.

**Comment by puzrin** [comment]
I can try to make local setup to check, but not nearest days, and i work under Ubuntu.

- Does it works without custom glyphs? (when you select from existing collections only)
- Which node version do you use? Fontello runs under 0.10.xx and i didn't tested 0.12 & iojs.

**Comment by jamespero** [comment]
Ok, still happens with the existing collections. I'm on 0.12.2. Let me try downgrading and see if that changes anything.

**Comment by jamespero** [comment]
Ok, that did the trick.

**Comment by puzrin** [comment]
So, problem caused by node version?

**Comment by jamespero** [comment]
Yes sir.

**Comment by puzrin** [comment]
Thanks. Updated title. Will investigate later.

**Comment by puzrin** [comment]
Close in flavir of #469

Master is already updated, but i'd recommend to wait ~ a couple of days until we finish polishing
