### ISSUE TITLE
API error: [413] Request Entity Too Large (solved)

### ISSUE THREAD

**Issue by ardalann** [fontello/fontello#432]
I'm trying to use the API for the first time. When I send a POST request to http://fontello.com/ I get this error:
```[413] Request Entity Too Large```

I tried adjusting the headers but I couldn't fix it. 

Here is one of my requests, for example:

Request headers:
```
POST / HTTP/1.1
Host: fontello.com
Content-Type: application/json
```

Response headers:
```
HTTP/1.1 413 Request Entity Too Large
Content-Type: text/plain; charset=utf-8
Vary: Accept-Encoding
Server: Sansun Calakci
Date: Fri, 07 Aug 2015 15:36:41 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```

**Comment by puzrin** [comment]
What is config size you try to upload? Could you post minimal example that reproduces this problem?

**Comment by ardalann** [comment]
@puzrin Sorry, I didn't realize the config parameter was required. (Maybe it should be mentioned here https://github.com/fontello/fontello#developers-api )
I included a config file and tried again. It worked! Thanks!

One comment, it would make things easier if instead of having to upload a 'file', we could put the config json directly in the 'config' post param.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport here are more details about different api helpers. If you think readme or wiki info is confusing - feel free to improve. If you think you have idea about useful improvement - create a separate ticket to simplify discuss/tracking.

Closing?

**Comment by ardalann** [comment]
Thanks @puzrin !
