### ISSUE TITLE
FA - update to 4.4, 4.5

### ISSUE THREAD

**Issue by puzrin** [fontello/fontello#434]
http://fontawesome.io/whats-new/

**Comment by knownasilya** [comment]
Yes please. This is the only reason I'm not using fontello to bundle my current icons.

**Comment by dotnetwise** [comment]
+10000

**Comment by Rewt0r** [comment]
4.5 is now out

**Comment by espretto** [comment]
versioning in general would be an absolute killer-feature!

**Comment by titocr** [comment]
Yep, 4.5.

**Comment by breadadams** [comment]
Is there an ETA on this? The _old_ version of the Google+ logo is haunting me :ghost:

**Comment by nofxx** [comment]
+1 using lot of new icons here =D
TY for fontello.

**Comment by ineentho** [comment]
Yesterday 4.6 was released leaving it even more outdates.

I hadn't noticed that you can upload your own font, but  today I tested it for up to date Google icons, works good enough while we wait for an update.

**Comment by breadadams** [comment]
Aha! Hadn't thought of that :thought_balloon: @ineentho - nice workaround

**Comment by gideoncresswell** [comment]
Title should now read update to 4.6 due to the new Instagram logo.

**Comment by sebastienbarre** [comment]
4.6 would indeed be great. Maybe an issue need to be added to [fontello/awesome-uni.font: transformed Font Awesome](https://github.com/fontello/awesome-uni.font), since this is the Git submodule Fontello [is importing](https://github.com/fontello/fontello/blob/master/.gitmodules#L6) internally. Or instructions on how to update that submodule to future Font Awesome versions, so that the community can help and push a PR...

**Comment by sebastienbarre** [comment]
@puzrin Is this you would accept a PR for? Or something you prefer to update yourself, usually? Thx.

**Comment by puzrin** [comment]
If anyone has time for that, any help will be appreciated. Repo is here https://github.com/fontello/awesome-uni.font, see details in makefile.

Actually, PR needs 2 files: updated original svg font & `config.yml`. Of cause, in buildable state.

**Comment by sebastienbarre** [comment]
@puzrin sounds good. Would you mind considering accepting or rejecting @mareksuscak's fontello/awesome-uni.font#5 before I start -- I work on a mac, and it seems it is [fixing something](https://github.com/fontello/awesome-uni.font/pull/5/commits/da4255f28c43f7336b8083dd64812f7b9b5c023e) to the Mac build (unclear). Thanks.

**Comment by puzrin** [comment]
@sebastienbarre i think no - it includes unnecessary changes in binary files.

- single glyph fix can be included to your update
- makefile changes are useful, but let make it saparate
- fontforge can be replaced with `svg2ttf` and install instructions will not be needed anymore.

I short: there are some useful things to extract, but PR needs cleanup.

**Comment by mareksuscak** [comment]
Yup i fixed the makefile.

**Comment by puzrin** [comment]
@mareksuscak thanks! I can accept PR immediately if you could remove autobuilded files from the first commit.

**Comment by mareksuscak** [comment]
Cool i can do that but right now im away from computer so will do that later, hopefully today.

**Comment by mareksuscak** [comment]
https://github.com/fontello/awesome-uni.font/pull/6

**Comment by digeomel** [comment]
What's the current status on this? I noticed in font awesome some icon names are also changed (e.g. "fa-clock" is now "fa-clock-o") and I'd love to get the latest version just for this.
Thank you very much, keep up the good work! :+1: :smile:

**Comment by digeomel** [comment]
> I hadn't noticed that you can upload your own font, but today I tested it for up to date Google icons, works good enough while we wait for an update.

@ineentho Unfortunately this doesn't work very well, because you can only upload SVG fonts and the glyph names are missing, so you would have to enter all glyph names one-by-one! :disappointed:

**Comment by ineentho** [comment]
@digeomel Yea, but I only needed a few icons so that worked for me. Of course I'd rather see the font updated instead of doing manual work.

**Comment by sebastienbarre** [comment]
Hopefully I can start working on this over the weekend...

**Comment by sebastienbarre** [comment]
@puzrin Just a quick update; I'm in the process of writing the PR to update to Font Awesome 4.6.3. The build process in awesome-uni.font seems broken for OSX, though I suspect it's broken on Unix too:
```
awesome-uni.font (fa4.6.3)$ awesome-uni.font/node_modules/.bin/svgo -f /var/folders/9g/_h11phvx4vv0h85qt0swr4xh0000gn/T/fstools.d02c0e --config awesome-uni.font/node_modules/svg-font-create/svgo.yml
awesome-uni.font/node_modules/svg-font-create/svgo.yml:1
(function (exports, require, module, __filename, __dirname) { # replace default config
                                                              ^
SyntaxError: Unexpected token ILLEGAL
```
This is a problem with SVGO, which has been reported [here](https://github.com/svg/svgo/issues/223) and [here](https://github.com/svg/svgo/issues/218). It is a tad unclear where the fix can be found, the latter issue mentions 0.5, but it seems fixed inh 0.4 too. For the sake of getting this done quickly, I'll update the dependency to SVGO to the latest 0.6.6 in my PR.

**Comment by puzrin** [comment]
@sebastienbarre remove it at all.

**Comment by sebastienbarre** [comment]
I'm not sure how to partially revert a commit that way.
The "only" files that were modified are:
```
config.yml
DEVELOPMENT.md 
package.json
src/original/fontawesome-webfont.svg
```
and `src/svg/ajust.svg` which was deleted, because it was misspelled (should be `adjust.svg`)

**Comment by puzrin** [comment]
Updated to 4.6.3, big thanks to @sebastienbarre for the help.
