### ISSUE TITLE
Material design icons

### ISSUE THREAD

**Issue by katgironpe** [fontello/fontello#435]
Have a project wherein I use 2 fonts: **Font Awesome** and **Material Design**. The site's pretty useful and hope material design icons can selected from there. 

Meanwhile, I am reading through https://github.com/fontello/fontello/wiki/How-to-use-custom-images and downloading FontForge to merge the icons.

**Comment by puzrin** [comment]
seems duplicate #417

**Comment by katgironpe** [comment]
Yep it is. I'm gonna watch that issue. So this is quite an urgent thing for me. I will help out if I can later. Thanks for your answers there.

**Comment by puzrin** [comment]
That issue was holded due fontforge bug (could not convert ttf to svg format), but they had to release patch. I didn't tested yet.

**Comment by katgironpe** [comment]
Gonna check. I'm trying out another option for converting TTF to SVG.
