### ISSUE TITLE
Custom font not displaying in IE

### ISSUE THREAD

**Issue by BrassMonkeyII** [fontello/fontello#436]
I created a custom font of icons in fontello. They display fine in Chrome, Firefox etc - but not at all in any version of IE. I've used "fail-safe, bullet-proof" methods of the @font-face rule to get them to display, and nothing's happening:

        @font-face{
	font-family:"triangle";
	 src: url('fontello-webfont?#iefix') format('embedded-opentype'), 
         url('fontello-webfont.woff') format('woff'), 
         url('fontello-webfont.ttf')  format('truetype'),
         url('fontello-webfont.svg#svgTriangle') format('svg');
}

My CSS is then:

#div{
color:#000000;
}

         #div:before{
          font-family:triangle;
          content:"\E801";
          color:#000000;
          font-size:18px;
}

Any ideas why it doesn't work in IE? Thanks!

**Comment by diegoflorez** [comment]
Check the Embedding permissions of your 'fontello-webfont.ttf'  file.
Use https://github.com/thegregorator/ttembed-js or https://github.com/hisdeedsaredust/ttembed to solve this problem.

**Comment by puzrin** [comment]
@diegoflorez 

- https://www.microsoft.com/typography/otspec/os2.htm#fst
- https://github.com/fontello/svg2ttf/blob/master/lib/sfnt.js#L19

Are you sure changing fstype 8 -> 0 is good idea?

**Comment by diegoflorez** [comment]
If IE prints something like:
CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
fontawesome-webfont.ttf

Use ttembed to change the fstype should solve the problem.

**Comment by puzrin** [comment]
@diegoflorez Have you seen such error with any of fontello fonts? That's not the same as fontawesome.

**Comment by diegoflorez** [comment]
@puzrin Yes, I have seen this error with the last fontello font I have used with some custom svg icons imported to the font.
Am I doing something wrong?

**Comment by puzrin** [comment]
> Am I doing something wrong?

Nothing wrong. I try to collect info to reproduce this problem. As you can see, fsType was 8 in fontello from the begining, june 2013 https://github.com/fontello/svg2ttf/blame/master/lib/sfnt.js#L19. It's a bit strange that problem happened only now.

Could it depend on IE / Win version?

**Comment by diegoflorez** [comment]
I'm a regular linux user, so I didn't see this problem for long time. But, It was happening on windows 7, on IE8, 9, 10, 11 and Edge.

**Comment by puzrin** [comment]
I have no win too :) . Thanks for info.

**Comment by diegoflorez** [comment]
Thanks to you, for your work on Fontello. ;)

**Comment by puzrin** [comment]
Should be fixed by https://github.com/fontello/fontello/commit/ede4786ca6bb15418324ade26638419cd2f48ad6
