### ISSUE TITLE
[Feat Req.] Website export just config.json

### ISSUE THREAD

**Issue by kkprince1998** [fontello/fontello#437]
Hello,
On your website, you can import config.json from previous downloads. Since I use your API to deploy my project, all I really need is that config.json, but alas I have to wait for the entire font set to download. My idea is as follows, add a simple Export button below your already existing import button so that people that only need that json file can download just that json file.

**Comment by vikeri** [comment]
I could also use this :+1:

**Comment by kkprince1998** [comment]
I have such a low bandwidth, I might as well be on dailup :smile:! When I deploy the project, I have it setup on my server to download resources like this.
