### ISSUE TITLE
Working around font download being disabled in IE

### ISSUE THREAD

**Issue by herbrandson** [fontello/fontello#438]
We've had a handful of IE users who have disabled font downloading in IE (usually because of some corporate setting/policy). We'd like to have a fallback mechanism in place for this scenario. Are there any best practices that people are using for this case?

**Comment by puzrin** [comment]
For some icons you can set the same codes, that similar chars has in system font. But in general, if fonts are disabled, no good solution exists. IMHO, that's like disabling javascript - it can help, but will break everything. Probably corporate policy should be tuned more carefully.

**Comment by herbrandson** [comment]
I agree about disabling fonts being like disabling javascript. However, we have users on IE who have corporate policies that disable font downloads by default. This is obviously out of our control, so we're looking for a workaround. I was hoping there was an easy way to detect this case and disable the icons. Right now our users are seeing Chinese characters (which has actually made at least one user worry that the site had been attacked by Chinese hackers).

**Comment by Jamesking56** [comment]
I'm experiencing the same as this, corporate users have font downloading disabled and it is showing Chinese characters for them.

**Comment by puzrin** [comment]
Closing - not related / not fixable.
