### ISSUE TITLE
Suggestion: Printable keyboard layout displaying which keys will produce which icon 

### ISSUE THREAD

**Issue by jasonmerry** [fontello/fontello#440]
I created a font for work which is purely icons and I assigned each icon to one of the 96 available characters on the keyboard for getting graphics into SVGs and of course other site graphics.

Now the business wants to use them in Word and similar software so people can create their own documents without the need for a designer to get involved. 

The one thing we really need is a keyboard layout that can be printed out showing which icons will be produced when a key is pressed. Now, I can spend time putting one together in one of the Adobe programs and sure it will look lovely but this sort of thing must be able to be automated and then be able to be printed out as a cheatsheet or keyboard overlay.

If this was a feature of Fontello it would be awesome. 

Any chance?

**Comment by puzrin** [comment]
Each font includes demo, that can show charcodes. Also it includes full config, and you can use it to renerate something else.
