### ISSUE TITLE
Generate fonts that are reverse compatible with original fonts

### ISSUE THREAD

**Issue by jhaglund** [fontello/fontello#444]
I have an existing design which uses the UTF character code sometimes, instead of CSS class names. For example &lt;span class="fa"&gt;&amp;#xf1db;&lt;/span&gt; will render that character using the font-awesome font, and it shows up as a circle. (see more characters: https://fortawesome.github.io/Font-Awesome/cheatsheet/ )

But if I use fontello to extend FontAwesome, the characters aren't the same so my previous design is broken.

Is there a way for fontello to preserve character compatibility with base fonts (like FontAwesome)?

Like just add new characters and icons to an existing font?

Thanks!

**Comment by puzrin** [comment]
In advanced settings - select "unicode" encoding
