### ISSUE TITLE
Feature Request: Select/deselect entire font at once

### ISSUE THREAD

**Issue by jrdnbwmn** [fontello/fontello#445]
This would probably be some kind of link/button by the title of a font that you could hit and it would select the entire family for you. 

This isn't necessarily the same thing as multi-select (as discussed on #153), it's more about ease of selecting an entire family at once, which I find myself doing a lot particularly when I upload a bunch of custom icons.

Icomoon does this and I find it to be very useful.

**Comment by rowaraujo** [comment]
+1

**Comment by puzrin** [comment]
@jrdnbwmn do you mean full selection for any font or for custom icons only?

**Comment by jrdnbwmn** [comment]
I can see the same benefits for both.

**Comment by puzrin** [comment]
Close in favour of #484 (new design allows font menu)
