### ISSUE TITLE
Idea - Exclude similar icons (website)

### ISSUE THREAD

**Issue by rowaraujo** [fontello/fontello#447]
I selected to download all the icons in fontello.com, but i wanted to delete all similar icons in a selection. So... i would like to appear a list of all the similar icons and i can choose a list of icons.

**Comment by nicooprat** [comment]
Selecting **all** icons is clearly not the purpose of Fontello – the exact opposite actually. You should only select icons that you need, not to force your users to download megabytes of unused fonts.

You could also use the search feature on the site to deselect similar icons for a specific term.
