### ISSUE TITLE
Idea - Do a reset button and/or saving project

### ISSUE THREAD

**Issue by Bob0t** [fontello/fontello#448]
This is very cool to be able to build a custom font as easily, but there is no way to reset selected icons, or save project, or anything like this (like if you want to work on a totally different project).

So, if you have time, and you want to do this, this would be a great upgrade :+1:

**Comment by ixti** [comment]
![20151015_16 17 16_selection 001_1365](https://cloud.githubusercontent.com/assets/94782/10516424/728ff47e-7358-11e5-8d31-15a6fc1fb2ed.png)

Reset button already in there. And once yhou have saved font, there's config.json file that you can _import_.

**Comment by Bob0t** [comment]
Just retrieved my account access ! Thank you so much ! I'm feeling so mad about this option I didn't seen (a)

**Comment by ixti** [comment]
All good! :D Glad it helped :D
