### ISSUE TITLE
Session Sharing (request)

### ISSUE THREAD

**Issue by thiagof** [fontello/fontello#449]
Think it is not possible to share the current set (session) with other designers.

To allow other people to follow, there is a whole set of complications (priorly to match names, codes, selected stack, etc)

IMO would be beneficial to have some sort of session sharing feature.

Simple Eg. use case:

- User A select some fonts
- User B wants to checkout and make some changes
- User A export its session
- Fontello generate a session file, downloadable
- User A sends the session file to user B
- User B loads and loop the interaction

**Comment by thiagof** [comment]
Looking at the readme (sorry not reading first)
Seems like there is the session persistance already.

But there is a link the front-end to use the session link?

**Comment by dotnetwise** [comment]
+1 Add a button -> `Share` which would generate a link that includes the serialized local storage settings, so other developers can start from the same settings

Also that link can be added to git e.g. versioned

**Comment by thiagof** [comment]
Seems the session sharing (link) is persisted for limited time.. The api for creating a session describes it.

Liked the idea of version control, like exporting/loading the whole session and keeping it in the repository.

**Comment by puzrin** [comment]
Your font state is stored in zip archive in `config.json`. You can drop it to fontello page and continue work anytime.

Link sharing is another deal. That expects hosting files, and fontello does not store users data. Probably, it's possible to do temporary links for 1day, but i don't know if it's useful. Create another issue for that to discuss.
