### ISSUE TITLE
Adding to the Fontello fonts and CSS

### ISSUE THREAD

**Issue by dtjones369** [fontello/fontello#450]
My site already uses Fontello fonts and CSS. 
I made some new icons which created a new css and font.

I have gotten the new font to work, but it then cancels out other icons, such as social. I then changed the a customized code, still had icons missing and my new font show as Asian characters. 

I have tried adding a new CSS line in the page. Also tried adding the new font to the Fontello CSS. 
Keep running into Character Code issues.

Is there anyway to merge the 2 files/fonts/css or how can I customize the codes in letters/numbers that are not used?

Thank you,
Dean

**Comment by puzrin** [comment]
Codes and names are customised on second and third tabs. You can partially merge only custom icons, as far as i remember, if you import .svg file. CSS is generate automatically.

If you have conflicts between 2 fonts - make shure you use different font faces for each.
