### ISSUE TITLE
ttfautohint error ubuntu

### ISSUE THREAD

**Issue by gerardoBSjunior** [fontello/fontello#454]
error sudo ttfautohint --no-info --windows-compatibility --symbol /tmp/fontello/fontello-92102d89/font/fontello-unhinted.ttf /tmp/fontello/fontello-92102d89/font/fontello.ttf

Error in `ttfautohint': malloc(): memory corruption: 0x088f1ce0

**Comment by puzrin** [comment]
What is that? Not sure ttfautohint bugs should be reported here.

**Comment by puzrin** [comment]
Probably this could be solved on one of ttfautohint version. If you still have this bug - please, provide more info how to reproduce (zipped font or zipped config)
