### ISSUE TITLE
Remove query string number from font URLs

### ISSUE THREAD

**Issue by flaviotordini** [fontello/fontello#455]
I'm using the HTML5 application cache manifest and it's annoying to change it every time the Fontello font is updated.

Here's a similar bug in the Font Awesome project: https://github.com/FortAwesome/Font-Awesome/issues/3286

**Comment by puzrin** [comment]
Just use css file with codes only and write your own font definition.

**Comment by flaviotordini** [comment]
This way, if fontello.css gets improved I don't get the update. I have to manually keep my copy in sync. Btw, what is the rationale for the query string numbers?

**Comment by puzrin** [comment]
The probability if such improvment is about zero :) . Timestamping (after `?`) was requested by people who update regular websites.

It's impossible to include all files for all use cases. But i tried to provide build blocks to simplify customizations. Also, you can write scripts to use fontello via API and automate such things (removing & from CSS and so on).
