### ISSUE TITLE
Font Awesome 4.5.0

### ISSUE THREAD

**Issue by sodbileg** [fontello/fontello#457]
Hi. When is Fontello going to be updated with Font Awesome 4.5.0?

**Comment by geekitude** [comment]
I second this, it would be really nice :)

**Comment by tikiki** [comment]
Yep, I would love it too, I would like to use icons which are not included on Fontello now :p

**Comment by sylvainar** [comment]
The same for me ! :)

**Comment by vremy** [comment]
For now you can upload the new fontawesome font (svg file) to fontello and use that  :) The disadvantage is that you have to fill in all the character names for the font...

**Comment by sodbileg** [comment]
@vremy, Didn't know about that. Thank you so much for the info. The disadvantage wasn't that bad for me, because I just wanted a new Google+ icon. Fontello is great :)

**Comment by puzrin** [comment]
Dupe of #434
