### ISSUE TITLE
You're awesome !

### ISSUE THREAD

**Issue by MentalGear** [fontello/fontello#459]
Hey,

Just wanted to tell you how awesome you guys are. I use Fontello in almost every of my projects, and it has such a nice and comfortable GUI and this was really over-due. Thanks for making this and keep up the good work !

+1 for everyone who agrees !

**Comment by mistertest** [comment]
Yes there is no "thank you page" so i congratulate you here, Fontello is an incroyable tool for the developpement Frontend. Since 2004 i says that SVG is the futur, with your tool SVG is now so powerful. I will give somes icons fonts, for the community certainly. Thank you .

**Comment by puzrin** [comment]
thanks :)
