### ISSUE TITLE
Imported .svg = nada

### ISSUE THREAD

**Issue by eliuserman** [fontello/fontello#461]
Hi there
I don't know why, but some .svg files that I import end up as blank spots - nothing there.
Why is that and what should I do to fix it?

**Comment by mistertest** [comment]
hello yes of course, it is important to work on your required svg:
the size, the vector itself and the manner in which the elements are assembled.

**Comment by eliuserman** [comment]
Thanks mistertest, I tried it all and still... I guess that I miss something...

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-use-custom-images#importing-svg-images

**Comment by eliuserman** [comment]
Hi Vitaly, thanks a lot!
The online solution did it (after paying with the settings)
P.s love your project !
