### ISSUE TITLE
403 error on the website using fontello fonts in the theme

### ISSUE THREAD

**Issue by cshirish** [fontello/fontello#462]
Hi, 

I am getting Failed to load resource: the server responded with a status of 403 (Forbidden) error in the console for a WordPress theme which loads fontello fonts.  Can you please help me solve the issue. 

When I ask the server and theme provider both referred to this document. I have set .htaccess file according to the code provided but nothing has yet worked for me. 

Please help me solve the issue. 

<img width="1280" alt="screen shot 2015-12-26 at 3 45 43 pm" src="https://cloud.githubusercontent.com/assets/519768/12290313/14ff9d3c-ba07-11e5-8fb8-5dc7c4d02118.png">

Thank you,
Shirish

**Comment by puzrin** [comment]
Ask someone local with admin skills why your server forbids fonts file download. That's not fontello issue.

Other settings are described in https://github.com/fontello/fontello/wiki/How-to-setup-server-to-serve-fonts
