### ISSUE TITLE
Invalid Host and Error 404

### ISSUE THREAD

**Issue by Vekseid** [fontello/fontello#465]
So I tried setting this up on my own server to see if I could play with it, following the instructions in INSTALL.md (and do things like update Font Awesome, strip out fonts I don't care for, add ones I do, etc.)

Got it running, and despite setting mount: in the config, it says 'invalid host'.

So I make that part in server.js return true to get it out of the way.

After which it returns 404

Is something in the current config examples missing?

**Comment by puzrin** [comment]
Try with node 0.10 :) . I'll update things when have a time.

It should run on localhost by default. No ideas what can be a problem.

**Comment by Vekseid** [comment]
Gah. Using node 4 right now.

I can wait. Just wanted to see if I could help push things along. : )

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/issues/469 ref for tracking

**Comment by puzrin** [comment]
Master branch now deployed to fontello site. It's ok and uses node 4.+
