### ISSUE TITLE
"Communication problems. Try again later." When trying to download font.

### ISSUE THREAD

**Issue by matbush** [fontello/fontello#466]
I'm trying to download a small icon font (19 icons) in Chrome it endlessly loads and both Firefox and Safari show the error message: "Communication problems. Try again later." Not sure what the issue is exactly, whether it's something I'm doing wrong.

I'm currently using a Mac, I've tried on another Mac on the same network but to no avail, I'll be able to try on another network later today.

- OS: El Capitan 10.11
- Browser: Chrome v48.0.2564.97
- Tried with Firefox 44.0
- Tried with Safari 9.0

Thanks!

**Comment by puzrin** [comment]
already fixed

**Comment by matbush** [comment]
Perfect, thank you!
