### ISSUE TITLE
fontello.com not working in IE11

### ISSUE THREAD

**Issue by jamiehutber** [fontello/fontello#467]
Whilst we have moved to edge, which it works fine in, the rest of the site doesn't work in ie11. This could be my machine alone. Its also worth pointing out that I am using a Windows 10 machine.

Still:
<img>http://i.imgur.com/VK13m8e.jpg</img>

```javascript```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
fontello.com
HTML1300: Navigation occurred.
fontello.com
CSS3111: @font-face encountered unknown error.
icons-0b87cb255d9bd69cbb117b6b005efec9.eot
CSS3111: @font-face encountered unknown error.
icons-10afb1e215459c09bf6a108efc9e3437.woff
CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
icons-0dffee7f9633f92ea5f93c9a05e8165d.ttf
CSS3111: @font-face encountered unknown error.
fontello-840ada64de2cb1e470a8a2d6e58823ab.eot
CSS3111: @font-face encountered unknown error.
fontello-e2978774977f71a86817d3c0308f49cc.woff
CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
fontello-348e8a6aeb62db2d9e2ed6678f652fb3.ttf
```

I feel like you will need more information, lay it on me.

**Comment by puzrin** [comment]
Hmm... info about installable permission is useful. Thanks.

Here are records https://github.com/fontello/svg2ttf/issues/45

Could you tell me, how to reproduce those messages?

**Comment by puzrin** [comment]
https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/ i could not find here ie11 + win 10 :(

Edge + win10 seems to work. Any ideas how to reproduce?

**Comment by jamiehutber** [comment]
I believe to get IE11 you need to install the Pro edition of Windows 10. Ye I had/have no problems with Edge. 

As for producing the errors I navigate to http://www.fontello.com/ Upon seeing no fonts I open the console, reload the page and see the above errors.

But I did find this if it is not already installed on the system: http://stackoverflow.com/questions/32085395/how-to-force-installation-of-ie-11-on-windows-10

I do have Win10 at home. I hope this is just an edge case.

**Comment by AndrewCraswell** [comment]
I'm unable to reproduce on Windows 10 with IE 10 v11.0.10240.16678. Fonts display fine, but the following error is logged in the dev tools console:

```
CSS3111: @font-face encountered unknown error.
fontello-840ada64de2cb1e470a8a2d6e58823ab.eot
```

**Comment by puzrin** [comment]
@jamiehutber could you check now (ctrl+r / ctrl+f5 to reset cache) ?

I've updated svg2ttf, used to build fonts https://github.com/fontello/svg2ttf/blob/master/CHANGELOG.md#300--2016-02-12

**Comment by puzrin** [comment]
Close - timed out. Hope it works now.

**Comment by wpatter6** [comment]
This doesn't work. Here is a screenshot of the site in IE 11: http://prntscr.com/j4l0wf

Here are the errors in the console log:

CSS3111: @font-face encountered unknown error.
icons-c422a1666672d9d5ef8fcd024fded937.woff
CSS3111: @font-face encountered unknown error.
fontello-8f37719b6edc21bdb935c8a983e5d401.woff

I am also unable to get downloaded fonts to display in IE 11 on my page.  Here is the log from that:

CSS3111: @font-face encountered unknown error.
fontello.eot
CSS3111: @font-face encountered unknown error.
fontello.woff
CSS3111: @font-face encountered unknown error.
fontello.ttf

IE is frustrating, but sadly, I must find a way to support it.  Hopefully that doesn't mean I can't use your awesome tool!
