### ISSUE TITLE
Cannot add SVG font

### ISSUE THREAD

**Issue by smurn** [fontello/fontello#470]
I have a SVG file with some glyphs in it and tried to add it. But no symbols appear. 

I thought my SVG might be faulty, so I've seleted a few random symbols from the existing ones, downloaded the zip generated by fontello, extracted the SVG from it, and tried to upload that. Didn't work either.

Tested on firefox and chrome.

**Comment by puzrin** [comment]
Ups... missed one package upgrade. Should work now.
