### ISSUE TITLE
Strange issue with a recent font generation

### ISSUE THREAD

**Issue by mikebaldry** [fontello/fontello#471]
Hi there,

I recently created a new font with a single icon, it worked great for me, but started having problems when my team were playing with the feature I'd built and couldn't see the icon - all in Chrome on OSX. It works fine in other browsers for them, but it works fine in my Chrome also.. 

We've switched to a fontello font we generated for another project, which has the same character in (plus many others we don't need for this project) it for now, and this is working for everyone. 

Not sure whats happened or how to diagnose the issue! Even the demo.html has the same issue so its not due to implementation on our part. The demo.html works for me in exactly the same version of Chrome as a colleague where it doesn't. 

Its using the woff version, you can see it loading it in the network tab, but again, it doesn't display anything (not even unprintable character) if you set the content to be a printable character, it appears to be using a fallback font, but no warning saying it couldn't load the woff..

I've attached the zip, if that helps.

[fontello-8f28867b.zip](https://github.com/fontello/fontello/files/132693/fontello-8f28867b.zip)

**Comment by puzrin** [comment]
Could you redownload font and check again?

**Comment by puzrin** [comment]
Closing. Time out, let me know if problem still exists.
