### ISSUE TITLE
My fontello icons library is not working in my website

### ISSUE THREAD

**Issue by robertochingon** [fontello/fontello#472]
Hi, 
 
   I have just created a custom icons library for my website. The example is working well, however when I import it in my project I don´t see any icon. 

My webserver is Nginx. I read the readme and I´m aware some tuning should be done. But before that, I have to say, I´m already using font-awesome perfectly. I see the font extensions are exactly the same in font-awesome and fontello, so I´m wondering If I really need to do that tuning or it is another problem.

This is the code I have inserted: <i class="demo-icon icon-yanpy-skipper">&#xe801;</i>
And I see the screenshot attached.
<img width="93" alt="captura de pantalla 2016-02-19 a la s 21 15 11" src="https://cloud.githubusercontent.com/assets/4256081/13187839/20866aaa-d74e-11e5-868f-9eeaf59e5e35.png">

**Comment by stooni** [comment]
Which File are created and which have uploades - how you import this?
and why the example working well?

---- pls. precise!
---stooni

**Comment by puzrin** [comment]
Close - timed out
