### ISSUE TITLE
Not all icons are generating

### ISSUE THREAD

**Issue by moniquep** [fontello/fontello#474]
I can't work out what the problem is, I've tried clearing the cache and cookies, assigning a different name, using a different browser, unselecting and selecting all. It's a bit worrying as my website uses the icons and next time I update they won't be there.

Evidence
https://www.dropbox.com/s/qzxargrf3km65sl/Screenshot%202016-02-23%2016.39.30.png?dl=0

Thanks,
Monique

**Comment by stooni** [comment]
Hello Monique!
what for a update you make - have you a Theme or a Link?
Befor i have changed some font Files in Divi Theme- perhaps Xing Icon in the first Version of Divi theme was not there!?
----stooni

**Comment by moniquep** [comment]
I'm not sure what you mean but we use fontello on our website http://www.onthehouse.com.au/. I'm not a developer, I use the icons in my designs.

**Comment by puzrin** [comment]
Try to open demo page, included into archive. If it doesn't show some icons - provide your config file (or full zip archive with generated font)

**Comment by puzrin** [comment]
Also provide your config or zip please.

**Comment by puzrin** [comment]
Close - outdated, can't reproduce.
