### ISSUE TITLE
Change icon on hover

### ISSUE THREAD

**Issue by askaza** [fontello/fontello#475]
Hi! I need some help.
For example, I have on site `.icon-star-empty`, and on hover I need it to be changed to  `.icon-star`.
I can change just unicode symbol in content styles, like this:

`.icon-star-empty:hover:before { content: "\e81e"  }`

 This solution doesn't work actually. We add or remove some new icons very often and I realized that code of  `.icon-star` could be changed, it's not a constant and I can't use it.
Any suggestions?

**Comment by puzrin** [comment]
AFAIK, if you import old project, icon codes should not change until you unselect it. I'd suggest 2 solutions without direct code dependencies:

1. Use 2 icons (1 hidden + 1 visible), and change visibility on hover. Not very semantic, but will work everywhere.
2. You can write script to load `config.json` and generate your additional css rules by icon name.
