### ISSUE TITLE
Complex icon can break output

### ISSUE THREAD

**Issue by smckenzie87** [fontello/fontello#477]
I have made several Fontello fonts in the past. But on my most recent project whenever I try and update the existing font the following happens:
![screen shot 2016-02-25 at 3 18 16 pm](https://cloud.githubusercontent.com/assets/17483508/13334819/782fb552-dbd3-11e5-8131-babcd43b3283.png)

**Comment by puzrin** [comment]
Could you provide configs of old and new fonts (or zip archives with those fonts)?

**Comment by smckenzie87** [comment]
[fontello-new.zip](https://github.com/fontello/fontello/files/147341/fontello-new.zip)
[fontello-old.zip](https://github.com/fontello/fontello/files/147340/fontello-old.zip)

**Comment by puzrin** [comment]
Problem is with `nozzle-ptn-soft-wash` icon. If you unselect it, others will be ok.

May be too many segments, self-intersections and so on. I think, you can find it better and faster than me. Let me know about results. Probably it worth to create separate issue when more info available. Even if icon is bad, it should not fuckup everything.

**Comment by smckenzie87** [comment]
Thanks!

**Comment by puzrin** [comment]
Any news?

**Comment by smckenzie87** [comment]
Works perfectly now. Thank you

Sent from my iPhone

On Mar 2, 2016, at 6:26 AM, Vitaly Puzrin <notifications@github.com<mailto:notifications@github.com>> wrote:


Any news?

**Comment by puzrin** [comment]
Could you tell me details what was wrong with tan icon?

**Comment by smckenzie87** [comment]
It was one of the more complicated icons. I just changed the size a bit, re-uploaded it and it worked. Not sure more than that what actually was wrong with it.


Stephanie
--
Stephanie McKenzie
Studio Artist
608.256.6357

Hiebing // AdAge 2015 Small Agency of the Year // hiebing.com

**Comment by puzrin** [comment]
[fontello-432747d8.zip](https://github.com/fontello/fontello/files/165709/fontello-432747d8.zip)

Reduced set to 2 glyphs only, for history. No ideas why it's ok in browser but broken after server build (does not depend on hinting). May be will look sometime if someone else report similar problem.

Closing since self-resolved (disappeared after image resize).
