### ISSUE TITLE
BUG SVG line rounded ends

### ISSUE THREAD

**Issue by s-figuccia** [fontello/fontello#479]
Hi guys! I have a problem with few icons, in particularly when the icons end with rounded line they are "digged". So, I have attached an example of my icons [set-icons.zip](https://github.com/fontello/fontello/files/156665/set-icons.zip) and the result
[BUG-svg line rounded ends.zip](https://github.com/fontello/fontello/files/156636/BUG-svg.line.rounded.ends.zip). 
Thanks

**Comment by puzrin** [comment]
Could you attach a zoomed in screenshot and point to bad peace? I can't understand what is wrong.

**Comment by simone-sanfratello** [comment]
here the wrong icons (in the html are too small for see the problem)
![fontello-bug](https://cloud.githubusercontent.com/assets/5823031/13599701/b9d549cc-e524-11e5-951c-ec6076407059.png)

if you open the svg file into set-icons.zip with another program, like inkscape, you see them correct

**Comment by puzrin** [comment]
Thanks!

Problem is with ARC segments. I've exatracted minimal sample to investigate:

```svg
<svg viewBox="0 0 50 50">
<path d="m 7.4357552,13.892812 a 5.6575324,11.435414 0 1 0 0.5298119,22.845743 l 33.9079619,0 a 5.6518921,11.424014 0 1 0 0,-22.845743 l -33.9079619,0 a 5.6518921,11.424014 0 0 0 -0.5298119,0 z" />
</svg>
```

The same, but scaled to 1000x1000

```svg
<svg viewBox="0 0 1000 1000">
  <path d="m 128.88403,263.83707 a 120.61395,243.79363 0 1 0 11.29515,487.05245 l 722.88965,0 a 120.49365,243.55051 0 1 0 0,-487.05245 l -722.88965,0 a 120.49365,243.55051 0 0 0 -11.29515,0 z" />
</svg>
```

As temporary solution - replace arcs with bezier curves.

**Comment by puzrin** [comment]
Fixed by https://github.com/fontello/fontello/commit/2c586eda1bf3c7f5f84323d74a937f82cd2acd4c

I still recommend to join everything to compound path prior to import.
