### ISSUE TITLE
Import window doesn't open in Safari

### ISSUE THREAD

**Issue by bawpcwpn** [fontello/fontello#482]
Trying to import a JSON config file fails to show File Browser window. 

Tested in Safari 9.0.3 and Safari 8 (BrowserStack version) on OS X 10.11.3 and 10.10 respectively.

**Comment by puzrin** [comment]
Could you explain step-by-step what you do, and when something goes wrong?

**Comment by bawpcwpn** [comment]
## Steps to Reproduce:

1. Open http://fontello.com in Safari browser.
2. Click 'Spanner' icon next to 'Font name' input box.
3. Click "Import" item in dropdown

###Expected Results
File browser window pops open to select a JSON .config file

###Actual Results
No file browser window opens, nor any error message.

**Comment by puzrin** [comment]
Hm. Ok. Will try to check.

You can also drag&drop file to fontello page for import.
