### ISSUE TITLE
Invalid host www.fontello.com

### ISSUE THREAD

**Issue by zilly** [fontello/fontello#485]
Hi,

It seems like the configuration for www.fontello.com is no longer working. 

> HTTP/1.1 404 Not Found
> Content-Type: text/plain
> Date: Thu, 17 Mar 2016 12:09:40 GMT
> Connection: keep-alive
> Transfer-Encoding: chunked

Invalid host www.fontello.com

fontello.com without www works like it should. I think it worked before with www. aswell. Thats what i usually type in the browser since its more common using with www. than without.

Just wanted to let you know.

**Comment by puzrin** [comment]
Thanks! Will fix that a bit later (not critical).

**Comment by DataToken** [comment]
Greetings just wanted to chime in, new to the scene... and wanted to start helping out with this great project.

For this issue, if what I am reading is correct, it sounds like a www to non-www redirect through .htaccess could correct the issue? Or would I be wrong?

**Comment by zilly** [comment]
fontello.com and www.fontello.com are pointing to the same IP but since the server responds "Invalid host: www.fontello.com"  i guess there is some site/virtual host config that needs to be done so the .htaccess would not have any effect until it points to the right directory. 
I would myself find this critical though.

**Comment by puzrin** [comment]
Fixed.
