### ISSUE TITLE
Bad request when "Download webfont" is clicked

### ISSUE THREAD

**Issue by diamondobama** [fontello/fontello#486]
After selecting variety of fonts and you click "Download webfont", a message pops up at the bottom of the button saying "Bad request". it doesn't matter how many fonts you selected.

However, "config.json" could be downloaded and reused without issues.

**Comment by puzrin** [comment]
Need that config. Attach it please (may be zipped)

**Comment by diamondobama** [comment]
[config.zip](https://github.com/fontello/fontello/files/177935/config.zip)
