### ISSUE TITLE
API returning 'Invalid config format

### ISSUE THREAD

**Issue by colophonemes** [fontello/fontello#487]
I'm the author of [metalsmith-icons](https://www.npmjs.com/package/metalsmith-icons), which I use to generate a list of the icons we're using in a project, and add some custom glyphs. The plugin builds `config.json` on the fly, then downloads the resulting file.

It's worked fine until today, when it returns an error for each glyph:

```
'Invalid config format:
data.glyphs.0 no (or more than one) schemas match
- data.glyphs.1 no (or more than one) schemas match
- data.glyphs.2 no (or more than one) schemas match
- data.glyphs.3 no (or more than one) schemas match
// etc for all 32 glyphs in the config file
```

The config file I'm submitting is here:
[config.json.zip](https://github.com/fontello/fontello/files/181595/config.json.zip)

**Comment by puzrin** [comment]
Attach zipped config please.

**Comment by colophonemes** [comment]
Sorry, the form submitted before I'd finished writing my comment. See above

**Comment by puzrin** [comment]
Should work now

**Comment by colophonemes** [comment]
Fantastic, thank you @puzrin & @Kirill89!
