### ISSUE TITLE
Cannot get font with Gulp API and fontello-cli

### ISSUE THREAD

**Issue by vayter** [fontello/fontello#488]
Hello, 

I cant get font with Gulp API and fontello-cli.

Tryed to send POST via CURL to fontello.com and got status 413.

Everything worked fine until last Friday.

**Comment by puzrin** [comment]
Too few info. We do not use gulp.

1. try again, just updated server.
2. if still does not work - provide zipped config.

**Comment by puzrin** [comment]
Close - seems not related to this project + no info.
