### ISSUE TITLE
Error download .SVG file

### ISSUE THREAD

**Issue by magnacartasoftware** [fontello/fontello#490]
I’d like to create a font icon with fontello (http://fontello.com/) but when I try to download the .SVG files gives me the following error: 
“If image looks not as expected please convert to compound path manually. 
Skipped tags and attributes: circle, rect, class”

[11.zip](https://github.com/fontello/fontello/files/225695/11.zip)

**Comment by puzrin** [comment]
Just do what it says.

https://github.com/fontello/fontello/wiki/How-to-use-custom-images#preparing-images-in-inkscape
