### ISSUE TITLE
Shaky spinner

### ISSUE THREAD

**Issue by kasbah** [fontello/fontello#491]
I have this [issue](https://github.com/monostable/kitnic/issues/22) on my site. The spinner goes shaky sometimes. Seems to happen after a while only. I can't really reliably reproduce it. I have only seen it happen in Firefox so far.

[Here is a video](http://kaspar.h1x.com/janky_kitnic.webm)

**Comment by puzrin** [comment]
That's a known bug :( . 3 years old, without good resolusion. Discussed in #100 .
