### ISSUE TITLE
Kerning Glyphs

### ISSUE THREAD

**Issue by bennyp123** [fontello/fontello#492]
Please add support for per-glyph kerning and a full-width class a la fontawesome's fa-fw

**Comment by puzrin** [comment]
That seems too abstract. Could you explain what you mean? Fontello does not intend to support all possible CSS tricks. It provides you basic CSS files and you can extend those as you wish.

For example, is uses `codes.css` file itself and extend is separately https://github.com/fontello/fontello/tree/master/client/lib/icons

**Comment by puzrin** [comment]
Close as something strange.
