### ISSUE TITLE
Serve fontello over https?

### ISSUE THREAD

**Issue by jackmcpickle** [fontello/fontello#494]
Is this something you are able to do?

SSL are virtual free now with [letsencrypt](https://letsencrypt.org/) and [cloudflare](https://www.cloudflare.com/) services.

**Comment by puzrin** [comment]
Reasons? Here are no critical user info.

**Comment by jackmcpickle** [comment]
See one post of many https://trevellyan.biz/why-your-website-should-use-https-instead-of-http/

Big reason speed with HTTP/2 which only works over HTTPS see - http://www.httpvshttps.com/

Not a biggy but good practice now.

**Comment by puzrin** [comment]
That's too abstract. I don't see any point related to fontello.

**Comment by puzrin** [comment]
Closing as "not needed"
