### ISSUE TITLE
How to use the API in C#

### ISSUE THREAD

**Issue by midiway** [fontello/fontello#496]
I think it is not a C# specific issue, but I think I don't understand how to use the api.
I am trying to POST to http://fontello.com/ my config.json JSON content, but I always get a 400 Bad Request

Here is a dotnet fiddle with my test: https://dotnetfiddle.net/ha7dVt

**Comment by puzrin** [comment]
Sorry, can't help with C#. Probably, you send params not as encoded form, but i'm not sure. The only thing i can recommend is to study existing scripts, written in other languages https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport.

Closing as not directly related to this project.

**Comment by midiway** [comment]
Seriously, it is not a C# problem, just use any 'online HTTP POST test', put your config.json text as 'config' param, and you will always get this:
```
Something went wrong - The remote end-point returned an error - HTTP Code - 400
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Server: Sansun Calakci
Vary: Accept-Encoding
Date: Thu, 26 May 2016 02:53:58 GMT
Connection: keep-alive
Transfer-Encoding: chunked

=============

is required
```
I used this tool: https://www.codepunker.com/tools/http-requests

**Comment by puzrin** [comment]
Sorry, can't help with investigating your tools. I've provided link to working scripts. Also checked `make fontopen`  & `make fontsave` in this project - works as expected. https://github.com/fontello/fontello/blob/master/Makefile#L80-L111

**Comment by midiway** [comment]
The 'config' POST param is just the content of config.json file right?
URL encoded or not?

**Comment by puzrin** [comment]
> URL encoded or not?

Not. Form-encoded. Pay attention to [--form](https://github.com/fontello/fontello/blob/master/Makefile#L91) option

https://curl.haxx.se/docs/manpage.html#-F

**Comment by rsambathkumar** [comment]
Did we find a solution for this?

I too get same error: "is required"

I'm doing a POST to http://fontello.com and with following params:

config: the content of config file

**Comment by midiway** [comment]
Got it working in C#:
```
static public string CreateSession(string json)
	{
		var obj = JSON.DeserializeObject(json);
		json = JSON.SerializeObject(obj);// reduces request size

		using(HttpClient client = new HttpClient())
		{
			var content1 = new ByteArrayContent(Encoding.UTF8.GetBytes(json));
			content1.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
			content1.Headers.Add("Content-Disposition", "form-data; name=\"config\"; filename=\"config.json\"");

			MultipartFormDataContent content2 = new MultipartFormDataContent();
			content2.Add(content1, "config");

			string q = content2.ReadAsStringAsync().Result;
			q = HttpUtility.UrlDecode(q);


			HttpResponseMessage response = client.PostAsync("http://fontello.com/", content2).Result;
			response.EnsureSuccessStatusCode();
			return response.Content.ReadAsStringAsync().Result;
		}
	}
```
you have to upload the .config file as MultipartFormData. Call this CreateSession() method passing the config JSON, and it returns the sessionID

**Comment by rsk-579** [comment]
Thanks, I made it working with WebRequest.Create. I will try this as well.
