### ISSUE TITLE
Customize Codes not working

### ISSUE THREAD

**Issue by AlanS77** [fontello/fontello#500]
Hi

When I go to your website http://fontello.com
and choose a icon, then got to custimize codes,
to get the code - it always shows U+E800,
no matter which Icon I choose.

I tryed with differen browsers form different locations,
but it dosen't work.

Please fix this.

Thanks - Alan

**Comment by samayo** [comment]
:+1:  Same here. It seems someone changed something the past week or two. It used to work fine, but now when you choose a font .. say, a heart, start, mail icon .. the code for star, will let you pick the mail, the mail some other icon .. it's messed up.

**Comment by AlanS77** [comment]
When is this going fo be fixed, I can't get the codes, and therefore can't modify my website.

**Comment by puzrin** [comment]
Seems codes are not remembered after page reload, but if you download after edit, files are or. And if you import config, codes are updated properly.

**Comment by AlanS77** [comment]
Hi

When I download the fonts, there are many files.
Can you please tell me, where I can find the code for the specific font.

Even better would be, if you could provide me a PDF with all codes,
from exactly this website:  http://fontello.com

Or offer me a alternative option, to get the codes.

Thanks - Alan

**Comment by puzrin** [comment]
You can open html file for human, or `config.json` for scripting.

**Comment by puzrin** [comment]
Fixed lost codes after page reload.

**Comment by ngairet** [comment]
When I click Customise Codes, the special character assigned for the icon doesn't show characters anymore, it just shows either rectangular outlines or Mandarin characters. How do I change this so it uses English characters?
