### ISSUE TITLE
Resize not maintaining center

### ISSUE THREAD

**Issue by manatarms** [fontello/fontello#503]
Not sure if this is an issue but I didn't know where to ask this question. The custom font icon I created seems much smaller than all the other icons that I used from the font awesome pack. 

The icon at 14px looks much smaller than other default icons at 14px. If I try to upload a larger icon size (More than 500px svg) to Fontello it does not center the icon.![screen shot 2016-06-26 at 10 23 38](https://cloud.githubusercontent.com/assets/4206893/16362886/2a42f5ce-3b88-11e6-91a4-a3ba88843518.png)

I've attached images for your reference. Is there any way to get a larger icon as the default size. Worked hard on the icons, would hate for them to go to waste. Thanks for your time and thanks for Fontello.

**Comment by puzrin** [comment]
1. Make sure your icon takes proper place on working sheet in editor. You may need to adjust it or change scale
2. In html glyphs can be alligned with line-height property.

Generic recommendations about custom images are here https://github.com/fontello/fontello/wiki/How-to-use-custom-images

**Comment by manatarms** [comment]
Thanks for the response. I will check it out.

**Comment by puzrin** [comment]
Just keep in mind, that fontello does not guess icon size. It takes full document size to make glyph.

**Comment by leopiccionia** [comment]
Just for future reference: I had a similar problem and what was causing it was SVG scale set to different than 1:1.

In my particular case, it was set by editor to 0.264583333 (the ratio between 1px and 1mm). I fixed the viewBox size and it worked like a charm.

**Comment by decujo** [comment]
Hi, I seem to be having the exact problem.  Uploaded svg files are always smaller and in the upper left quadrant, instead of being centered.  Increasing the px on the sliding bar at the top of the fontello page does not help with the centering.   Can you please explain the solution above, in terms a newbie can understand?  Thanks!
