### ISSUE TITLE
Icons in demo.html render differently from icons in editor

### ISSUE THREAD

**Issue by mindplay-dk** [fontello/fontello#505]
I'm having problems with icon/font rendering. (in Chrome, on Windows.)

In the editor, they render like this:

![image](https://cloud.githubusercontent.com/assets/103348/16451353/c8d1ef8e-3e02-11e6-839b-1da29b3733da.png)

Under microscope:

![image](https://cloud.githubusercontent.com/assets/103348/16451366/e69f187a-3e02-11e6-936c-e34d905e3d60.png)

In the downloaded `demo.html`, they render like this:

![image](https://cloud.githubusercontent.com/assets/103348/16451463/8b79870e-3e03-11e6-9d54-207e13e3921c.png)

Under microscope:

![image](https://cloud.githubusercontent.com/assets/103348/16451482/abc2de98-3e03-11e6-9869-f03742a9ecff.png)

There's an extra pixel of space between the bottom shapes.

`font-size` is set to `16px` in both cases.

I have tried turning off every single CSS property, all except `font-size` - I have compared every single CSS property (with the "Computed" tab in the Chrome CSS inspector) and there is literally no difference, whatsoever.

Having spent hours doing this, having had five different coworkers look into it, nobody can spot any difference in the CSS, document type, `meta` tags, headers, nothing.

The only thing any of us were able to conclude, is that the file(s) we get when we download the icons is somehow different from the icons displayed in the editor? Like maybe the Y coordinates of the paths are affected somehow? The vertical aliasing is clearly different in the rendering on the editor page and demo page that comes wtih the download... somehow??

Any clues?

**Comment by mindplay-dk** [comment]
By the way, I also tried it the other way around - adjusting the CSS in the editor, to see if there was any way I could provoke the ugly rendering in the editor. There isn't. I'm losing my mind :-D ~

**Comment by mindplay-dk** [comment]
Nobody else bothered by this?

**Comment by puzrin** [comment]
https://github.com/blog/1135-the-making-of-octicons

You need fit your image to grid to show it sharp in desired size. That's not related to fontello.

**Comment by puzrin** [comment]
Short recipe is:

1. Select font size to show image (16 px for example)
2. Draw grid 16x16
3. Make sure long lines match that grid.

Then in 16px image will be sharp.

**Comment by mindplay-dk** [comment]
That was just an example though - this happens to be one of my icons, but I have the same exact issue with stock icons I selected from the FontAwesome set.

**Comment by mindplay-dk** [comment]
Either way, none of that really explains why the rendering is totally different in the editor and on the demo page that comes with the download? If my icon doesn't render well at 16px, it shouldn't render any better or worse in the editor compared with the demo page, should it? (why?)

**Comment by puzrin** [comment]
In short - display precision is not infinite. If glyph does not match to display pixels, then different things happen.

AFAIK, FontAwesome is done to be sharp at 14px. If you show it at 16px, lines can be slightly shifted, depending on screen DPI, OS and other things. You can check what happens with FA by change font size in fontello.

Also you can play with `hinting` settings. It tries to make icons more sharp by moving lines a bit.
