### ISSUE TITLE
Enable Multiple select with 'Shift' and 'Command' keys

### ISSUE THREAD

**Issue by eightyfive** [fontello/fontello#506]
It would be great if the `multipleselect` was working when holding 'Shift' and/or 'Cmd' keys. Exactly like on a computer OS.

**Comment by drawcard** [comment]
Would love to see this feature implemented

**Comment by AlexWayfer** [comment]
> @eightyfive closed this 6 days ago

Why? Is it resolved?

**Comment by eightyfive** [comment]
No, just cleaning my issues. Opened almost 3 years ago.
