### ISSUE TITLE
Impossible to drag down the screen, when 'dragging-selecting' icons

### ISSUE THREAD

**Issue by eightyfive** [fontello/fontello#508]
When drag-selecting icons, it is impossible to scroll down the screen as you select the icons. So you cannot select more icons than there is on the screen estate (the screen doesn't scroll down as you reach its bottom, dragging).

**Comment by puzrin** [comment]
I think, that works as expected. If mouse have wheel, scrolling is ok.

May be that could be improved, but i don't see big reasons. Of cause, of someone suggest PR, that will be accepted.

**Comment by puzrin** [comment]
We replaced selector with `xselectable` to drop `jquery-ui` dependency. As a side effect - seems that page scrilling was improved.
