### ISSUE TITLE
Drag-selecting a lot of icons, takes ages to actually select them

### ISSUE THREAD

**Issue by eightyfive** [fontello/fontello#509]
The drag-multiselect is very slow for me.

When I drag-select multiple icons I have to wait a loooong time before the webapp actually selects the relevant icons on page.

It also prevents me from using the webapp meanwhile (it freezes). I'm using Chrome (latest).

**Comment by puzrin** [comment]
That's a known problem, and it can't be fixed for now. New design allows to hide unused fonts in "library", that should help. But there are no any deadlines, i'm busy with main project.
