### ISSUE TITLE
Disable font caching on demand

### ISSUE THREAD

**Issue by antusus** [fontello/fontello#514]
Hello,

we are using fontello in our project and we are having some issues with added solution to prevent font caching (issue https://github.com/fontello/fontello/issues/127). We are using HTML5 application cache because we want to manage what should be refreshed when. In order to make fontello fonts work with this we have to either remove the generated timestamp or add it to cache manifest. Could it be possible to add a flag and specify during font generation if I want to add this timestamp or not?

**Comment by puzrin** [comment]
I'm very conservative about adding new options. But you can solve your problem without those. Just use `icons-codes.css` and create your own fontface description. It's specially done for such cases.
