### ISSUE TITLE
Svg Flatten module as separate package 

### ISSUE THREAD

**Issue by atomiomi** [fontello/fontello#515]
I wrote [npm package](https://www.npmjs.com/package/fontellizr) that automatically generates fontello webfont from svg set which is used `_svg_image_flatten.js` file from your repo. It would be great if u will move it to separate module so it would be possible to use it as a normal dependency _(currently i just copied it to my repo)_.

Moreover u make some other [manipulation with svg in your code](https://github.com/fontello/fontello/blob/2c586eda1bf3c7f5f84323d74a937f82cd2acd4c/client/fontello/app/import/import.js#L196-L201). The best thing would be if u will write package that will generate [this object] (https://github.com/fontello/fontello/blob/2c586eda1bf3c7f5f84323d74a937f82cd2acd4c/client/fontello/app/import/import.js#L208-L211) by passing to it svg file

**Comment by puzrin** [comment]
Sorry, i don't like this idea. That code is dirty, and can produce buggy result. That does not seems good enougth for separate module. Everything like `svgpath` & fontn convertors is already moved to packages.

Of cause, you can copy code an use it as you wish.
