### ISSUE TITLE
MIME types

### ISSUE THREAD

**Issue by rafis** [fontello/fontello#524]
https://github.com/fontello/fontello/wiki/How-to-setup-server-to-serve-fonts

`application/font-sfnt` is too generic. I think these are more exact:

    application/x-font-ttf                ttc ttf;
    font/opentype                         otf;

**Comment by puzrin** [comment]
You are right, it worth to update  info.

See https://github.com/fontello/fontello/wiki/How-to-setup-server-to-serve-fonts/_compare/66a313342038ca43dc8a9b2a28db704b0c5dd5d1

The only difference - i've taken otf info from https://github.com/jshttp/mime-db/blob/master/src/apache-types.json#L2243
