### ISSUE TITLE
fontello.com produces woff2 filled with zeros

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [fontello/fontello#537]
to reproduce:
1) navigate http://fontello.com/
2) click `tools -> reset all changes`
3) select an icon, say `emo-happy`
4) click  `download webfont`
5) unpack `fontello-*.zip`
6) locate `font/fontello.woff2`, 6096 bytes
7) file contents in hex editor shows as filled with zeros

attempt to load in chrome produces errors:
```
Failed to decode downloaded font: http://.../fontello.woff2
OTS parsing error: invalid version tag
```

**Comment by puzrin** [comment]
Ups... something was wrong with node_modules. Reinstalled dependencies, now works.

Thanks for report!

**Comment by Andrei-Pozolotin** [comment]
woks, thank you
