### ISSUE TITLE
No icons (or some icons) on specific browsers and mobile phones

### ISSUE THREAD

**Issue by TanjaTV** [fontello/fontello#541]
Hi,

Its awesome that we can make custom icons and use this in our site. But there are some icons not showing the image on some devices. The website is based on Wordpress with the theme Enfold. On the example page is the second and last icon missing, only the circle is showing. 

Here is more info about the devices:
device name: sony VAIO, 
operating system and version: Windows 10 Home
browser name and version: Google Chrome version  53.0.2785.116 m
link to example page: http://www.burobannink.nl/adam-en-anderen/

Device name: Iphone 6e & 5s
browser: Safari
link to example page: http://www.burobannink.nl/adam-en-anderen/

device name: Samsung Galaxy Note 3
browser: Internet, version 4.0.10-53
browser: Chrome, version 53.0.2785.124

the config of the font: https://gist.github.com/TanjaTV/ecc8eb7a2e8d1f67e20c178c44862c8c 

How can i fix this?
Regards,
Tanja

**Comment by TanjaTV** [comment]
Hello, Does anyone know how to fix this issue?

**Comment by puzrin** [comment]
Did you read https://github.com/fontello/fontello/wiki/How-to-use-custom-images ? I imported your config and it has a lot of black circles in Firefox under Ubuntu 14.04 LTS. Seems original images were not properly converted to compound paths (have contours with improper direction).
