### ISSUE TITLE
Some of fonts are filled on mobile browsers

### ISSUE THREAD

**Issue by lukaszflorczak** [fontello/fontello#543]
Some of fonts/icons are filled on mobile browser (I test it on Chrome and Safari for iOS). On desktop browser everything works fine. I use Fontello a long time, but I never before had problem like this. 

**Examples/Screenshots:**
Desktop browsers:
<img width="160" alt="zrzut ekranu 2016-10-13 o 10 07 21" src="https://cloud.githubusercontent.com/assets/1818979/19341935/0990455e-9130-11e6-849f-b02ce6eaed21.png">

Mobile browsers:
![img_0600](https://cloud.githubusercontent.com/assets/1818979/19341943/1185a6aa-9130-11e6-81b4-924bc0025e62.jpg)

On Fontello:
<img width="539" alt="zrzut ekranu 2016-10-13 o 10 29 27" src="https://cloud.githubusercontent.com/assets/1818979/19341960/1ad39096-9130-11e6-85a3-03357281b77f.png">

**Comment by puzrin** [comment]
Fill of each contour is defined by it's direction. You should recheck and fix contours orientation in source image. Some font renderers can autofix those, other not.
