### ISSUE TITLE
can not change baseline in ttf

### ISSUE THREAD

**Issue by niklasf** [fontello/fontello#546]
I am trying to escape fontastic.me by importing this SVG font to fontello: https://github.com/ornicar/lila/raw/master/public/font70/fonts/lichess.svg

It seems that the em size is 512 units, 480 ascent, -32 descent.

However when I export the font and view the ttf on the web (e.g. http://webfont-test.com/), the baseline seems to be different. In fact any baseline I set in the webinterface seems to be completely ignored.

When I export a ttf from the same SVG using fontforge the baseline is correct.

Hints are much appreciated. Anything else I could try or extra info I can provide?

**Comment by puzrin** [comment]
Input font metrics are used only to extract svg images.

Go to `menu -> advanced font settings` and setup the same params for output font.

Let me know if problem still exists.

**Comment by niklasf** [comment]
Yes, that's exactly what I tried. It seems any values  I set in that dialog habe no effect on the generated TTF. (I even tried setting crazy values.)

**Comment by puzrin** [comment]
That's easy to check:

- reset everything
- select some fontello icons
- change accent/descend % via advanced menu
- download font
- open in FontForge and check result.

PS. But everything should be ok.
