### ISSUE TITLE
POST API not working - Repening

### ISSUE THREAD

**Issue by rsambathkumar** [fontello/fontello#548]
POST API with content of my config gives back the response as "is required".

What is required here? I tried all different options for almost a day now.

This is just when using a simple POST. I just want to understand what are the parameters needed for POST. What will be value for config? Is it content of the config file.

Your sample was of no help.

Thanks

**Comment by puzrin** [comment]
1. [Makefile](https://github.com/fontello/fontello/blob/6.0.0/Makefile#L61-L92) works as needed via curl
2. Refs to examples for some languages exists in wiki.

Please investigate working code instead of creating issues with wrong titles.

**Comment by colophonemes** [comment]
Can we reopen this issue? I'm having the same problem as @rsk-579 

Sending a `POST` request to `http://fontello.com` using the following config JSON returns a `400 Bad Request` error, and the response body is simply `is required`:

```js
// POST request body to http://fontello.com using 
// using Content-Type: application/json
{
  "name": "",
  "css_prefix_text": "icon-",
  "css_use_suffix": false,
  "hinting": true,
  "units_per_em": 1000,
  "ascent": 850,
  "glyphs": [
    {
      "uid": "3a900d0e9f43f5409211f62bec557379",
      "css": "emo-beer",
      "code": 59403,
      "src": "fontelico"
    },
    {
      "uid": "4dd56d61fd0dab19277824da301424b3",
      "css": "emo-devil",
      "code": 59397,
      "src": "fontelico"
    }
  ]
}
```

This `config` was downloaded from the Fontello web interface, so I presume it's in the right format (and if I try dragging/dropping the config.json file onto the web interface, it loads fine). I've checked it against this [schema](https://github.com/fontello/fontello/blob/a59530d22caf13eadbe308c1d27dcefb54e8d83b/server/fontello/font/_lib/config_schema.js) and it looks OK.

I've also tried with [fontello-cli](https://github.com/paulyoung/fontello-cli), which (when using the same `config.json`) returns the following error:
```
Error: connect EHOSTDOWN 5.9.24.88:80 - Local (0.0.0.0:0)
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at connect (net.js:884:16)
    at net.js:1013:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```

**Comment by puzrin** [comment]
@colophonemes try `curl` requests first https://github.com/fontello/fontello/blob/6.0.0/Makefile#L61-L92. I don't know why `fontello-cli` doesn't work (it's 3rd-party project), but usually problem happens because people try to post params in NOT form-encoded format.

If problem still exists with `curl` too - create a new issue with details, i will check.

**Comment by rsk-579** [comment]
How are you doing you POST? I use C# HttpClient and figured out a way to do this.

It is mainly to do with how you setup headers. Content-Disposition should be set to form-data

**Comment by colophonemes** [comment]
The issue seems to have resolved itself. No changes to my code, but I've stopped getting the error. Thanks anyway.
