### ISSUE TITLE
working svg example for fontello.com?

### ISSUE THREAD

**Issue by juek** [fontello/fontello#550]
I just tired to upload lots of different variants of the same quite simple SVG shape , generated with 4 different applications (including Inkscape). All consist of the required single 'compound' path. I tested no fill, black fill (r0g0b0), almost everything I could imagine. All files render correctly in every browser and open in all applications. 

But fontello.com tells me either 'If image looks not as expected please convert to compound path manually.' or it only renders only a placeholder box. 

Cound anyone please provide me with a working svg file, so I can transform mines to the subset, fontello understands. Thank you.

**Comment by puzrin** [comment]
https://github.com/fontello see any font repo there, `src/svg` folder.

Also this should help https://github.com/fontello/fontello/wiki/How-to-use-custom-images. Remove all fills and make sure contours have proper directions.

**Comment by juek** [comment]
Thank you. That helped. 

It seems that we have to ...

1. keep SVG 1.0 standard from scratch (couldn't find out how to tell inkscape so save 1.0 if the original source was 1.1)
2. be cautious with too high geometric precision (e.g. 1:100 @ 2048px base grid)
3. force applications to generate a path attribute even if a polygon (without any curves) would be sufficient to descripe the shape

**Comment by puzrin** [comment]
The only thing that really does matter - convert image to compound path. Everything else is not significant.

If you provide image with single compound path, fontello will do the rest well.

**Comment by juek** [comment]
> convert image to compound path

It will fail on a polygon. When converted to a path (e.g. using any of inkscapes path functions), it will work. 
While this will do the job for me, I only wonder if describing even straight lines as beziers is overkill and needless computation for any font renderer.

**Comment by juek** [comment]
> ... if describing even straight lines as beziers ...

Ok, this seems only to be the case in Inkscape, which treats even straight path segments as (potential) curves. Other applications don't so I assume fontell doesn't as well.

Thanks again for your help. Fontello is a great thing.

**Comment by puzrin** [comment]
I think if you don't create huge number of segments, you will not see difference between beziers & lines in modern renderers.

Some editors can have optimizers to simplify contours, but i'm not familiar with details. In general - if you draw manually - don't waste your time for optimizations :)
