### ISSUE TITLE
FontAwesome update to 4.7

### ISSUE THREAD

**Issue by Wruczek** [fontello/fontello#553]
FontAwesome 4.7 was released over a month ago, it would be nice if you can update it on Fontello

**Comment by sstragier** [comment]
+1

**Comment by sebastienbarre** [comment]
I just created the corresponding PR, fontello/awesome-uni.font#9

**Comment by puzrin** [comment]
Thanks @sebastienbarre ! I'll arrange update this weekend

**Comment by puzrin** [comment]
updated
