### ISSUE TITLE
Placeholder present when I use spaces before or after icon

### ISSUE THREAD

**Issue by carc1n0gen** [fontello/fontello#558]
Whenever I put spaces before or after a font I get weird placeholder looking characters instead of spaces.  I don't get them when I use the original font files, only when using a custom fontello font file.

![img_20161116_111345](https://cloud.githubusercontent.com/assets/8248986/20355026/f2a2ac14-abed-11e6-94d3-b6d5d9827f06.jpg)

**Comment by puzrin** [comment]
If you need a space, you could add blank character with required width and code 0x20. Is it ok?

**Comment by carc1n0gen** [comment]
@puzrin My use case probably doesn't meet with what fontello aims for.  I'm using the icons in the output of a shell script.  I wanted to use fontello because when I tried to use fontawesome fonts with weather icon fonts, they would override each others icons.  So I tried to use fontello to pick the individual icons I needed, and not have them override each other.

**Comment by puzrin** [comment]
You see garbage because generated font doesn't have 0x20 character. But you can add it as custom icon. Just create blank squarish SVG document, drop it to custom icons collection and set code to 0x20.

Does it solve your problem?

**Comment by carc1n0gen** [comment]
Ahh, that would be the problem.  Thank you for you help.  I do not have the tools to try that out sadly, and I need to use the ttf fonts anyway.

**Comment by puzrin** [comment]
https://github.com/fontello take any svg from any font source and delete path manually in text editor.

**Comment by carc1n0gen** [comment]
I'm sorry, but I just don't understand.  I don't know anything about fonts or svg.  Are you saying there is a way to add a space to the custom font collection I generated from the fontello website?

**Comment by carc1n0gen** [comment]
So I think I'm close.  For some reason, whenever I create a rectangle in inkscape, even if I set fill and stroke to none I get fill space when I import it in fontforge

**Comment by carc1n0gen** [comment]
Another issue is that the space is too wide even though y rectangle was not wide at all

**Comment by puzrin** [comment]
```
<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000"></svg>
```

Try one above and change `width` as you need. Save content as `space.svg`, then import to fontello.

**Comment by carc1n0gen** [comment]
Aha! I was able to do away with inkscape and just leave the space empty in font forge, and I Dragged the box more narrow to make the space more narrow.

Thanks for all the help!
