### ISSUE TITLE
config.json contains all fonts instead of selective

### ISSUE THREAD

**Issue by scazzy** [fontello/fontello#563]
Downloading the fonts, it exports all codes in config.json instead of just the selective icons

**Comment by puzrin** [comment]
That's normal. It stores all custom glyphs, because it should restore state on load.

**Comment by scazzy** [comment]
@puzrin why all glyphs required when the config is meant to know your config(glyphs you've selected or are using)? Purpose of fontello is to use glyphs that you want, so ideally the config file, like the font files, should contain glyphs and details only for the selected glyphs

**Comment by puzrin** [comment]
Because config solves the real problems, not imaginated. I provided you the real example - config should restore all custom glyphs, even if those were not selected.
