### ISSUE TITLE
Missing icons from fontawesome

### ISSUE THREAD

**Issue by stefanheule** [fontello/fontello#565]
It seems that the [fa-cutlery](http://fontawesome.io/icon/cutlery/) icon is missing from the fontawesome project.  It looks like fa-cutlery was part of fontawesome since 3.0, and fontello supports version 4.7 of fontawesome, so I'm not sure why it is missing.

Any plans to add this?

**Comment by puzrin** [comment]
http://fontello.com/#search=food
