### ISSUE TITLE
Demo Alphabetical Order

### ISSUE THREAD

**Issue by troytempleman** [fontello/fontello#567]
Is there currently a way to list the icons in alphabetical order in the demo? If not, this would be great feature to have in the future. It's not a big deal if you only have a small number of icons but when you have a large number of icons, it may be difficult for the user to find the type of icon they are looking for. For example, if they are looking for a facebook icon, instead of manually looking through a potentially large list, they would just scroll to the icons beginning with "f" to find it. 

If this is not possible, maybe a search tool could work?

Kudos on a great tool!

**Comment by JohnEcks** [comment]
there's a search box right on the top left of the website. :) Unless you mean in the icon set you have made.

I do agree though, if we could have an alphabetical option that would be cool, although most icons have multiple tags, I guess the first could be used.

**Comment by troytempleman** [comment]
Yes, I meant on the icon set. I ended up adding a simple search script found at http://www.javascripter.net/faq/searchin.htm. Works like a charm!

**Comment by dropddesigns** [comment]
I originally imported our SVG in alphabetical order but I've found that any new icons that I import are added to the end of the list in both the CSS and the demo.

I haven't dug into any code but my assumption is that the ordering is based on the unicode character sets?

I would love the option to generate the CSS classes and the demo listing in alphabetical order.

**Comment by bigvax** [comment]
I made the macro for the Far Manager Editoe (LUA), which stylizes the fontello demo-file and also sorts the icons alphabetically. If anyone is interested, I can share it.

**Comment by puzrin** [comment]
Standard answer for all such request is: "use fontello API, and then build any customizations from `config.json` as you wish".

Some examples https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport.

Fontello itself use this method too for icons update.
