### ISSUE TITLE
fontello.com not working in IE11

### ISSUE THREAD

**Issue by sadm2014** [fontello/fontello#568]
I worked under bug issue on my site using fontello and found that fontello.com not working in IE11 sometimes. Reproduced on win7
![win7](https://cloud.githubusercontent.com/assets/11456369/20878672/512c6a70-bae1-11e6-8cfb-a923bbb28365.jpg)
and win12 (server)
![win12](https://cloud.githubusercontent.com/assets/11456369/20878694/5fe37752-bae1-11e6-88fc-8f04429fd7eb.png)

IE last updated, no plugins

**Comment by puzrin** [comment]
Looks like custom fonts disable in settings. I don't have IE now to check. But, honestly, nobody cares much about it if generated fonts are ok in IE.

**Comment by puzrin** [comment]
close - timed out / nobody cares
