### ISSUE TITLE
Add config option for fonts directory

### ISSUE THREAD

**Issue by azizur** [fontello/fontello#573]
First of all this really an awesome tool, that I have been searching for a long time. I love the node CLI tool it's perfect how you guys have thought of everything to make life easier for many lazy developers like me.

In order to support even more lazy developers like me, I would like to request a config option to specify the font files directory.

For example currently:
```
@font-face {
  font-family: 'icons';
  src: url('../font/icons.eot?87713699');
  src: url('../font/icons.eot?87713699#iefix') format('embedded-opentype'),
       url('../font/icons.woff?87713699') format('woff'),
       url('../font/icons.ttf?87713699') format('truetype'),
       url('../font/icons.svg?87713699#icons') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

I would like the ability to specify the `../font` from a config or CLI option. That way when I download I am able to set a prefix to start with. If one is not provided it would just add `../font` to keep it backward compatible.

**Comment by puzrin** [comment]
There are no plans to extend api with things, that can be done on other side. Archive contains `config.json` file, used to generate any CSS you wish.

**Comment by azizur** [comment]
@puzrin I understand about not changing the API. What I am asking is reasonable. The current setup means you are forcing developers to store their fonts in the specific location. This file if someone is starting a new project I would like to use `fontello` in a way that works with the existing project structure. Without this option to change the base path you are dictating where developers should store their font files. I am sure you'd agree that most high-performing sites are serving assets such as fonts from subdomains. Adding this option would mean one can have those fonts files served from different domains with even longer TTL then my CSS files.

**Comment by azizur** [comment]
@puzrin I would like to understand what you mean by `... that can be done on other side ...`?

**Comment by puzrin** [comment]
Fontello's API has no goal to do anything people can imagine. It's goal is to provide full data for post-processing (if someone is not satisfied with defaults). You can write simple script to unpack downloaded file, move fonts to another place and create css/stylus/sass file from `config.json`. I think that's not very difficult for github users.

**Comment by domruf** [comment]
@puzrin Sorry for my late comment, but I don't understand what you mean by ' create css/stylus/sass file from config.json. Do you mean I should generate my own css file instead of using the one in the download?

Currently I replace the ../font/ path in the css file with my own path with a script. But that doesn't feel very stable.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport it's possible to automate load/save operations, and you can create custom script to add files you need.

**Comment by domruf** [comment]
@puzrin Sorry but you did not really answer my question.

My problem is not extracting and moving the files around. My problem is editing that relative paths inside of the css file.

Lets say I use fontello-cli with `--font ./myfontsdir --css  ./mycss`, then the url() directives in the css file still point to `../font/`, even tough the files are now in `./myfontsdir`.
