### ISSUE TITLE
Font on IOS Shows Paths Filled Demo does not.

### ISSUE THREAD

**Issue by onlinegeek101** [fontello/fontello#576]
I have an SVG icon that has 3 circle paths that aren't filled. I created a new font set in fontello and downloaded the web font. The demo.html appears correct and so does the fonts in fontello's UI but when I push them to device and reference them using the provided createIconSetFromFontello() I am seeing the circle paths are being filled w/ black.

Any ideas?

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-use-custom-images#importing-svg-images

Fill is defined by contour direction. You should set it properly (that's done when you create compound path). I can't comment anything about your device.

**Comment by onlinegeek101** [comment]
Do you know if the demo file would appear correct even if these were wrong?

**Comment by puzrin** [comment]
That depends. If you see red warning on SVG image import - you should rework it as recommended in wiki.

**Comment by onlinegeek101** [comment]
Ahh def the issue I used something to simplify my exported SVG and the fill rule evenodd is what causes the inner circle to be not filled which is ignored by the font ttf. Do you have any links/examples to how to do this correctly?

**Comment by puzrin** [comment]
See wiki link above, it contains detailed instructions.

https://github.com/fontello/awesome-uni.font/tree/master/src/svg any font repo from this org contains correct files.
