### ISSUE TITLE
differences in look between fontawesome and fontello (e.g. handle of trash is squashed).

### ISSUE THREAD

**Issue by insidewhy** [fontello/fontello#579]
I switched from fontawesome 4.7.0 to using the same icons exported by fontello from fontawesome 4.7.0.

Here is the pure fontawesome version followed by the fontello version for comparison:

![fontawesome](https://cloud.githubusercontent.com/assets/97685/22308268/2fe97224-e33e-11e6-8f31-97f9870e2c43.png)
![fontello](https://cloud.githubusercontent.com/assets/97685/22308279/4057028e-e33e-11e6-8e08-4c57ca2a29ca.png)

You can see that the handle of the trash can has been squashed (but the rest of the trash bin is identical). The entire floppy disk has been vertically squashed. The globe and the "x" also seem to have gotten shifted up and to the right a bit. The only icon that looks the same in both is the chevron.

**Comment by ohjames** [comment]
When I turned off hinting they match, sorry for the noise.

**Comment by ohjames** [comment]
Sorry I was wrong, turning off hinting stops the disk getting squashed and the shifting of the x, but the handle of the bin is still squashed and the globe is shifted up and to the right a bit.

**Comment by puzrin** [comment]
Go to advanced settings and play with font accent/decent. Fontello defaults can be different.

**Comment by ohjames** [comment]
@puzrin I played with them a bunch, I set them to what I believe font-awesome uses. Could that explain the handle of the bin getting squashed without the rest of the bin being affected?

**Comment by puzrin** [comment]
Yes. Process of rendering high resolution images to low resolution screen is not trivial. Sometime renderer can change details to improve contrast. And it's difficult to predict where it happens (can vary in OS-es and browsers). The only thing you can do - try to reproduce similar initial conditions as in original - metrics, hinting.

**Comment by puzrin** [comment]
Is this still a problem?

**Comment by insidewhy** [comment]
@puzrin Sorry I'm not sure, I stopped using fontello slightly after hitting this problem.
