### ISSUE TITLE
Import custom icon font and select all icons - Chrome and Firefox hangs

### ISSUE THREAD

**Issue by tlygnersjo** [fontello/fontello#583]
Hi,

I'm trying to import a custom icon font (in this case its Linear Icons Premium, https://linearicons.com/) with 1001 icons. Importing works and i can see the icons but when trying to select them in either Firefox och Chrome the browser hangs.

What can i do in order to work with this icon font?

**Comment by tlygnersjo** [comment]
The same thing also happens when i select a couple of icons from the set ( e.g. 10 or 30 icons)

**Comment by puzrin** [comment]
Hm... if i import big SVG font (to create 2000 custom icons), selection is really slow, even if i select one-by-one.
