### ISSUE TITLE
Fontello not working in FF and IE

### ISSUE THREAD

**Issue by pineladsn** [fontello/fontello#584]
Hey guys,

I have this piece of code: 

input {
                -webkit-appearance: none;
                 -moz-appearance:none;
                margin: 0;

                &::before {
                    content: '\f1db';
                    font-family: 'fontello';
                    color: map-get($foundation-palette, midgrey);
                }
}

and it's works perfectly in chrome but in IE and FF doesn't...
That's something that i missed ? Or is a fontello issue?

Thanks

**Comment by puzrin** [comment]
Each downloaded file has demo inside. If it works in browser, then that's not foltello issue.

**Comment by pineladsn** [comment]
Could you told me where is this demos ? I didnt find it

**Comment by puzrin** [comment]
Unzip archive, and open `demo.html` file in it.

**Comment by pineladsn** [comment]
Thanks purzin,

downloaded demo file and works well in FF and IE.. that's something from darkness in my code..
I'll check it out
Thanks for the help :D
