### ISSUE TITLE
Two or more fontello fonts with different font-family names

### ISSUE THREAD

**Issue by burdyga** [fontello/fontello#585]
Hello..
If I use more than one fonts with different font-family names on my page – I get a bug. I see icons from first loaded css, for example:

font1.css:
```
@font-face {
  font-family: 'CUSTOME_NAME';
  src: url('../fonts/FONT1.woff2?23577030') format('woff2'),
....
}
```
and font2.css:
```
@font-face {
  font-family: 'CUSTOME_NAME_2';
  src: url('../fonts/FONT2.woff2?23577030') format('woff2'),
....
}
```

If I use same name – all fine. But I need use different names. 
Help me please with link to fix, because I didn't find answer. Thank you.

**Comment by puzrin** [comment]
You should update rule like [this](https://github.com/fontello/fontello/blob/99e5c61b2178446b7cdc30e9789b6b5e095b8a73/client/lib/icons/src/css/icons.css#L22). For example, move it to separate class, and define icon via 2 classes.
