### ISSUE TITLE
Add pulse to animate.css

### ISSUE THREAD

**Issue by SamStonehouse** [fontello/fontello#591]
Font awesome has a nice pulse css animation which goes well with some of their icons

Adding a pulse animation class would be helpful

```
.animate-pulse {
  -moz-animation: spin 1s infinite steps(8);
  -o-animation: spin 1s infinite steps(8);
  -webkit-animation: spin 1s infinite steps(8);
  animation: spin 1s infinite steps(8);
  display: inline-block;
}
```

**Comment by puzrin** [comment]
No plans to do a "CSS framework" here. IMHO it's very easy to extend existing style, and it's better to stay forused on font generation.
