### ISSUE TITLE
Some of the fontello fonts are not appearing in Firefox on Mac and iOS

### ISSUE THREAD

**Issue by komalwt** [fontello/fontello#594]
All the fontello fonts are appearing fine in Windows in Chrome and Firefox, 
and in Chrome and Safari in Mac and iOS

But in Firefox on Mac and iOS, for some weird reason, some of them are not appearing. 
Can be checked at  [beta13.websitetoolbox.com](beta13.websitetoolbox.com)

Note: I have used custom icon (saved from svg) in the fonts but all the custom icons are appearing fine in all browsers. Its the other icons that are missing. 

Not sure what's wrong. Any help with this issue will be good. 
![missing-icon-browse](https://cloud.githubusercontent.com/assets/20275184/24607101/d5fb14d6-188d-11e7-8436-e3be704b5be7.png)
![missing-icon-shield](https://cloud.githubusercontent.com/assets/20275184/24607099/d5fa15f4-188d-11e7-9580-3d69d6066c59.png)
![missing-icon-left-arrow](https://cloud.githubusercontent.com/assets/20275184/24607100/d5fa7742-188d-11e7-957a-558f8744a9c9.png)

**Comment by puzrin** [comment]
- are those broken glyphs from existing collections or custom one?
- are those codes > 0xFFFF? Try modify to 0x21-0x7F to check if that change anything

**Comment by komalwt** [comment]
Thanks. 
The missing icons are the part of existing collection. 
Please forgive me for my limited understanding of the terms you've mentioned in second line. Little more explaination will be helpful. 

Also I have noticed a pattern in icon font's css. That the icon code starting from "\6" are only missing. Please check attached screenshot. 

![series-6-missing](https://cloud.githubusercontent.com/assets/20275184/24608610/e4327f2e-1894-11e7-967a-3e1c52894f5f.png)
![strange-pattern](https://cloud.githubusercontent.com/assets/20275184/24608609/e4311e36-1894-11e7-8cb2-038cd55dfee0.png)

**Comment by puzrin** [comment]
Well, if you do not need fallback to system fonts, i'd suggest first to use more standard glyph codes (see "Customize codes" tab) from [PUA](https://en.wikipedia.org/wiki/Private_Use_Areas) range.

In simple words:

1. Settings -> Encoding, select "Private Use Area" (that's to set proper codes when you add more images next time)
2. Edit current glyph codes to start from 0xE800 (as fontello does by default)

Then let me know if problem still exists.

**Comment by komalwt** [comment]
Thanks a lot. Will try to fix it this way.

**Comment by komalwt** [comment]
We were able to fix the problem with the suggested solution :)

Thanks for the help,
Komal
