### ISSUE TITLE
Font awesome css class names do not match current font awesome

### ISSUE THREAD

**Issue by sschueller** [fontello/fontello#597]
It appears that some classes are named differently. For example `fa-map-marker` and `fa-google-plus-official` are missing.

They are not correct in https://github.com/fontello/awesome-uni.font/blob/master/config.yml although the file states version 4.7 of font awesome.

Would you accept a pull request that fixes this?

**Comment by puzrin** [comment]
I already explained somewhere, that existing diviations have historic reasons, because it collaborates different collections, not FA only.

On practice that means, that i prefer to avoid names change but would accept PR with more search aliases. Or we can discuss some kind of specific importer for FA, if you have well known use case for it.

**Comment by sschueller** [comment]
I see the need for backwards compatibility. 

The issue I run into is with 3rd party js libraries that use font-awesome. Many have hardcoded fa tags in them.

**Comment by puzrin** [comment]
IMHO that can be automated via script somehow. Need to understand what is the data source - how you get list of icons for custom font.

**Comment by sschueller** [comment]
ok thanks. I think I can get what I need with a custom config.json.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello#developers-api this may help, examples are included.

Closing?

**Comment by holgerd77** [comment]
I also find it a bit unlucky that naming is different, spent 2-3 hours just renaming things yesterday/today when switching from Font Awesome (not complaining - great library, thanks :-) - just describing a use case), wouldn't it make sense to make a hard version cut and make these names up-to-date and inform people they have to update the names?

Have you alternatively thought/already discussed just keeping a namespace for the different icon libraries, and naming e.g. ``icon-fa-clock``, ``icon-io-trash``, ...? Would definitely make things cleaner and easier to separate and also eases search and replace operations a lot (probably lots of people are switching from some of the separate libraries).

Just my 2 cents, of course this would be one harsh version cut.

**Comment by sschueller** [comment]
I guess you could also keep the current naming and additionally add the namespace naming. That way existing users wont notice a change and new users can use the namespace for the correct icon names.
