### ISSUE TITLE
Hinting(?) issue on dark backgrounds

### ISSUE THREAD

**Issue by leopiccionia** [fontello/fontello#604]
I've made a font with custom [programming language icons](https://github.com/leopiccionia/programmicons). The `hinting` option was set to `true`, but it also seems to happen with the option set to `false`.

The font looks great on light backgrounds:
![image](https://cloud.githubusercontent.com/assets/9576518/26272625/c0bb8350-3cf3-11e7-9bc9-3a6bbdf960e3.png)

However, it looks slightly "bolder" on dark backgrounds:
![image](https://cloud.githubusercontent.com/assets/9576518/26272634/24fca45c-3cf4-11e7-91a3-84b82c6011a8.png)

To be sure it's not just optical illusion, here's a XOR (*exclusive or*) of both images:
![image](https://cloud.githubusercontent.com/assets/9576518/26272714/c2c919a8-3cf5-11e7-87c4-d0115d6e1998.png)

I've tested it on Firefox, Chrome and Edge on my Windows, and a friend tested it on his Trisquel distro, with very different hardware, and the glitch always occur. I'm not using no custom CSS except Twitter Bootstrap v3.3.7.

Am I doing something wrong, or is it a Fontello issue?

**Comment by leopiccionia** [comment]
Here's a [link to config.json](https://github.com/leopiccionia/programmicons/blob/master/docs/config.json), if it helps.

And here is a [live demo](https://leopiccionia.github.io/programmicons/programmicons.html).

**Comment by JohnEcks** [comment]
I'm not saying this is your problem, but white on black typically looks bolder to the eye than black on white. I compared your images and the pixels line up exactly.

**Comment by leopiccionia** [comment]
My first thought was about optical illusion, too. However, my third image uses [pixelwise XOR (exclusive-or)](https://en.wikipedia.org/wiki/Exclusive_or), where a black-ish pixel in resulting image represents a pair of pixels that has similar shades in both images, i.e. white foreground on one image, white background on the other. Therefore, it means that the foreground/background ratios in both images differ in the screen, not only in our eyes.

Possibly the issue is foreign to Fontello, being a hardware or configuration issue, for example. It's the reason for providing a live demo of the issue, linked in this thread.

I agree with you that it's partly my problem: I could simply use less detailed icons and carry on my life. However, if it's a recurring problem with other users, I think it's worth reporting.

**Comment by puzrin** [comment]
Seems not fontello issue. Closing.

If you do not agree - need more details why this can be fonello-specific.
