### ISSUE TITLE
Bitcoin donations?

### ISSUE THREAD

**Issue by NxtChg** [fontello/fontello#609]
Please add Bitcoin donation address to your awesome service!

And thank you for doing this.

**Comment by puzrin** [comment]
`1fbGaPHFUgub47XGzKZzVhhGhUYcJmoZK` - try this one.

Never expected this can be useful on fontello :)

**Comment by NxtChg** [comment]
Sent a little :)

I suggest putting this address on the site, maybe others would be inclined to donate too.

**Comment by puzrin** [comment]
Will do, no problem. I'll keep this issue open until done.

**Comment by puzrin** [comment]
Seems not very  actual. Closing.
