### ISSUE TITLE
Can we somehow automate the process in a Github chatbot?

### ISSUE THREAD

**Issue by amihaiemil** [fontello/fontello#610]
Would be nice to automate the whole process of adding a new svg icon to an already existing font.
Say, for instance, that we have a Github chatbot. When I tell it: ``add [this](ling/to/svg) svg pls`` it should add it automatically and I should then be able to access it directly via css class ``icon-[name]``.

The bot would operate on gh-pages repos only, as those are the only ones which support websites. It would first create the webfont files and update the existing ones, which would become online imediately.

What do you think? Would it be possible? Yesterday I added a Gitter svg to my font-awesome library and spent about an hour on it...

**Comment by puzrin** [comment]
Fontello provides API https://github.com/fontello/fontello#developers-api  and everything else is out of project scope.

Some api samples available in wiki: https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport
