### ISSUE TITLE
fontello.css missing

### ISSUE THREAD

**Issue by ExillustX** [fontello/fontello#612]
when i download the font collection, in css folder fontello.css is missing! is it replaced with text.css?

![Screenshot](https://www.dropbox.com/s/5cl3kehklnyw5ap/Screenshot%20at%202017-07-29%2018%3A57%3A06.png?raw=1)

**Comment by ntdvl** [comment]
Yes. Exactly. 
![2017-07-30_144129](https://user-images.githubusercontent.com/8450954/28753014-4129b8da-7535-11e7-86f6-7a540744ec44.jpg) This is my fontello folder.

**Comment by puzrin** [comment]
CSS files use font name as prefix ('fontello' if not set).

Works as intended.
