### ISSUE TITLE
CSS prefix still appears

### ISSUE THREAD

**Issue by beckylopes** [fontello/fontello#613]
I deleted all the text in the box so my icon names would be the ones I chose, but the demo file still shows the "icon-" prefix.
I restarted the browser and reloaded the icons but still the same thing.
Help?!

**Comment by puzrin** [comment]
That's not supported out of box. For all custom requests of such kind it's recommended to write script and generate CSS from `config.json`.

**Comment by beckylopes** [comment]
Thank you :)
