### ISSUE TITLE
display  error

### ISSUE THREAD

**Issue by ccseer** [fontello/fontello#615]
different display  between Windows and Mac.

It works fine on Mac, but not on Windows.

tested on Chrome and generated font

[OneDrive.zip](https://github.com/fontello/fontello/files/1240984/OneDrive.zip)

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/29551137-021087ca-8744-11e7-8228-cd6cef4d8a8f.png)

![image](https://user-images.githubusercontent.com/15963166/29551155-0d93eb82-8744-11e7-8973-1b63fc9f7ba0.png)



![image](https://user-images.githubusercontent.com/15963166/29551167-1b8da2d2-8744-11e7-8a9f-e93441018042.png)

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-use-custom-images

You have wrong contour directions in src images

**Comment by ccseer** [comment]
Wooow~

Thank yoooooooooooou~~
