### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by derwaldgeist** [fontello/fontello#616]
I saw that less support was already proposed in #178, and I would like to request Sass support, too. In the comments of #178 you asked why this is actually needed, i.e. what cannot be done with CSS that can be done with Less or Sass.

The answer is simple: if you have a large webapp that uses a build system, you have to be flexible about providing the font folder locations. In my case, I am using MeteorJS and package my custom font in an Atmosphere package. The font will be bundled into my app using Meteor's rules, so I have to customize the font path in order to make it point to the right target. Relative paths are not enough here.

It would be great if you could pass in a Sass variable for the font path, like it is done with the Sass versions of fontawesome and materialdesignicons. Using Sass would also allow you to define the icon prefix on the fly, even after you have downloaded the font. The aforementioned fonts support this level of customization as well.

**Comment by puzrin** [comment]
1. You can use `*-code.css` and add outer definitions in your app
2. You can script upload/download operations via api and create any additional file from config.json

Please use old issue for comments.
