### ISSUE TITLE
[Suggestion] Change font directory to fonts

### ISSUE THREAD

**Issue by Frondor** [fontello/fontello#619]
I encounter myself manually renaming these lines every time I use fontello, since I use bootstrap and I'm importing more than one font from `/fonts` directory, I suggest to go for the plural. It'll just make easier the integration with most projects (and bootstrap).

This could easily be a config feature.

**Comment by JohnEcks** [comment]
I agree, I also use "fonts" as my folder name. Maybe there can just be a config feature as suggested by Frondor for those of us who use the plural.

**Comment by puzrin** [comment]
No plans to change files layout. You can use scripts to upload/download data and automate any additional operations https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport

**Comment by zcesur** [comment]
```bash
find . -type f -exec sed -i 's/\/font\//\/fonts\//g' {} \;
mv font fonts
```

**Comment by geri777** [comment]
How about allowing to change the font directory in the fontello.com settings (advanced font settings)?
Many thanks!
