### ISSUE TITLE
svg appears too large when imported 

### ISSUE THREAD

**Issue by gallaghers472** [fontello/fontello#620]
Hi when I try and import the attached svg it appears too large, with only 2 dots visible. I would like it to be smaller with all 3 dots fitting in the icon thank you. Because github doesn't support svg I had to add .png to the end. please remove the .png when testing the image thank you 

![ic_more svg](https://user-images.githubusercontent.com/31947628/30413749-55374322-9963-11e7-9afa-eafd5a8db367.png)

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-use-custom-images
