### ISSUE TITLE
IE11 Browswer is hanging

### ISSUE THREAD

**Issue by NarenderRao** [fontello/fontello#622]
Hi,

Currently we are using fontello font in our code. To make our application compatible with IE 11 we are adding IE reference in our master page. This is SharePoint application.
<meta http-equiv="X-UA-Compatible" content="IE=Edge,Chrome=1;IE=11;IE=10" /> 

After adding this code in master page browser is hanging, In further investation we realized that issue is coming from fontello font reference. This is working fine in other browsers.

@font-face {
    font-family: fontello;
    src: url(fontello.eot?95581469);
    src: url(fontello.eot?95581469#iefix) format('embedded-opentype'), url(fontello.woff?95581469) format('woff'), url(fontello.ttf?95581469) format('truetype'), url(fontello.svg?95581469#fontello) format('svg');
    font-weight: 400;
    font-style: normal
} 
This is used as below

.glbSearchIcon:before {
    font-family: 'fontello'; 

Please suggest feasible solution options for this issue.

**Comment by puzrin** [comment]
No ideas about IE modes. Probably worth report to Microsoft.

**Comment by puzrin** [comment]
Close as outdated.
