### ISSUE TITLE
Glyph not working in Firefox for Mac

### ISSUE THREAD

**Issue by kailt** [fontello/fontello#624]
Hi,

I'm using a font generated with Fontello in my website but I've detected that one of the glyphs (an eye icon) is not displaying correctly on Firefox for Mac (v56 stable, tested on both Sierra and High Sierra). It does work properly in Firefox for Windows and Linux, as well as other major browsers, such as Chrome, Safari, Edge, IE11, etc.

Here is how the icon is expected to look like:
[Screenshot taken in Chrome](https://i.imgur.com/PDsgkDe.jpg)

Here's how the icon actually looks like in Firefox for Mac:
[Screenshot taken in Firefox](https://i.imgur.com/RKYHz7W.jpg)

Link to the affected page, so you can see it for yourself:
https://www.wikiloc.com/wikiloc/map.do?lt=37.261612&ln=-106.872070&z=6&k=1&act=

The included fontello font:
https://sc.wklcdn.com/wikiloc/assets/styles/fonts/css/wikiloc-font.min.0703ade4.css?v=1.9.3

**Comment by puzrin** [comment]
Check how FF on Mac show demo page. May be your CSS minifier does something wrong.

**Comment by kailt** [comment]
I tried using the non-minified version and it doesn't work either.

**Comment by puzrin** [comment]
Please, check demo page, as i asked. It's included in generated font archive.

**Comment by puzrin** [comment]
close - timed out.

**Comment by kailt** [comment]
Hi, sorry for the delay. I checked the demo.html and it's got the same issue.
