### ISSUE TITLE
Feature request: User accounts

### ISSUE THREAD

**Issue by Gotterbild** [fontello/fontello#625]
First, thanks for the great service!

I didn't find the option to create an account. 

Maybe it is available for users who donated, but I don't have ability to donate right now (but going to do that in the future). If this feature exists, just close the issue and don't waste time for an answer. I'll receive an email from GitHub and will understand.

But if feature doesn't exist - I have no idea why didn't you do that.

I suppose user's info is stored in localstorage (or equivalent) and available only in browser. That leads to the list of issues:

1. If something happens to browser or machine - I'll loose my font. I'll have to config it again and it can take a lot of time. Or can lead to loss of icons if custom icons were used.

2. If I need to work on more than one projects in parallel, I'll need to use multiple browsers. It is totaly uncomfortable. And it makes the first issue even worse (I'll loose a lot of work if something will happen to machine).

So, if there was an option to save a font, that would be great. I understand that it will introduce the need of DB (or DB-less equivalent with files as storage). I understand that it will require space on your server.

But you make this feature payed with this options:
1. Free - no registration needed. Service works like this right now.
2. Beginner - user can save his fonts configs, but can't save custom icons. This option will require very very small space on a server.
3. Pro - user can save fonts with custom icons.

Also, you can set a limit of saved fonts and/or saved custom icons and make several plans with different limits. Or user just pay per saved font and per saved custom icon without any plans.

For me, it will be a killer feature and I will certainly pay for that.

What I proposed is just my thoughts. The main idea - is to have a way to save a font config, load a font config and switch between your font configs easily.

If you'll need someone to discuss feature with, I'm at your service. Also, I can propose design in both graphical and technical meaning. Not sure if I can help with coding, as I'm not familiar with most technologies Fontello uses and right now don't have time to get familiar with them.

Thank you for any reaction!

**Comment by NxtChg** [comment]
> So, if there was an option to save a font, that would be great.

Yep, this is the major annoyance when you work on several projects at once.

Would be nice to save the font somehow (even as a simple txt file that could be later loaded and would select the same glyphs).

Accounts would require more hassle, but if you could save various fonts there, that would also solve the problem.

**Comment by Gotterbild** [comment]
> Would be nice to save the font somehow (even as a simple txt file that could be later loaded and would select the same glyphs).

@NxtChg When you're downloading a font there is `config.json` file. You can import it: 
![image](https://user-images.githubusercontent.com/23502743/31552411-154b71b8-b040-11e7-8849-6d19ece83a4b.png)

I know about this feature, but you have to take care for `config.json` file for every font change you do. User accounts will make it much more comfortable.

**Comment by NxtChg** [comment]
> When you're downloading a font there is config.json file. You can import it:

Oh, wow, missed that, thanks! Pretty obscure :)

**Comment by puzrin** [comment]
@Gotterbild see #483. Also i expleined in some similar issues, that moving into directions if user accounts is not best idea in my situation:

- that's possible only with payed services added (because taking responsibility of user data for free is stupid)
- i don't wish to spend efforts for commerce about fontello.

Problem you describe is not lack of user accounts on website, but lack of sharing data. This can be solved in different ways (gists, dropbox, amazon etc).
