### ISSUE TITLE
Suggestion: sort glyphs and demo page

### ISSUE THREAD

**Issue by saidbakr** [fontello/fontello#626]
I have two suggestions:
 1. Allow to sort font's glyph by code or by its title.
 2. The icons in demo page should have HTML id attributes, let it to be its code to allow linking to it via anchor. For example, I have imprints or credits page that I need to link it with glyph demo to give attribution to the author of the glyph.

**Comment by puzrin** [comment]
Icons are stored in the same order as selected on "customize names tab" (can drag & drop there).

For any alternative you can use scripting and generate different demo from `config.json` automatically after download https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport
