### ISSUE TITLE
Fully integrated font manager API

### ISSUE THREAD

**Issue by Fleuv** [fontello/fontello#627]
Fontello always has been one of my common features when it comes to building applications. Unfortunately it's kind of harsh to predict what icons are going to be used. In some extreme cases it's not possible to predict at all, because the icons don't exists yet. The content of the application is constantly changing.

That's why I would like to fully integrate a font manager API where you can create/build on a certain font configuration for your application. The more significant features for such an API would be uploading the JSON configuration to Fontello what will update the selected configuration file and the related files for that configuration file on the fly in your application. Thus you have to be able to perform the following calls

**bold** = architectural significant

- GET: All fonts (for visualization) and probably also a specific font.
- GET: All glyphs of a font (for visualization) as well as a specific glyph.
- **GET: Retrieve the font files.**
- **GET: Retrieve the CSS files.**
- **POST/GET: Create/Retrieve the configuration.**
- **PUT: Upload a custom icon/glyph.**
- DELETE: Remove a custom icon/glyph

**Comment by puzrin** [comment]
https://github.com/fontello/fontello#developers-api

What's wrong with existing API? It allows all important operations (everything else can be done on user side)

**Comment by Fleuv** [comment]
Whoops missed that, I was quite confused after reading this: https://github.com/fontello/fontello/wiki/How-to-use-fontello-fonts-in-your-project

But that developer API should do about it.

So if I understand correctly, the API redirects the user to fontello.com when the user wants to edit the font where after all changes are sent to the server where the user was originally redirected from?

**Comment by puzrin** [comment]
Everything works exactly as described [here](https://github.com/fontello/fontello#api-methods)

Examples available at https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport

**Comment by Fleuv** [comment]
Hey Puzrin,

I've tried to use the fontello-cli node.js module but after clicking "Save session" I don't detect any changes in the config nor font files (I don't use the stylesheets). What should happen after clicking the "Save session" button? I expected it to update the files I just mentioned. Now I still have to download the webfont package extract the files I want and move them to the right directory.

**Comment by puzrin** [comment]
Fontello-cli is 3-rd party code, i can not comment it. After clicking "save", data is stored on server. Then you can download if via api request. Or you can be redirected to external url, and other server can make download. Please, read API description, everything is described there. Also, see makefile, it has working code.
