### ISSUE TITLE
Get all font codes

### ISSUE THREAD

**Issue by g-rodigy** [fontello/fontello#630]
Have you config file for all icons?
I don't find in this repository.

**Comment by woshixixi** [comment]
you can see font codes in demo html
![image](https://user-images.githubusercontent.com/18056146/48124716-f9a47f80-e2b7-11e8-8ea5-a3b01da49dfa.png)

**Comment by louisameline** [comment]
I need the codes too (in the config.json file, not shown on my screen on demo.html) to use them in an SVG object.

Am I missing something here? Is there another way to do it?
What's the use of the code shown in config.json by the way? Can't find an answer.

I asked the question on Stackoverflow too, no answer so far.
@puzrin would you know about that?

https://stackoverflow.com/questions/57819421/how-do-i-retrieve-a-fontello-icons-code-programatically

Thank you

**Comment by louisameline** [comment]
I figured it, the codes in the json file are a decimal version of the hex code that can be found in the css file. You have to write `code.toString(16)` to get the hex value. I guess it was obvious to erveryone else since it's not mentionned anywhere :(

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/tree/master/lib/embedded_fonts (autogenerated)
