### ISSUE TITLE
I can't donate Russian rubles via PayPal

### ISSUE THREAD

**Issue by AlexWayfer** [fontello/fontello#634]
![image](https://user-images.githubusercontent.com/6510020/35437778-f59c164e-02a4-11e8-86c7-9c6111b9442c.png)

Google Translate (I think it good enough):

> The payment initiated by you is blocked, as payments with PayPal between residents of Russia can be made only in Russian rubles. Return to the seller's website and select a payment option in Russian rubles or use a different payment method.

I've tried work-around: credit card instead of PayPal account, but I can't find Russian Federation in the countries selection:

![image](https://user-images.githubusercontent.com/6510020/35437861-5e706760-02a5-11e8-8d14-7244636a7f52.png)

**Comment by puzrin** [comment]
Seems a paypal problem - it doesn't allow to change currency for button.

See email at top page, when you click paypal button. You can send there rubles manually if you wish.

**Comment by AlexWayfer** [comment]
It may be worth adding other payment methods.

**Comment by AlexWayfer** [comment]
For example, like a https://www.paypal.me/%username%

**Comment by puzrin** [comment]
https://www.paypal.me/etomne ok :).
