### ISSUE TITLE
repeat icons

### ISSUE THREAD

**Issue by rewardsfuel** [fontello/fontello#636]
Hello, I love your font, its a huge help.  I apologize ahead of time if this has already been asked and I missed it.  I use the upload JSON file to keep my font up to date.  I was hoping to repeat a fontawesome icon because I use naming like icon-1,icon-2 etc.  I tried to manually update the JSON file to repeat one of my fontawesome icons and it just gets ignored.  Is there a way around that?

**Comment by puzrin** [comment]
Dupes are not supported, sorry.

https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport

You could use scripting, and add any customizations after download, based on `config.json`. [Here](https://github.com/fontello/fontello/blob/master/Makefile#L63-L94) is example fontello uses itself.
