### ISSUE TITLE
Fonts files trying load something from fontello.com?

### ISSUE THREAD

**Issue by zorinpavel** [fontello/fontello#640]
I downloaded fonts, add css, everything is perfect!
BUT when I load my page with this fonts I see this requests in console:

«http://fontello.com/assets/fontello-2a201e9f28fc5fd5c0d804f286fe408b.woff2»
«http://fontello.com/assets/icons-08bcaf8eba11bfa69138789938554a86.woff2»

What is that?

**Comment by puzrin** [comment]
No ideas, it's something at your side in css.
