### ISSUE TITLE
Why "Payload Too Large"?

### ISSUE THREAD

**Issue by dimaeromin97** [fontello/fontello#642]
If you add more than 105 icons, the session is will be not saved because "Payload Too Large".

>**To play this, you need: open http://fontello.com/ with config.json that is:** 
>![screenshot](https://user-images.githubusercontent.com/21929069/37057971-bc14781a-2191-11e8-84c7-dc9e5ce4ecd8.png)

[File config json](https://drive.google.com/open?id=1kSlKr2_7m3S7oEXxS15ay7odQtlj89TW)

![download](https://user-images.githubusercontent.com/21929069/37056880-4e9c7bf0-218e-11e8-9bc8-337da92c8c78.png)

**Comment by timothyfisherdev** [comment]
Any update on this? Experiencing this problem as well. Loaded in elegant fonts from divi and just want to select a few of them but getting "Payload Too Large" error.

**Comment by rlidwka** [comment]
Fixed, thanks for reporting.

Actual limit on config size is now raised 100x times, which will be enough hopefully.
