### ISSUE TITLE
How do I use Fontello in PowerPoint?

### ISSUE THREAD

**Issue by haveaquestionaboutthisproject** [fontello/fontello#647]
Hello, I'm trying to use Fontello in PowerPoint - is that possible?
I put encoding as Text characters, downloaded font, installed icons.ttf but don't know what to do next.

**Comment by qp-line** [comment]
You may find a file which ends with '.ttf' in the folder named 'font' as you download the webfont package ,and then install it as other fonts in your computer. After that ,you can find the font-family as what you name in your document when you insert a word, choose what you need ,and then copy the area of the shape from the demo.html.

**Comment by EfrenPerez94** [comment]
I do exactly the same as @qp-line  and works for me, Im using a MacBook Pro 2017, this issue could be closed at least the problem persist on Windows
