### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by himanshuwt** [fontello/fontello#649]
![image](https://user-images.githubusercontent.com/21654174/39112964-c2a6ef56-46f7-11e8-9762-0b8e00be56bb.png)

It was working fine. I added 5 new icons and then updated the CSS and now it is not working. Please tell me how to fix it?

**Comment by puzrin** [comment]
For example, you can remove woff2 font, or test if it's mime type is properly configured. Anyway, first, check if included demo page works or not. If not - then attach archive.
