### ISSUE TITLE
Can't download fonts anymore

### ISSUE THREAD

**Issue by wim-mertens** [fontello/fontello#650]
I have used fontello for years but as of yesterday I can't seem to download the font set anymore. It is showing an alert with "Communication problems. Please try again later."

**Comment by puzrin** [comment]
Seems to work as expected. Could you retry (or ctrl+F5 and retry)?

**Comment by wim-mertens** [comment]
Still not working for me, see screenshot:
![fontello1](https://user-images.githubusercontent.com/5226333/39335578-b566af76-4a07-11e8-9ddd-411dc7d98031.jpg)

**Comment by puzrin** [comment]
Could you ping/traceroute fontello.com? Seems network issue at your side.

**Comment by wim-mertens** [comment]
Seems ok:
![fontello2](https://user-images.githubusercontent.com/5226333/39335823-b41bd140-4a08-11e8-9f4b-3dc577ea27fc.jpg)

**Comment by wim-mertens** [comment]
It might be an issue with Sophos firewall/proxy but I never had this issue before. Disabling does not seem to resolve it though...

**Comment by puzrin** [comment]
I've restarted server for sure. Works for me, and worked before. Try another browser/computer/provider.

**Comment by wim-mertens** [comment]
I have tried all other browsers too, to no avail. I will test in another environment soon and get back to you. Thanks for your help so far.

**Comment by wim-mertens** [comment]
was indeed an issue with the firewall. confirmed is not a bug.
