### ISSUE TITLE
How to create request via axios

### ISSUE THREAD

**Issue by martin-badin** [fontello/fontello#651]
Hello,
I need help with create the POST request via axios. My code is here.
```js
const formData = new FormData();
formData.append('config', JSON.stringify(fileData));
const data = await axios.post('http://fontello.com/', formData);
```

fileData - config.json downloaded from fontello.com
header is set to `Content-Type: multipart/form-data;`

and everytime I have error message `Missed "config" param - must be file`. Where I make mistake?

**Comment by puzrin** [comment]
You should encode `config` field as file, not as string. See https://github.com/fontello/fontello#examples sources. I think `fontello-cli` should help.

**Comment by martin-badin** [comment]
I tried it some days, but I'm wasn't successful. Please help my implement the API from php/Laravel/GuzzleHttp or javascript. I tried different code implementations, but nothing worked. Did anyone try it? It works to someone? Thanks for help
