### ISSUE TITLE
[problems in Hetzner] fontello.com down?

### ISSUE THREAD

**Issue by entr** [fontello/fontello#655]
Just wanted to draw attention to the fact http://fontello.com is down.

**Comment by owen-mills-from-school** [comment]
+1

**Comment by owen-mills** [comment]
+1

**Comment by Arkmind** [comment]
+1

**Comment by RezaMaz** [comment]
+1

**Comment by GigiSan** [comment]
+1
I don't use Twitter, maybe someone could ping the dev?
https://twitter.com/puzrin

**Comment by mariocasciaro** [comment]
I already pinged him on twitter a few hours ago. 
By the way, you can run Fontello locally in the meantime, it's very easy. Make sure you have Node.js and `ttfautohint` (`brew install ttfautohint` or use your package manager) installed on your system. 
Clone the repo, `npm install` + `node server`. Open `localhost:3000` and you will have your own Fontello.

Kudos to the Fontello team for making it so easy.

**Comment by puzrin** [comment]
https://www.hetzner-status.de/en.html

Global power failure in Hetzner. They still fixing it.

**Comment by puzrin** [comment]
> Categories: Basic infrastructure
> Start: May 24, 2018 11:30:00 AM CEST
> End: **Unknown**

Take it easy, sometime shit happens :). I hope you forgive that i don't invest resources into reserve instances of this non-commercial project. Hoster's failure of multiple-reserved hardware which-should-never-fail-because-multiple-reserved - is a force majeure. That's not specific for my server. I think, hetzner's stuff will do the best to fix things.

PS. If you have something very urgent - you can install fontello locally, as suggested by @mariocasciaro .

**Comment by GigiSan** [comment]
No worries boss. Thanks for the update :)

I was personally just worried that it was a problem with the site itself... like an attack or the fact that who.is states the domain is expired. >_<

Have a nice day! ☺
Gigi

**Comment by yoohyunseog** [comment]
lol

**Comment by yoohyunseog** [comment]
+1

**Comment by laven2** [comment]
@mariocasciaro @puzrin 
I have some problem after `node server`
`[FATAL] 5188 system - Router config contains unknown server API methods: fontello.font.download`
how to fix it?

**Comment by puzrin** [comment]
@laven2  I have no telepathy skills. Propably it worth to create separate issue with details

**Comment by guopeng1994** [comment]
+1

**Comment by anupattulips** [comment]
@mariocasciaro @puzrin 
I have some problem when running `node server`
`fontello/lib/system/runner.js:118
  async function execute() {
        ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/fontello/server.js:12:3)
    at Module._compile (module.js:570:32)`

Note: I had clone from github repository, and did npm install and run node server.

**Comment by anupattulips** [comment]
@puzrin @mariocasciaro It did work after I update my node version and npm to the latest one. Great work guys. Thumbs up.

**Comment by firstrow** [comment]
+1

**Comment by puzrin** [comment]
Please, do not post `+1` here instead of votes for posts. That will not help Hetzner to repair faster :).

**Comment by puzrin** [comment]
Server is back after 30h downtime.

Closing.

**Comment by anupattulips** [comment]
At last.
