### ISSUE TITLE
Some problems with run project local 

### ISSUE THREAD

**Issue by laven2** [fontello/fontello#656]
I'm clone repo and run `npm install`  and `node server`
after run i get error
![image](https://user-images.githubusercontent.com/10598311/40535483-ed359f32-6011-11e8-946a-a0aebdf47ec3.png)
in bundle.js:47 i change 
`  let api_path_start = path.dirname(name).replace(new RegExp(path.sep, 'g'), '.');`
to 
  `let api_path_start = path.dirname(name).replace(new RegExp('\\' + path.sep, 'g'), '.');`
and get new error
![image](https://user-images.githubusercontent.com/10598311/40535633-537942f8-6012-11e8-82ba-73b7018f120b.png)

**Comment by puzrin** [comment]
Hm... we don't use windows and never tried to run fontello in it. Do you have possibility to run fontello on linux host or in linux shell? May be, via Virtualbox. Or, latest windows was declared to support some linux shell umelation (i don't know details)

**Comment by AlexWayfer** [comment]
> Or, latest windows was declared to support some linux shell emulation (i don't know details).

https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

**Comment by anupattulips** [comment]
@puzrin I have using MAC and install ttfautohint, clone repo, `npm install` and `node server` but I am getting this

`fontello/lib/system/runner.js:118`
`async function execute() {`
`^^^^^^^^`
`SyntaxError: Unexpected token function`
`at Object.exports.runInThisContext (vm.js:76:16)`
`at Module._compile (module.js:542:28)`
`at Object.Module._extensions..js (module.js:579:10)`
`at Module.load (module.js:487:32)`
`at tryModuleLoad (module.js:446:12)`
`at Function.Module._load (module.js:438:3)`
`at Module.require (module.js:497:17)`
`at require (internal/module.js:20:19)`
`at Object.<anonymous> (/Applications/MAMP/htdocs/fontello/server.js:12:3)`
`at Module._compile (module.js:570:32)`

**Comment by puzrin** [comment]
@anupattulips make sure your node version is 8+. Probably 10 should work.

**Comment by anupattulips** [comment]
@puzrin It worked. Thumbs up. Amazing work.

**Comment by odera89** [comment]
after run. when I want to download the font I get this error...

`[2018-05-25T14:38:04.018] [FATAL] 43283 rpc@ - 127.0.0.1 - "POST /RPC/fontello.font.generate?config= HTTP/1.1" 200 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36" - [500] Error: spawn ttfautohint ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-05-25T14:38:04.019] [FATAL] 43283 system - ***
ip:        127.0.0.1
url:       /io/rpc
request:   POST
responder: rpc
apiPath:   fontello.font.generate
params:    {
  "config": ""
}

stack: Error: spawn ttfautohint ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

error: {
  "code": "ENOENT",
  "errno": "ENOENT",
  "syscall": "spawn ttfautohint",
  "path": "ttfautohint",
  "spawnargs": [
    "--no-info",
    "--windows-compatibility",
    "--symbol",
    "--fallback-script=latn",
    "/var/folders/y7/pph1vlfx6hz3c4vkj0cjtpp80000gp/T/fontello/fontello-54e371f8/font/xxx-unhinted.ttf",
    "/var/folders/y7/pph1vlfx6hz3c4vkj0cjtpp80000gp/T/fontello/fontello-54e371f8/font/xxx.ttf"
  ],
  "cmd": "ttfautohint --no-info --windows-compatibility --symbol --fallback-script=latn /var/folders/y7/pph1vlfx6hz3c4vkj0cjtpp80000gp/T/fontello/fontello-54e371f8/font/xxx-unhinted.ttf /var/folders/y7/pph1vlfx6hz3c4vkj0cjtpp80000gp/T/fontello/fontello-54e371f8/font/xxx.ttf",
  "name": "Error",
  "message": "spawn ttfautohint ENOENT"
}
`

Can you help me!?

**Comment by puzrin** [comment]
@odera89 you should install ttfautohint OR disable hinting in fontello settings

**Comment by puzrin** [comment]
There are some install intructions here https://github.com/fontello/fontello/blob/master/INSTALL.md

**Comment by odera89** [comment]
yes. nice. is working for me 👍

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/issues/656#issuecomment-392027825

**Comment by puzrin** [comment]
- Last commit should fix run under Win https://github.com/fontello/fontello/commit/3f8450f4d95995a3902b1ec7d3ef9b39d402d5eb.
- Also, not sure about ttfautohint under win, but you can disable is in settings
- Most of bin deps were removed (except leveldb), and fontello should not depend on system packages.

Also note, Win is not actively tested, we develop all under linux (ubuntu) and have no resources to test Win platform. If someone may help with configure appveyour to run tests under win - PR welcome.

Closing, because key issues should be solved. Feel free to create new issue if something new happens.
