### ISSUE TITLE
why horizontal single lines appear extremely big?

### ISSUE THREAD

**Issue by fusun470** [fontello/fontello#661]
I am creating custom webfonts and if it is a simple horizontal line it appears huge on preview and when downloaded and inserted same problem happens. So far I've tried outlining the path, making compound path but it didn't work. Why I can't keep the same proportion with horizontal lines?
![screen shot 2018-08-02 at 8 39 05 am](https://user-images.githubusercontent.com/15936078/43584238-dcce2638-962f-11e8-9bf1-9c88affe8da5.png)
![screen shot 2018-08-02 at 8 39 00 am](https://user-images.githubusercontent.com/15936078/43584239-dcde24d4-962f-11e8-9b42-f14078e39363.png)

**Comment by puzrin** [comment]
Something may be wrong with your source. https://github.com/fontello/fontello/wiki/How-to-use-custom-images make sure those are prepared properly, try again. If problem still exists - please provide example how to reproduce.
