### ISSUE TITLE
Modifying the config.json file directly

### ISSUE THREAD

**Issue by M1ke** [fontello/fontello#662]
Is there a reference for modifying the config.json file directly?

I have an SVG path and so want to create an icon. How do I determine the `code`, `uid`, `src`, `selected` parameters? I can see how I can add a path and width. So far I've tried but the icon rendered is one that isn't even included in the project, I guess because it shares a code with unicode or similar.

If this question was answered it would make a useful wiki page.

**Comment by puzrin** [comment]
Download font with custom icons, and see config.

- uid => any random, used to identify icon.
- code => any you need
- src => "custom_icons"
- selected => true
