### ISSUE TITLE
Unable to open fontello site

### ISSUE THREAD

**Issue by toton333** [fontello/fontello#664]
I'm always getting this error Asset load error: **"N.Wire" unavailable after asset load.**

![fontello](https://user-images.githubusercontent.com/7140284/44647999-57396780-a9fd-11e8-9913-50b38fa8e88e.png)

**Comment by puzrin** [comment]
ctrl + f5 ?

**Comment by toton333** [comment]
ctrl + f5 not working either, i tried that.

**Comment by toton333** [comment]
Nope, still not working after browser cache clean up the error pop up message are coming in delay like 10 seconds later, but no icons are showing still. Tried with internet explorer, same problem.

**Comment by puzrin** [comment]
That's strange, server works. Can your provider force transparent proxy cache?

Try in Chrome for shure:

- go to fontello
- open debugger (F12)
- Right click on "reload" button and select "Cache cleanup and hard reload"

**Comment by toton333** [comment]
hi, just did that, i'm pasting what the 1 error i'm getting from the debugger
Uncaught TypeError: Cannot read property 'load' of undefined
```
    at Object.<anonymous> (/assets/bundle-fontello.en-US-e0f4e12618de6dd75302135cc51f749f.js:2)
    at Object.o.execute (fontello.com/:2)
    at /assets/bundle-fontello.en-US-e0f4e12618de6dd75302135cc51f749f.js:1
    at Object.application/javascript (fontello.com/:2)
    at m (fontello.com/:2)
    at fontello.com/:2
```
and the link address of the error is :
` /assets/bundle-fontello.en-US-e0f4e12618de6dd75302135cc51f749f.js`

**Comment by toton333** [comment]
btw i'm working on localhost.

**Comment by imzfly05** [comment]
Asset load error: "N.Wire" unavailable after asset load. google chrome.
cache cleaning is not helping!

**Comment by abhijitXD** [comment]
Yep. This is issue is still there

**Comment by OmarQataberi** [comment]
is there any solve to this error, I got a similar one in FlutterIcon.com

**Comment by puzrin** [comment]
Let's close as outdated. Create new one if needed
