### ISSUE TITLE
all icons blank when uploaded from Fontello

### ISSUE THREAD

**Issue by 5amcrawford** [fontello/fontello#666]
I'm trying to use custom SVG icons on elementor. After uploading using Fontello, none of the icons show. They are all blank.

This is also the case when trying to upload any of the premade Fontello icons. After uploading the zip file with any selected icons, it shows the file name but no icons. 

Please help if possible! I've been pulling my hair out trying to get it to work! (and I already don't have enough hair)

Thanks

Sam

**Comment by Inadurill** [comment]
I have the same problem. I've checked all the possible options and nothing. Sometimes I only see squares, sometimes nothing. Is it possible that I'm doing something wrong or is there another problem?

Thanks, Kuba

**Comment by puzrin** [comment]
Is this still actual? If yes, can you provie sample how to reproduce?
