### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ChristopherHButler** [fontello/fontello#670]
I'm not sure this is the correct place for this so I apologize if it's not. 

I was hoping someone could add a cookie with a bite taken out of it as seen here: https://www.flaticon.com/free-icon/cookie_1047813

Again, apologies if this is not the correct forum for this. keep up the amazing work 🥇

**Comment by puzrin** [comment]
Icon requests are not accepted. But you can import custom SVG icons yourself.
