### ISSUE TITLE
Preserve character codes after update

### ISSUE THREAD

**Issue by okinp** [fontello/fontello#672]
Hello,

it would be great if there was an option to preserve codes after updating an existing fontello font with new icons - currently, it appears that codes are created anew.

Thanks!

**Comment by S-AT** [comment]
Same problem here.

When updating the existing font with new glyphs, the codes get messed up.
So I have to correct them manually with every update.

It would be really great to have the old codes unchanged.

Thank you.

**Comment by puzrin** [comment]
Please provide exact sequence how to reproduce (includint test files).

Reordering may happen only if you import svg font instead of config file. This can be changed by `settings` -> `advanced` -> `encoding` -> `unicode`.

**Comment by nigam214** [comment]
Here is what I am experiencing:
1. Upload svg files in custom icon
2. check the unicode mapping each char get
3. these unicode char are starting from e800
4. every time I upload svg files (may have more svg every time), unicode may get changes for old one
5. is there any way to preserve unicode against each svg file? may be get the unicode from file name as done in IcoMoon?

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/issues/672#issuecomment-631542515 did you tried this?

**Comment by nigam214** [comment]
I tried this setting suggested by you. I think PUA encoding is better we I am making custom font icon here. Every time I import SVG files, it starts from E800, though I want to fix some other unicode for each svg file. Did I missed anything?

**Comment by puzrin** [comment]
I don't understand you. What behaviour do you expect? When you import new SVG file, fontello should assign some codes, but it can not guess what you need

**Comment by nigam214** [comment]
This is functionality icomoon has, this type of functionality in fontello would be surely a very useful:

_If you want to re-import all your SVGs each time while keeping your previous codes, embed the code in your file names: home-U0xE999 would get imported with a default code of E999 (hex)._
