### ISSUE TITLE
Issue with SVG corruption in Windows

### ISSUE THREAD

**Issue by DeadcowDesign** [fontello/fontello#673]
Hey, I'm having an issue with the online converter and a glyph that seems to be being corrupted (specifically in woff, and specifically in Windows) when I create a custom font. I've tested the SVG and that seems to be fine, and if I perform the conversion in icomoon I don't see the same issue. It's only the one icon that's being affected (although it does have knock-on effects for the other icons in the font).

**Comment by gap777** [comment]
I'm having similar troubles with SVGs converted to font being corrupted when viewed in Windows browsers (but not on Mac). Did you ever discover the issue or a work-around?

**Comment by DeadcowDesign** [comment]
I'll be honest, this is testing me because I wrote this two years ago. :D 

I'm pretty sure the font glyph was displaying no fixed line height in my case so it was overflowing it's container and colliding with anything that was on the same Y axis on the page. I think my temporary workaround was to just explicitly set the line height to 1 and maybe overflow:hidden on the containing div. Alternatively, Icomoon didn't seem to have the same issue.

Hope that helps.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-use-custom-images

Image should be prepared as one path. If this is still actual, could you provide example how to reproduce?
