### ISSUE TITLE
Allow for Multi-Colored SVG Icons

### ISSUE THREAD

**Issue by ryangwilson** [fontello/fontello#675]
We have a need for multiple colors to be included/embedded in SVGs in out icon sets. This is easily done in IcoMoon, but is a shortcoming of Fontello.

<img width="1380" alt="icon-compare" src="https://user-images.githubusercontent.com/4571457/49163307-c8d5ca00-f2fa-11e8-9ca8-4dd772c3a12b.png">

In IcoMoon we can touch internal paths, e.g.:
```
.icon-sun-happy .path1:before {
  content: "\e900";
  color: rgb(255, 204, 51);
}
.icon-sun-happy .path2:before {
  content: "\e901";
  margin-left: -1em;
  color: rgb(255, 102, 0);
}
.icon-sun-happy .path3:before {
  content: "\e902";
  margin-left: -1em;
  color: rgb(255, 102, 0);
}
.icon-sun-happy .path4:before {
  content: "\e903";
  margin-left: -1em;
  color: rgb(255, 102, 0);
}
```

**Comment by Dreamersoul** [comment]
Fonts are not meant to include colors if I recall correctly. I usually just apply a CSS color property to color the font

**Comment by puzrin** [comment]
As been said - this job is for CSS, not related to fontello.

**Comment by hansmbakker** [comment]
Hi @puzrin, can you please reopen this issue?

The point is that multi-colored SVGs need to be split into multiple glyphs that can be rendered on top of each other.
- The coloring can indeed be done by CSS
- However, the splitting is something that can be done by Fontello
- Also, it would be helpful if Fontello would generate the CSS to stack the glyphs and color them like IcoMoon does:

> Font glyphs cannot have more than one color by default. Using CSS, IcoMoon stacks multiple glyphs on top of each other to implement multicolor glyphs. As a result, these glyphs take more than one character code and cannot have ligatures.

Using this SVG: ![Account circle duotone.svg](https://github.com/fontello/fontello/assets/3463496/b918d109-db28-432e-a4b3-0305354c5001), IcoMoon understands it is a multi-colored SVG that needs to be split into multiple following glyphs, and it generates the required CSS to color those glyphs and stack them on top of each other:

```css
.icon-Account-circle-duotone .path1:before {
  content: "\e900";
  color: rgb(86, 134, 225);
  opacity: 0.3;
}
.icon-Account-circle-duotone .path2:before {
  content: "\e901";
  margin-left: -1em;
  color: rgb(86, 134, 225);
}
```

<img width="793" alt="image" src="https://github.com/fontello/fontello/assets/3463496/20f3b53f-fdc3-4f60-81de-c6560943bdce">

It creates a `\e900` glyph for the background and a `\e901` glyph for the foreground.

This is also how FontAwesome works: https://blog.pieeatingninjas.be/2022/12/13/fontawesome-duotone-icons-in-maui-and-xamarin-forms/
