### ISSUE TITLE
Cannot save font in original order

### ISSUE THREAD

**Issue by qnz1** [fontello/fontello#676]
**English variant**
As for me, there is one very significant problem. Cannot save font in original order.

For example, if you select the first three rows in font awesome, we will get a font in which the user secret glyph will be at the end of the font. And in the font awesome, he walks last in the first row. Glyphs are obtained not in order as they are in the original font.

**Русский вариант**
Как по мне есть одна очень значительная проблема. Невозможно сохранить шрифт в изначальном порядке.

Например если выделить в font awesome три первых ряда мы получим шрифт в котором глиф user secret будет в конце шрифта. А в  font awesome он идет последний в первом ряду. Получаеться глифы сохраняются не по порядку как он есть в исходном шрифте.

**Comment by puzrin** [comment]
Order/codes are preserved only for saved/loaded projects.

Order and codes of original sources were not the same to improve unicode maching.  This may be good or bad decision, but it can not be changed for existing fonts. I think, this magick should be removed for new ones. But current fonts will stay as is, sorry.
