### ISSUE TITLE
icons look like broken when using smaller font-size

### ISSUE THREAD

**Issue by cihanzengin** [fontello/fontello#678]
Hello i imported svg icons to fontello and generate them to fonticon 
but when i use them eg: font-size 40 or smaller they look like broken. Why it's happen? 

![screenshot-localhost-8080-2018 12 13-11-38-29](https://user-images.githubusercontent.com/1409879/49926216-2ad22a00-fecc-11e8-97a9-715a13514b81.png)
![screenshot-localhost-8080-2018 12 13-11-39-27](https://user-images.githubusercontent.com/1409879/49926217-2b6ac080-fecc-11e8-8153-6f6e49de798b.png)

**Comment by puzrin** [comment]
What do you mean "looks like broken"? I don't see difference.

**Comment by cihanzengin** [comment]
1 - There is stroke weight very different :)
2 - If you will look the smaller version there is not look smooth like a big version

**Comment by puzrin** [comment]
Fontello can not magically increase your screen DPI :). You can only enable/disable hinting, but result will be browser-os-specific anyway. Try to search articles about drawing pixel-perfect icon for specific scale. But that's not fontello issue.

**Comment by cihanzengin** [comment]
Excellent support,  just take and close issue :) perfect. 

This is not about dpi my friend exported fonts just lose their stroke weight when font-size smaller: if you will look it an example: https://fontawesome.com/icons/anchor?style=solid maybe you will understand what i mean. 

Anyway, thanks

**Comment by puzrin** [comment]
Effect of lost weight in small size depends on pixel rounding in output devices. There is nothing to fix in fontello, and no reasons to keep issue open.
