### ISSUE TITLE
Chrome not showing all chars when GDI is enabled

### ISSUE THREAD

**Issue by SuperPat45** [fontello/fontello#680]
FontAwesome 5 generate its web font using fontello but only the icons 0xf020 to 0xf0ff are visible with the generated TTF font on Windows desktop and, worse, also with Chrome when GDI rendering enabled (All Chrome versions on Windows Vista / XP and Chrome versions lower than 37 on windows 7+)

Related bugs:
https://github.com/FortAwesome/Font-Awesome/issues/13156
https://github.com/FortAwesome/Font-Awesome/issues/12693

**Comment by RoobieBoobieee** [comment]
Same for a lot of desktop applications. Including word, excel, wordpad. Powerpoint does work. 

Windows 10 - Office 2016 - FA 5.8.1

**Comment by puzrin** [comment]
Is this still actual?
