### ISSUE TITLE
option to base 64 encode fonts in downloadpackage

### ISSUE THREAD

**Issue by Klipper** [fontello/fontello#681]
First thanks for your great tool!

Can you create an extra option for base64 encoding the woff and woff2 fonts and put the result in the css-file in the download-package?
Would be very nice. I now always need to do that as a second step.
Putting small (icon)fonts base64-encoded straight in css speed up the rendering of a webpage: (less server-requests and font is immediately available for browser when parsing the CSS when put in front of the CSS file)
Thanks in advance,
Klipper

**Comment by Klipper** [comment]
I did not looked very well. 
I found that the '***.woff' and '***.truetype (ttf)' already are base64 encoded in the '***-embedded.css'. So finally the only thing I'm missing is the the base64 encoded '***.woff2' file.
Can you please add '***.woff2' also base64 encoded to ***-embedded.css in the downloadable zip?
Thanks in advance.
Klipper

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport

Please use scripting to generate any customized output from `config.json`.
