### ISSUE TITLE
Upload a custom svg, but see a empty icon

### ISSUE THREAD

**Issue by 4074** [fontello/fontello#687]
I upload some svg to custom icon on http://fontello.com/
But one of them is not work.
I can see the content on Chrome.
But on fontello, it looks like a empty icon.
Here is the failure svg:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 53.2 (72643) - https://sketchapp.com -->
    <title>arrow</title>
    <desc>Created with Sketch.</desc>
    <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <polygon id="Fill-1" fill="#000000" points="6 9 12 16 18 9"></polygon>
    </g>
</svg>
```

**Comment by puzrin** [comment]
You should see message with link to https://github.com/fontello/fontello/wiki/How-to-use-custom-images. Just follow it.

**Comment by 4074** [comment]
Thanks for your reply.
I known what's happen now. The `svg2ttf` not supports `polygon` tag. I should convert `polygon` to 'path'.
In my case:
```
<polygon id="Fill-1" fill="#000000" points="6 9 12 16 18 9"></polygon>
```
convert to
```
<path id="Fill-1" fill="#000000" d="M6 9 12 16 18 9z" />
```
After this, it work.

I think it is amazing if the `svg2ttf` can do this convertion, the project also belongs fontello.
