### ISSUE TITLE
The font generated is different from the svg uploaded (missing hole)

### ISSUE THREAD

**Issue by elenasal4** [fontello/fontello#689]
Hi all, I've tried to upload an svg (It's a path) but during the conversion the hole inside the svg got lost. It seems like it was filled. I've tried to invert the path direction but nothing changed. I have Windows 10 Pro, Version 1803, installation date 15/05/2018, build operating system 17134.765 . Tested on Chrome, Firefox and Edge. Any ideas on how to solve this problem? 
Thank for your help!
[218-visible.zip](https://github.com/fontello/fontello/files/3236175/218-visible.zip)
[fontello-652b3fdf.zip](https://github.com/fontello/fontello/files/3236176/fontello-652b3fdf.zip)
![SVG obtained by the font](https://user-images.githubusercontent.com/51192778/58620630-d975f580-82c7-11e9-94ff-a6f9f28ce928.png)

**Comment by puzrin** [comment]
You have wrong orientation if internal contour. I did split + substract in inscape, and everything works as needed.

[218-split-sub.svg.zip](https://github.com/fontello/fontello/files/3237135/218-split-diff.svg.zip)

**Comment by elenasal4** [comment]
Thank you very much @puzrin , your suggestion was very useful!
