### ISSUE TITLE
Fontello Website needs SSL/HTTPS

### ISSUE THREAD

**Issue by awakekat** [fontello/fontello#690]
Seems this VERY simple request has gone deaf and blind since March of 2016. It takes less than 10 minutes to do this.

**Comment by puzrin** [comment]
Closed as dupe of previous issues.

**Comment by awakekat** [comment]
Oh, so your website security doesn't mean much to you, ok gotcha! 😉

**Comment by puzrin** [comment]
Yes. Here are no secrets.

**Comment by AlexWayfer** [comment]
As I know, fonts are not secure completely: https://googleprojectzero.blogspot.com/2016/06/a-year-of-windows-kernel-font-fuzzing-1_27.html

And MITM attack can replace the content of files.

**Comment by xf-** [comment]
@puzrin Browser are starting to add warnings like a Icon for insecure websites
![image](https://user-images.githubusercontent.com/1295633/82227345-ec923300-9927-11ea-8dd5-a5a2f741357e.png)

Also you download a zip and some harmful stuff can be in a zip. Like @AlexWayfer wrote it is possible to replace content.

Please reconsider. Adding ssl with lets encrypt is easy and no additional coasts.

**Comment by puzrin** [comment]
@xf- your argument sounds reasonable, thanks. In general, this feature depends on my deployment process, related to other project. I nearest months i plan to migrate to new software/server, and this will be resolved automatically.

Note, i have nothing against https. By right now it would be very inconvenient to organaze it for fontello only. There are foreign reasons. Good news is that i have deadlines, an fontello should switch to https this year.

**Comment by puzrin** [comment]
FYI. Migrated to standalone VPS, with deploy via docker. How https.
