### ISSUE TITLE
Error [400] Bad Request with parameter in fontello.com url

### ISSUE THREAD

**Issue by strixy** [fontello/fontello#692]
I wanted to share fontello.com with my friends on Facebook and discovered that Facebook appends the fbclid parameter to the URL example

http://fontello.com/?fbclid=IwAR26V6wYydvgBaZyM1gtoSycmk3q90dTbcubwHVivdfs-pimX7u7Kn-vgOOI

Clicking on the link serves up a `[400] Bad Request` error.

I checked previous issues here, but I couldn't find any mention of it.

Steps to reproduce: click on the link above or append any parameter to the URL on the fontello.com site.

I'm using Chrome 76 on Linux

**Comment by AlexWayfer** [comment]
Reproduced by me.
