### ISSUE TITLE
Asset Load Error

### ISSUE THREAD

**Issue by antglenn** [fontello/fontello#693]
Hi, when trying to load the website I get the following alert error:

Asset load error (bag.js): Can't open url /assets/bundle-fontello.en-US-8d00df3b19b3af122a6a1161b1fd43fc.js

When navigating to that file: http://fontello.com/assets/bundle-fontello.en-US-8d00df3b19b3af122a6a1161b1fd43fc.js

It seems to take a fairly long time to actually download that in the browser, but the file does exist.

Any ideas?

**Comment by puzrin** [comment]
Try another provider or VPN. Download speed seems not fontello issue.

Or provide more details how to reproduce to reopen.
