### ISSUE TITLE
server:fontello.font.download event fired before font zipdata is written to disk

### ISSUE THREAD

**Issue by luchenatwork** [fontello/fontello#694]
browser: Chrome

os: Windows

step-by-step instruction:
Download google material icons from https://github.com/google/material-design-icons.
Import all svg icons, about 2000 svg files.
When export font using my local Fontello server, error returned as 404, not found.
When export font using Fontello.com, it works fine.

After debugging through the source code, find out api.download.js await N.wire.emit('server:fontello.font.download', env); is executed even before font_build.js finishes output zipdata to disk.

When reduce the total number of svg files to below 500, my local Fontello server works.

It looks like with large number of svg files, the font_build.js is not able to finish the output job before emit the download event.

By the way, thank you very much for the excellent work on Fontello server.

**Comment by puzrin** [comment]
Is this reproducible on fontello.com or linux OS (Windows WSL should be ok)? Can not say anything about Windows.
