### ISSUE TITLE
Importing SVG solid circle bug? 

### ISSUE THREAD

**Issue by jadevop** [fontello/fontello#699]
Importing SVG with perfect solid circles, the circles would not display. All other shapes are fine. Any thoughts?

**Comment by AlexWayfer** [comment]
Please, provide an example SVG file to import.

**Comment by jadevop** [comment]
Spoke too soon, seems like the issue somehow disappeared and or fixed. 

Tried importing a few weeks ago and every filled, perfect circle in a SVG would fail to display. Very odd.
