### ISSUE TITLE
Wrong icons in CSS file codes section

### ISSUE THREAD

**Issue by plagasul** [fontello/fontello#700]
I've downloaded a font with a selection of a few FontAwesome icons, and In the main css file, at the bottom, which is the codes section, some icons are wrong:

![image](https://user-images.githubusercontent.com/13966673/76703095-154f3f80-66cf-11ea-9263-cc14d5920343.png)

**Comment by puzrin** [comment]
Icons in text file depends on installed system fonts and not related to fontello.
