### ISSUE TITLE
Save config

### ISSUE THREAD

**Issue by simplenotezy** [fontello/fontello#701]
Currently when I navigate to fontello.com it remembers my set of icons. But what happens if I clear browser data, how can I get back this list of icons, so I can continuously add new? E.g. a way to manage my projects.

**Comment by daveloodts** [comment]
I would even yearly pay for such a service, saving Fontello profiles

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects
