### ISSUE TITLE
Problem with icons on mobile

### ISSUE THREAD

**Issue by MathiasDumoulin** [fontello/fontello#706]
Hello,

I have a weird problem with fontello's svg icons.

On desktop it works fine (except of course on IE...) but on mobile (safari/chrome) it doesn't work well.

Some icons are sometimes "full" on mobile...

I tested the svg without fontello in "mobile" mode and the svg works fine.

Can you help me ? Thx :)

**Original SVG**
[https://static.myskillcamp.com/icons-test/person.svg](https://static.myskillcamp.com/icons-test/person.svg)
[https://static.myskillcamp.com/icons-test/people.svg](https://static.myskillcamp.com/icons-test/people.svg)

**On desktop (good)**
[https://static.myskillcamp.com/icons-test/desktop.png](https://static.myskillcamp.com/icons-test/desktop.png)

**On mobile (bad)**
[https://static.myskillcamp.com/icons-test/mobile.jpg](https://static.myskillcamp.com/icons-test/mobile.jpg)

**Comment by AlexWayfer** [comment]
@MathiasDumoulin this is not an issue with Fontello, so, please, close this issue.

This is an issue with SVG. I suggest you to not use a simple line (or circle) for these elements, like "head", and use double lines (circles: outer and inner) for correct rendering. It's a bit more difficult, but can be done with a few clicks in some instrument like Adobe Illustrate or Inkscape, as I remember. And you can try to check the result in some tool like FontForge.

**Comment by puzrin** [comment]
Your SVG has `fill-rule="evenodd"`. There should be no any attributes. You should see warning on import, with link how to pepare single-path svg https://github.com/fontello/fontello/wiki/How-to-use-custom-images

Just prepare your image with proper contours orientation, and it will work.
