### ISSUE TITLE
fontello-cli install not download new set from site after session save

### ISSUE THREAD

**Issue by dotus-ru** [fontello/fontello#708]
When i perform **fontello-cli install** with config json, cli douwload only fonts in this config file. Then i perform **fontello-cli open**,  open site with selected icons. I select more icons, click 'save session', perform **fontello-cli install**, but new set not downloaded. After every edit set on site, i had to download new config, delete old font folder, change scss import, because new downloaded folder name has change. Why such complex logic is implemented instead of **fontello-cli open** , change set, save session,  **fontello-cli install** ...exists css and fonts updated

**Comment by puzrin** [comment]
`fontello-cli` is third party package, please ask auhor.
