### ISSUE TITLE
fontello site is down

### ISSUE THREAD

**Issue by Pranjalya** [fontello/fontello#710]
www.fontello.com loads and then fails to propagate with message
```
Asset load error: "N.Wire" unavailable after asset load.
```

**Comment by AlexWayfer** [comment]
> [www.fontello.com](http://www.fontello.com) loads and then fails to propagate with message
> 
> ```
> Asset load error: "N.Wire" unavailable after asset load.
> ```

I can't reproduce.

**Comment by puzrin** [comment]
ctrl + f5 should help
