### ISSUE TITLE
Feature request: Import Fontastic fonts

### ISSUE THREAD

**Issue by sebastian-65** [fontello/fontello#711]
Since I'd like to use Fontello for my older projects (using Fontastic), I would appreciate the easy way to import fonts made with Fontastic

**Comment by bencergazda** [comment]
@sebastian-65 Fontello can parse the content and configuration from any SVG icon font, just drop the font file to the Fontello editor.

**Comment by sebastian-65** [comment]
@bencergazda Oh, thank you for letting me know!
