### ISSUE TITLE
Corrupted Fonts

### ISSUE THREAD

**Issue by kushraj** [fontello/fontello#713]
I am importing some font-awesome svgs to convert which was fine until this week.
Lately glyphs are coming out corrupted and crooked somewhat. Some are fine, some invisible, and some are kind of crooked version of actual svgs.
On Site, they are being previewed fine, but on rendering on system, this problem arises.
Also the svg of combined fonts is also corrupted.

**Comment by kochai** [comment]
Yes, can confirm that all of the custom (uploaded) SVG icons are broken with generated css / font.

**Comment by puzrin** [comment]
Please provide your configs, an descriptions how to reproduce.

**Comment by kochai** [comment]
`{
  "name": "",
  "css_prefix_text": "icon-",
  "css_use_suffix": false,
  "hinting": true,
  "units_per_em": 1000,
  "ascent": 850,
  "glyphs": [
    {
      "uid": "019683ba7ab20271a85f0e35286f3424",
      "css": "prosumers-1",
      "code": 59392,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M691.6 531.5A284 284 0 1 0 418 531.5 566.5 566.5 0 0 0 0.3 967.9 26.9 26.9 0 1 0 53.1 978.7 511.4 511.4 0 0 1 1055.8 978.7 26.9 26.9 0 0 0 1082.2 1000.3 25.6 25.6 0 0 0 1087.6 999.7 26.9 26.9 0 0 0 1108.7 968 566.4 566.4 0 0 0 691.6 531.5ZM324.6 284A230.1 230.1 0 1 1 554.8 514.1 230.4 230.4 0 0 1 324.6 284Z",
        "width": 1109
      },
      "search": [
        "prosumers"
      ]
    },
    {
      "uid": "92b557c41c916d2ea8ebe4c0eac1a7cb",
      "css": "devices-1",
      "code": 59409,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M500 0A500 500 0 1 0 1000.1 500 499.6 499.6 0 0 0 500 0ZM500 941.5A441.5 441.5 0 1 1 941.5 500 442.9 442.9 0 0 1 500 941.5ZM500 119.2A380.7 380.7 0 0 0 228.6 766.9 29.3 29.3 0 0 0 272.3 769.2L272.6 768.9 355 686.4A29.3 29.3 0 0 0 313.6 645L252.4 706.1A319.4 319.4 0 0 1 179 529.2H265.7A29.3 29.3 0 1 0 265.7 470.6H179.1A320.8 320.8 0 0 1 252.4 293.8L313.6 354.9A29.3 29.3 0 0 0 355 313.5L293.9 252.4A320.7 320.7 0 0 1 470.7 179V265.7A29.3 29.3 0 1 0 529.3 265.7V179.1A320.8 320.8 0 0 1 706.1 252.4L645 313.6A29.3 29.3 0 1 0 686.5 355L747.7 293.9A320.7 320.7 0 0 1 821 470.7H734.4A29.3 29.3 0 1 0 734.4 529.3H820.9A319.4 319.4 0 0 1 747.7 706.2L686.6 645.1A29.3 29.3 0 1 0 645.1 686.5L727.5 769.2 727.5 769.5A29.3 29.3 0 0 0 771.1 767.3 380.7 380.7 0 0 0 500 119.2ZM595 389.4A29.3 29.3 0 0 0 553.5 389.4L522.3 420.7A87.9 87.9 0 1 0 572.3 500 86.6 86.6 0 0 0 563.7 462.3L595 431.1A29.4 29.4 0 0 0 595 389.4ZM484.4 529.4A29.3 29.3 0 1 1 513.7 500 29.3 29.3 0 0 1 484.4 529.3ZM587.9 763.8H412.2A29.3 29.3 0 0 0 412.2 822.4H587.9A29.3 29.3 0 0 0 587.9 763.8Z",
        "width": 1000
      },
      "search": [
        "devices"
      ]
    },
    {
      "uid": "755bb2edf2a037cc9d8ac6ba0193a0ee",
      "css": "agreements-1",
      "code": 59394,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M984.9 785.6A509.2 509.2 0 0 1 839.8 649.8 31.2 31.2 0 1 0 789.5 686.8 602.3 602.3 0 0 0 895.8 799.2L380.2 934.9C164.3 795.1 76.8 467.9 63.5 211.4L595.4 71.2A1547.3 1547.3 0 0 0 624.6 287.8 31.2 31.2 0 0 0 685.8 275 1418.3 1418.3 0 0 1 656 31 31.2 31.2 0 0 0 616.8 1.1L23.3 157.3A31.2 31.2 0 0 0 0 187.9 1480.6 1480.6 0 0 0 46.2 509C95.3 699.9 189 892.4 358.7 995.4A31.2 31.2 0 0 0 374.9 999.9C381.2 999.9 341 1009.9 976.6 842.7A31.2 31.2 0 0 0 984.9 785.6ZM312.5 718.7A1585 1585 0 0 0 509.8 654.6 31.2 31.2 0 1 0 490.1 595.3L302.7 657.8A31.2 31.2 0 0 0 312.5 718.7ZM593.4 677.2A107.7 107.7 0 0 0 512.8 693.3C465.2 727.6 474.8 781.2 406 781.2A31.2 31.2 0 1 0 406 843.5C509.1 843.5 523.1 762.7 549.3 743.9A73.3 73.3 0 0 1 611.6 746.9 31.2 31.2 0 0 0 637.6 746.9 546.1 546.1 0 0 0 777.8 617.5 470.6 470.6 0 0 0 874.2 244.7 31.2 31.2 0 0 0 829.4 221.8C666.1 303.7 599.3 493.6 593.4 677.2ZM818 301.6A432 432 0 0 1 657 654.7C665.7 522.5 708.9 378.5 818 301.6ZM257.8 593.5A1457.6 1457.6 0 0 0 509.8 520 31.2 31.2 0 1 0 490.1 460.7L247.9 532.8A31.2 31.2 0 0 0 257.8 593.7ZM247.8 427.3A92.7 92.7 0 1 1 340.6 334.5 92.8 92.8 0 0 1 247.8 427.3ZM247.8 293.8A40.8 40.8 0 1 0 288.6 334.6 40.9 40.9 0 0 0 247.8 293.7Z",
        "width": 1000
      },
      "search": [
        "agreements"
      ]
    },
    {
      "uid": "50bee8ff0b268d80bf9fc5340b605e5f",
      "css": "traders-1",
      "code": 59393,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M691.6 531.5A284 284 0 1 0 418 531.5 566.5 566.5 0 0 0 0.3 967.9 26.9 26.9 0 1 0 53.1 978.7 512.5 512.5 0 0 1 473.4 575.1 90.3 90.3 0 0 0 494.1 687.2L453.8 922.4 477.5 983.2A26.9 26.9 0 0 0 527.7 963.7L509.5 916.9 545 709.4A93.2 93.2 0 0 0 554.6 710.3 91.3 91.3 0 0 0 567.9 709L603.5 916.9 585.3 963.7A26.9 26.9 0 0 0 600.6 998.5 26.9 26.9 0 0 0 635.5 983.2L659.1 922.4 618.3 684.4A90.6 90.6 0 0 0 636.1 574.6 512.3 512.3 0 0 1 1056.4 978.1 26.9 26.9 0 0 0 1082.7 999.7 25.6 25.6 0 0 0 1088.1 999.1 26.9 26.9 0 0 0 1109.3 967.5 566.2 566.2 0 0 0 691.6 531.5ZM324.6 284A230.1 230.1 0 1 1 554.8 514.1 230.4 230.4 0 0 1 324.6 284ZM516.4 617.7A38.4 38.4 0 1 1 554.8 656.1 38.4 38.4 0 0 1 516.4 617.7Z",
        "width": 1109
      },
      "search": [
        "traders"
      ]
    },
    {
      "uid": "fd7eef8a400e912ba8506048399fe40d",
      "css": "delete-1",
      "code": 59396,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M663.5 419.1L568.1 417 547.4 764 642.8 766.2ZM384.6 763.9L363.8 416.9 268.4 419.1 289.1 766.1ZM0 183.1V258.4H81.4L146.2 965.7A38.6 38.6 0 0 0 185.2 1000H745.4A38.6 38.6 0 0 0 784.4 965.7L849.1 258.4H932.2V183.1ZM709.5 924.9H221.3L160.3 258.6H770.6ZM622.1 0H310.1A79.7 79.7 0 0 0 230.5 79.6V230.8H326V95.2H606.2V230.8H701.7V79.6A79.7 79.7 0 0 0 622.1 0Z",
        "width": 932
      },
      "search": [
        "delete"
      ]
    },
    {
      "uid": "9dd9e835aebe1060ba7190ad2b2ed951",
      "css": "search",
      "code": 59401,
      "src": "fontawesome"
    },
    {
      "uid": "8663320a860b00f26e94d3d15c9ba99a",
      "css": "clock",
      "code": 59402,
      "src": "entypo"
    },
    {
      "uid": "76fa76eb3472394c9937f7c7734f77b2",
      "css": "key",
      "code": 59398,
      "src": "iconic"
    },
    {
      "uid": "c5fd349cbd3d23e4ade333789c29c729",
      "css": "eye",
      "code": 59399,
      "src": "fontawesome"
    },
    {
      "uid": "0d08dbb1dd648a43bdea81b7e6c9e036",
      "css": "location",
      "code": 59397,
      "src": "fontawesome"
    },
    {
      "uid": "1cf8db366bf3c11b1606cd4e786e2310",
      "css": "attach-1",
      "code": 59395,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M312.5 1000A312.8 312.8 0 0 1 0 687.5V250A41.7 41.7 0 0 1 83.4 250V687.5A229.2 229.2 0 1 0 541.7 687.5V229.2A145.8 145.8 0 0 0 250.1 229.2V645.8A62.5 62.5 0 1 0 375 645.8V250A41.7 41.7 0 0 1 458.4 250V645.8A145.8 145.8 0 0 1 166.7 645.8V229.2A229.2 229.2 0 0 1 625.1 229.2V687.5A312.8 312.8 0 0 1 312.5 1000ZM312.5 1000",
        "width": 625
      },
      "search": [
        "attach"
      ]
    },
    {
      "uid": "47871a5c465d1bb0714fd0278e3f074b",
      "css": "word-1",
      "code": 59400,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M1033.3 133.4H599.9V33.4A33.3 33.3 0 0 0 587.9 7.7 32.7 32.7 0 0 0 560.5 0.6L27.2 100.7A33.3 33.3 0 0 0 0 133.4V866.7A33.3 33.3 0 0 0 27.2 899.4L560.5 999.4A31.4 31.4 0 0 0 566.6 1000.1 33.3 33.3 0 0 0 599.9 966.7V866.7H1033.3A33.4 33.4 0 0 0 1066.6 833.4V166.7A33.4 33.4 0 0 0 1033.3 133.4ZM466.4 370.3L433.1 670.4A33.4 33.4 0 0 1 404.1 699.8 28.7 28.7 0 0 1 400 700 33.4 33.4 0 0 1 368.8 678.5L300 494.9 231.2 678.5A33.3 33.3 0 0 1 167 671.4L133.9 438.2A33.3 33.3 0 0 1 199.9 428.8L214.8 533.1 269 388.5A34.8 34.8 0 0 1 331.4 388.5L382.5 524.6 400.4 363.1A33.3 33.3 0 0 1 466.7 370.6ZM999.9 800H599.9V733.3H899.9A33.3 33.3 0 0 0 899.9 666.7H599.9V600H899.9A33.3 33.3 0 0 0 899.9 533.4H599.9V466.7H899.9A33.3 33.3 0 0 0 899.9 400H599.9V333.4H899.9A33.3 33.3 0 0 0 899.9 266.7H599.9V200.1H999.9Z",
        "width": 1067
      },
      "search": [
        "word"
      ]
    },
    {
      "uid": "467eba02b452664a1826c10e4a97c936",
      "css": "edit-1",
      "code": 59410,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M968.9 121.7L878.2 30.8A106.3 106.3 0 0 0 728.1 30.8L53.9 705.3A29.8 29.8 0 0 0 45.8 720.7L0.5 965.4A29.3 29.3 0 0 0 34.6 999.5L279.3 954.2A29.8 29.8 0 0 0 294.6 946.1L968.9 271.9A106.2 106.2 0 0 0 968.9 121.7ZM65.8 934.2L93.3 786.2 213.9 906.8ZM273.9 884L116 726 692.6 149.4 850.8 307.3ZM927.4 230.5L892 265.9 734 108 769.5 72.5A47.7 47.7 0 0 1 836.8 72.5L927.4 163.1A47.6 47.6 0 0 1 927.4 230.5Z",
        "width": 1000
      },
      "search": [
        "edit"
      ]
    },
    {
      "uid": "b27f682b7c77b0d9687c6366869c83fb",
      "css": "pdf-1",
      "code": 59403,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M263.7 455.4A731.5 731.5 0 0 1 229.3 537.8C222.4 551.5 215.6 561.7 208.7 575.5H215.4A516.5 516.5 0 0 1 328.6 544.6 48.9 48.9 0 0 1 314.9 534.3 363.2 363.2 0 0 1 263.7 455.4ZM267.3 345.5V338.7A55.4 55.4 0 0 0 267.3 304.3V301L263.9 297.7A3.2 3.2 0 0 1 260.6 301 139.8 139.8 0 0 0 260.6 376.6 141.8 141.8 0 0 0 267.3 345.5ZM95.4 678.7C116 675.4 136.6 654.8 157.2 613.5A72.1 72.1 0 0 0 140.1 623.8 169 169 0 0 0 95.4 678.7ZM473.3 561.9C469.9 558.5 456.2 548.1 408.1 548.1H401.2V551.5A185.8 185.8 0 0 0 466.4 568.6H476.7V565.2A3 3 0 0 1 473.3 561.9ZM1033.3 133.4H599.9V33.4A33.4 33.4 0 0 0 560.3 0.7L27.1 100.7A33.3 33.3 0 0 0 0 133.4V866.6A33.3 33.3 0 0 0 27.3 899.3L560.6 999.4A31.4 31.4 0 0 0 566.4 999.9 33.4 33.4 0 0 0 599.7 966.6V866.6H1033A33.4 33.4 0 0 0 1066.3 833.3V166.7A33.4 33.4 0 0 0 1033.3 133.4ZM487 589.4A69.6 69.6 0 0 1 456.1 596.3 249.2 249.2 0 0 1 353.2 572.3 567 567 0 0 0 215.7 599.8C212.3 599.8 212.3 599.8 208.8 603.2 167.6 675.3 133.1 709.7 105.8 709.7 98.9 709.7 95.5 709.7 92.1 706.3L75 696V692.7A31.5 31.5 0 0 1 71.6 675.6 131.4 131.4 0 0 1 136.8 603.5C143.7 600.1 153.9 593.2 167.7 586.4 178 569.3 188.3 548.7 202.1 524.6A730 730 0 0 0 239.8 425 159.3 159.3 0 0 1 232.9 311.8C236.2 298 246.6 284.3 260.4 284.3H267.3A47.5 47.5 0 0 1 287.9 291.2C311.8 315.1 301.6 370.1 287.9 414.7V418.1A249.2 249.2 0 0 0 342.9 507.5 232.5 232.5 0 0 0 373.8 528.1C390.8 528.1 404.6 524.7 418.3 524.7 459.5 524.7 487.1 531.6 497.3 548.7A44.8 44.8 0 0 1 500.6 569.3 170.5 170.5 0 0 1 487 589.4ZM999.9 800H599.9V733.3H899.9A33.3 33.3 0 0 0 899.9 666.7H599.9V600H899.9A33.3 33.3 0 0 0 899.9 533.3H599.9V466.7H899.9A33.3 33.3 0 0 0 899.9 400H599.9V333.3H899.9A33.3 33.3 0 0 0 899.9 266.7H599.9V200H999.9Z",
        "width": 1067
      },
      "search": [
        "pdf"
      ]
    },
    {
      "uid": "89efc1bf1dc4f1a381b88fe4ac718126",
      "css": "agreement-1",
      "code": 59406,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M984.9 785.7A509.2 509.2 0 0 1 839.8 649.9 31.2 31.2 0 1 0 789.5 686.9 602 602 0 0 0 895.8 799.2L380.2 934.9C164.3 795.1 76.8 467.9 63.5 211.4L595.4 71.4A1547.3 1547.3 0 0 0 624.8 287.8 31.2 31.2 0 1 0 685.9 275 1418.3 1418.3 0 0 1 656.2 31 31.3 31.3 0 0 0 617 1L23.3 157.3A31.3 31.3 0 0 0 0 187.8 1480.6 1480.6 0 0 0 46.2 508.9C95.3 699.9 188.9 892.3 358.7 995.4A31 31 0 0 0 374.9 999.9C381.2 999.9 341 1009.8 976.6 842.6A31.2 31.2 0 0 0 984.9 785.7ZM312.5 718.7C319.6 718.7 305.1 722.9 509.9 654.6A31.2 31.2 0 1 0 490.2 595.3L302.7 657.8A31.3 31.3 0 0 0 312.6 718.7ZM593.7 677.2A107.7 107.7 0 0 0 513 693.3C465.4 727.5 475 781.2 406.3 781.2A31.3 31.3 0 1 0 406.3 843.7C509.3 843.7 523.3 762.9 549.5 744.1 565.1 732.9 595.6 739.6 611.9 747.1A31.1 31.1 0 0 0 638 747.1 546.1 546.1 0 0 0 778.1 617.7 470.7 470.7 0 0 0 874.6 244.8 31.3 31.3 0 0 0 829.8 222C666.1 303.6 599.3 493.6 593.7 677.2ZM818.2 301.6C826.5 441.9 761.3 564.5 657.4 654.9 666 522.7 709.5 378.6 818.2 301.6ZM257.8 593.7C264.9 593.7 305 588.4 509.9 520.2A31.2 31.2 0 0 0 490.1 460.9L247.9 532.8A31.3 31.3 0 0 0 257.8 593.7ZM247.8 427.3A92.7 92.7 0 1 1 340.6 334.5 92.9 92.9 0 0 1 247.8 427.3ZM247.8 293.7A40.7 40.7 0 1 0 288.6 334.5 40.9 40.9 0 0 0 247.8 293.7Z",
        "width": 1000
      },
      "search": [
        "agreement"
      ]
    },
    {
      "uid": "0dfa4e21e2a486965ff5032016346276",
      "css": "device-1",
      "code": 59405,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M500 0A500 500 0 1 0 1000.1 500 499.6 499.6 0 0 0 500 0ZM500 941.4A441.4 441.4 0 1 1 941.4 500 442.9 442.9 0 0 1 500 941.4ZM500 119.2A380.6 380.6 0 0 0 228.7 767 29.3 29.3 0 0 0 272.3 769.2C272.4 769.1 272.5 769 272.6 768.9L355.1 686.4A29.3 29.3 0 1 0 313.7 645L252.5 706.2A319.4 319.4 0 0 1 179.1 529.4H265.7A29.3 29.3 0 1 0 265.7 470.8H179.1A320.8 320.8 0 0 1 252.5 294L313.7 355.2A29.3 29.3 0 1 0 355.1 313.8L293.9 252.8A320.7 320.7 0 0 1 470.7 179.4V266A29.3 29.3 0 1 0 529.2 266V179.1A320.8 320.8 0 0 1 706 252.5L644.9 313.7A29.3 29.3 0 1 0 686.2 355.1L747.4 293.9A320.7 320.7 0 0 1 820.8 470.7H734.4A29.3 29.3 0 0 0 734.4 529.2H820.9A319.4 319.4 0 0 1 747.6 706.1L686.4 644.9A29.3 29.3 0 0 0 645 686.3L727.5 768.8C727.6 768.9 727.6 769 727.8 769.1A29.3 29.3 0 0 0 771.4 766.8 380.7 380.7 0 0 0 500 119ZM595 389.4A29.3 29.3 0 0 0 553.6 389.4L522.3 420.7A87.9 87.9 0 1 0 572.3 500 86.6 86.6 0 0 0 563.7 462.2L595 430.9A29.4 29.4 0 0 0 595 389.4ZM484.4 529.3A29.3 29.3 0 1 1 513.7 500 29.3 29.3 0 0 1 484.4 529.3ZM587.9 763.8H412.2A29.3 29.3 0 0 0 412.2 822.3H587.9A29.3 29.3 0 0 0 587.9 763.8Z",
        "width": 1000
      },
      "search": [
        "device"
      ]
    },
    {
      "uid": "9b5d94e5011673ce1f30b51b8d117119",
      "css": "prosumer-1",
      "code": 59408,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M691.6 531.3A284 284 0 1 0 418 531.3 566.5 566.5 0 0 0 0.5 967.7 26.9 26.9 0 1 0 53.3 978.4 511.5 511.5 0 0 1 1056.1 978.4 26.9 26.9 0 0 0 1082.4 1000.1 25.6 25.6 0 0 0 1087.8 999.5 26.9 26.9 0 0 0 1109 967.9 566.3 566.3 0 0 0 691.6 531.3ZM324.6 284A230.1 230.1 0 1 1 554.8 514.1 230.4 230.4 0 0 1 324.6 284Z",
        "width": 1109
      },
      "search": [
        "prosumer"
      ]
    },
    {
      "uid": "71605d4865e995125342ec3e11f6aa85",
      "css": "next",
      "code": 59404,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M10.8 527.4L452.6 989.1A35.7 35.7 0 0 0 504.6 988.2 39.7 39.7 0 0 0 504.6 934.8L88.9 500 504.6 65.4A39.7 39.7 0 0 0 504.6 11 35.7 35.7 0 0 0 452.6 11L10.8 472.8A39.7 39.7 0 0 0 10.8 527.4Z",
        "width": 515
      },
      "search": [
        "next"
      ]
    }
  ]
}`

Try the example above. Some icons are offset from the center, in the preview mode (selecting icons) all of them are centered properly within the container.

Once you download the webfont, some of the icons are moved down the Y axis, which was not the case before I generated new icons today.

**Comment by sergeylukin** [comment]
+1

Could reproduce it using standard Font Awesome icons as well (icons are broken on Windows while looking good on OS X).
Steps to reproduce:

Visit https://fontello.com
Import following configuration:

```json
{
  "name": "",
  "css_prefix_text": "icon-",
  "css_use_suffix": false,
  "hinting": true,
  "units_per_em": 1000,
  "ascent": 850,
  "glyphs": [
    {
      "uid": "0ddd3e8201ccc7d41f7b7c9d27eca6c1",
      "css": "link",
      "code": 128279,
      "src": "fontawesome"
    }
  ]
}
```

Open demo.html in the browser and check out the link icon.

Current Result:

<img width="33" alt="Screen Shot 2020-10-18 at 13 37 58" src="https://user-images.githubusercontent.com/720339/96365153-39806c80-1147-11eb-947d-97b852a82dee.png">


Expected:

<img width="24" alt="Screen Shot 2020-10-18 at 13 38 11" src="https://user-images.githubusercontent.com/720339/96365146-32595e80-1147-11eb-9916-f036f64db353.png">

Currently we're forced to avoid generating icons using fontello until this bug is fixed.

**Comment by kalamun** [comment]
+1
Same issue here, with self-designed SVGs.

**Comment by puzrin** [comment]
Temporary reverted one buggy commit. Seems provided samples are not distorted anymore.

Sorry for inconvenience. Will close issue when final fix ready.

**Comment by marioese31** [comment]
Hi, I just tested uploading a custom svg to fontello.com after your update from 2 hours ago but unfortunately it still shows incorrectly (as described above).

The weird thing is this only seems to happen in Windows (10 both pro and enterprise) while on my Mac everything seems fine, even when I transfer the zip generated on my Windows machine to my Mac.

My config.json:
`{
  "name": "",
  "css_prefix_text": "icon-",
  "css_use_suffix": false,
  "hinting": true,
  "units_per_em": 1000,
  "ascent": 850,
  "glyphs": [
    {
      "uid": "39a1163dc8c4a66e38acc7d67017f966",
      "css": "checkbox-checked",
      "code": 59392,
      "src": "custom_icons",
      "selected": true,
      "svg": {
        "path": "M888.7 0H111.3A111.3 111.3 0 0 0 0 111V888.7A111.3 111.3 0 0 0 111.3 1000H888.7A111.3 111.3 0 0 0 1000 888.7V111A111.3 111.3 0 0 0 888.7 0ZM388.7 777.7L111.3 500 189.7 421.7 389.7 621.7 810.3 200 888.7 278.7Z",
        "width": 1000
      },
      "search": [
        "checkbox-checked"
      ]
    }
  ]
}`

**Comment by kalamun** [comment]
Unfortunately the issue persist for me too (W10 + Firefox).
In Fontello I can see all the icons well before exporting, but once exported they look corrupted.

**Comment by masoudelahi** [comment]
I have the same problem

**Comment by Fullbusters** [comment]
I have the same issue with today's generated icons but last week the same icons look good

**Comment by ItaloFSS** [comment]
I'm also having this issue. The icons look great on a Mac, distorted on Windows 10.

Thanks,
Italo

**Comment by sergeylukin** [comment]
> Temporary reverted one buggy commit. Seems provided samples are not distorted anymore.
> 
> Sorry for inconvenience. Will close issue when final fix ready.

I'm getting same result (corrupted) by following steps to reproduce I've mentioned in my last comment. Please advise.

**Comment by guillome2k** [comment]
Same problems here, see my other topic (sorry for that)

**Comment by BrandesEric** [comment]
Same problems here

**Comment by puzrin** [comment]
Temporary reverted svg2tf to v4.x. Is anything changed on windows?

**Comment by ItaloFSS** [comment]
It did not fix the issue. I even tried "Reset all changes" and cleared the browser data in Chrome.

**Comment by saenzjuan** [comment]
The issue persists on Android, the icons are corrupted. On iOS works fine.

**Comment by yuratehnik** [comment]
The same problem, on windows server 2016 and windows 10 yesterday generated icons became broken

**Comment by puzrin** [comment]
Found! Problem is caused by upgraded `ttfautohint` version (if disable hinting in settings - works).

We need to test different versions, and i will deploy fix soon.

**Comment by ItaloFSS** [comment]
Disabling hinting did the trick! 

Thank you very much!!!

**Comment by guillome2k** [comment]
Lovely! Thank you!

**Comment by marioese31** [comment]
That's great, thanks for looking into it and keep up the good work! 🙏

**Comment by puzrin** [comment]
Problems with building tfautohint 1.1 on new OS (crash), uUbuntu 12.04 is not supported anymore.

Temporary forced hinting disable on server. A least, now fonts should work without need to change settings. Will enable hinting back when find solution.

**Comment by puzrin** [comment]
@lemzwerg could you take a look? ttfautohint breaks some characters if `--windows-compatibility` option used:

```
./ttfautohint.exe --no-info --windows-compatibility --symbol --fallback-script=latn ./unhinted.ttf ./fontello.ttf
```

On old server we used some pre-1.1 version, that worked. On new server, all builds from 1.1 to 1.8.x give broken result (we quick-tried all windows builds an last linux buils).

See attached demos with both hinted an unhinted sources:

[demo.tar.gz](https://github.com/fontello/fontello/files/5422472/demo.tar.gz)

**Comment by lemzwerg** [comment]
This is most certainly a bug in ttfautohint, probably triggered by the fact that it there are no other blue zones in the font except the artificial ones added by `--windows-compatibility`.  Thanks for the report.

Note, however, that `--windows-compatibility` makes no sense for a dingbats font.  As a quick fix I thus suggest to always disable this option for non-latin fonts.  Additionally, I think that you can safely drop the option for latin fonts, too: AFAIK, Windows no longer cuts off glyphs at the top and the bottom.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/commit/46f6de21abfa2a2ab3ff6eae58375179e951cf2e

@lemzwerg thanks! Do we still need `--fallback-script=latn` or it can be dropped too? It was added many years ago as workaround of something https://github.com/fontello/fontello/issues/464#issuecomment-202244651

**Comment by lemzwerg** [comment]
Well, if you get better results you can leave it :-)

**Comment by puzrin** [comment]
Deployed final update (now from master@HEAD)

Please, confirm reportet bug gone, or something more required.
