### ISSUE TITLE
Icon Name and Code are Changing

### ISSUE THREAD

**Issue by ItaloFSS** [fontello/fontello#714]
We have been using Fontello for a while now, is a great tool. Yesterday, 10/16/2020, I tried importing a config file into Fontello and noticed that "-1" were being appended to several names during the import, also the code of several icons were being changed. Not sure what is happening. If you import the attached config file, you will notice that not all icons match the config file.

Thanks!

[config.zip](https://github.com/fontello/fontello/files/5395788/config.zip)

**Comment by puzrin** [comment]
Reproduced. Seems a bug. I certainly did not touched relaed part of code, and don't know why nobody reported problem before.

**Comment by ItaloFSS** [comment]
Looks like this bug is happening when you rename an icon to any name already used by Fontello.

1. Goto Fontello
2. Start a new session
3. Select the first icon in Font Awesome, the glass
4. Rename the icon to alert
5. Refresh the page, notice that the icon will now be renamed to "alert-1"

Thanks!

**Comment by nikwins** [comment]
I have the same problem, imported the config file, checked the icon names and all got a "-1" attached. I manually deleted all those attachments and downloaded the icon files. Then there accured another bug, now all my icons that are below ~20px size, are not properly shown.
I tried multiple browsers - Chrome, Firefox & Edge, all had the same problems.

**Comment by kalamun** [comment]
+1
Same issue for me, first time I managed to see it was like a week ago.
Not only names, but also icon codes are changing: this is making unusable the config import in order to modify a previously created icon set.

**Comment by ABPSoft** [comment]
I have this problem.
I imported my config.json to the Fontello.
And -1 add for all icon names!

**Comment by francoismassart** [comment]
Sorry for the dupe @puzrin

**Comment by oasit** [comment]
Same here.
All custom glyphs uploaded as SVG get a "-1" postfix. Uploading the config again increases the postfix by one.

**Comment by puzrin** [comment]
Temporary reverted breaking commit. Sorry for inconvenience.

**Comment by ItaloFSS** [comment]
Thanks for the quick fix. The name and code seems to have been fixed. However, some of the icons are not properly showing. 

Example: This is how the Fontawesome alert is showing.
![image](https://user-images.githubusercontent.com/130403/96498110-a5330a00-1219-11eb-990f-1dde1f95945b.png)

**Comment by puzrin** [comment]
I can not reproduce. There is second issue about icons. Please post detailed description there, how to reproduce.

Also, do `settings` -> `reset all changes`

**Comment by francoismassart** [comment]
Personally I always use a private browser window for fontello prior to dropping the `config.json` file on the webpage. This ensures me to start clean and my co-workers must do the same. Our `config.json` file is versioned and up-to-date.

**Comment by ItaloFSS** [comment]
I did Settings -> Reset all changes, also cleared all browsing data. Attached is the result of a new session, picking only the Fontawesome bell-alt icon. 

[fontello-357d9b39.zip](https://github.com/fontello/fontello/files/5404216/fontello-357d9b39.zip)

**Comment by puzrin** [comment]
@ItaloFSS demo looks ok in Ubuntu 18.04 FF & Chrome.

**Comment by ItaloFSS** [comment]
Strange, this is what I see. Tried Firefox, Edge, Chrome.

![image](https://user-images.githubusercontent.com/130403/96516852-dae5ec00-1235-11eb-884f-59dd18023f6e.png)

Thanks!

**Comment by puzrin** [comment]
@ItaloFSS please, use #713 to post info about glyphs, if you have something new.

**Comment by ItaloFSS** [comment]
The changing name and code have been fixed. Will post the icon issue to #713 

Thanks!

**Comment by masoudelahi** [comment]
How long will it take to fix the bug?

**Comment by puzrin** [comment]
I hope 1-2 days. We postponed everything and  working on this. Sorry again.

**Comment by puzrin** [comment]
Deployed final update (now from master@HEAD)

Please, confirm reportet bug gone, or something more required.

**Comment by ItaloFSS** [comment]
I can confirm that I'm not seeing the bug anymore. The issue has been fixed.

Thanks!
