### ISSUE TITLE
Any way to "compress" glyph ranges?

### ISSUE THREAD

**Issue by baboongd** [fontello/fontello#715]
Im using generated fonts with desktop application as "icon" font that is being merged into the main font, 
and i have to specify glyph ranges manually, however the generated fonts glyphs are all over the place
would be real nice if i could get a compressed version where the glyphs are laid out from a specified start index sequentially.
Im currently writing a tool to parse the the config and convert it to ranges, but i would rather just specify a start/start+count 
instead.

**Comment by baboongd** [comment]
Yeah however if you will implement such feature would be nice to have a stable sorting, so that between edits the config positioning of already existing icons would not change, and newly added icons would just be appended to end.

**Comment by puzrin** [comment]
Seings -> Encoding -> PUA. Is it what you need

**Comment by baboongd** [comment]
I don't understand yet, as PUA/Unicode outputs the same config.
I also noticed that while fontdrop.info says

usFirstCharIndex
    8646
usLastCharIndex
    65535

The codes in the config jump to 128000, what am i missing? Im expecting ushort 65k max, or `code` in config is not refering to the actual glyph index?
