### ISSUE TITLE
POST http://fontello.com gives 301 to https version which breaks webpack plugin

### ISSUE THREAD

**Issue by hjri** [fontello/fontello#716]
```curl -X POST http://fontello.com/ -F config=@static/fontello.json``` gives 301
```curl -X POST https://fontello.com/ -F config=@static/fontello.json``` works as intended

unfortunately redirect forgets method/data and gives index.html instead. some tools like https://github.com/w3geo/fontello-webpack-plugin default to http version

**Comment by puzrin** [comment]
Hm... i could set 308 redirect, but not sure node client & curl support it https://stackoverflow.com/a/48874271/1031804.

IMO the best was is to update URL to https.

PS. I certaintly need upadate URL-s in documenation & samples.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/commit/fbbaefa09cc1e20cd25a2b4ce02a8f0101070f2d

**Comment by puzrin** [comment]
I did this things:

- created PR to your plugin
- created pinned issue.

Also, seems your plugin has undocumened option `host`, and you can override it.

IMO nothing can be added in scope of this issue.
