### ISSUE TITLE
Damaged icons after downloading webfont

### ISSUE THREAD

**Issue by aaronshahi** [fontello/fontello#717]
After downloading the webfont package, the icons are damaged and broken in the demo file. Therefore, they do not work on my website.
I have this theme that comes with a fontello pack which works well but I need a few more custom icons. But when I download the config and import it, even without adding customs, when I download the same package just to test, the originally well package becomes damaged.

**Comment by puzrin** [comment]
#713, please don'r duplicae issues, provide details how to reproduce instead
