### ISSUE TITLE
Problems Downloading Webfont - "Communication problems. Try again later."

### ISSUE THREAD

**Issue by roddeo** [fontello/fontello#718]
I'm trying to download a small icon font (4 icons) and getting an error message: "Communication problems. Try again later." Not sure what the issue is exactly, whether it's something I'm doing wrong.

I'm using Chrome on a Mac with Catalina 10.15.7  - hoping you can help! 

Thanks!

**Comment by CPlusAK** [comment]
I got the same problem. Please help us to fix soon. Thank you.

**Comment by mkhalidnoor** [comment]
Getting this error **413 Request Entity Too Large**

**Comment by puzrin** [comment]
Did you tried Ctrl+F5? May be you have old assets in browser cache.

**Comment by puzrin** [comment]
@mkhalidnoor in download dropdown, click "download config only", zip, and post it in new issue

**Comment by chaiezerzer** [comment]
I got the same problem...!!  I get "Communication problems" when trying to download webfont ???
Using Chrome on a Mac with Catalina 10.15.7

Thanks...

**Comment by chaiezerzer** [comment]
The problem started once I upgraded from Mojave to Catalina OS ???

**Comment by kcondic** [comment]
Same problem for me, but I'm on Windows using Firefox/Chrome. One font works normally, the other one doesn't work through website nor through CLI, can't download anything except config.

**Comment by puzrin** [comment]
Please post zipped config, need description how to reproduce.

**Comment by kcondic** [comment]
[config.zip](https://github.com/fontello/fontello/files/5422204/config.zip)

Here it is. fontello-cli open does nothing, install only creates css and font folders without anything inside.

Web download gives 'Communication problems' message.

The same font (this exact config file) worked a couple of weeks ago for sure.

**Comment by chaiezerzer** [comment]
[config.json.zip](https://github.com/fontello/fontello/files/5422216/config.json.zip)
thanks

**Comment by mkhalidnoor** [comment]
Everything was working earlier, suddenly started getting this error **413 Request Entity Too Large**, Here is the config file
[config.zip](https://github.com/fontello/fontello/files/5422320/config.zip)

**Comment by chaiezerzer** [comment]
Thanks...
It's working fine now !!
have a Gr8 day

**Comment by kcondic** [comment]
Working for me also now, thanks.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/commit/27e51e92684d1bd4f628716920e4cf7810afaee4

Fixed. Thanks for your help.
