### ISSUE TITLE
Character codes should be kept untouched when importing SVG fonts

### ISSUE THREAD

**Issue by bencergazda** [fontello/fontello#721]
When dropping an existing SVG font file to Fontello (eg. an old Fontastic.me output), the character codes of the glyphs get parsed correctly, but Fontello may silently update the character codes when enabling the glyphs, making them start with \E800. In order to create a backward-compatible font, we should note the correct code before enabling the glyph, and write back after enabling.

After importing the SVG font
![image](https://user-images.githubusercontent.com/5767697/96902423-cbb0a980-1494-11eb-9ad1-eaf911054716.png)

After activating the glyph
![image](https://user-images.githubusercontent.com/5767697/96902450-d408e480-1494-11eb-9525-c9bf23d73721.png)

(Relates to #711)

**Comment by puzrin** [comment]
That's not a bug. You need to set `settings -> encoding -> unicode` to force keep defalt code on select when possible.

**Comment by bencergazda** [comment]
Thank you very much for letting me know this.

**Comment by puzrin** [comment]
No problem. May be wiki/interface are not ideal if you could not recognize that without help. If you have ideas how to improve - let me know.

**Comment by bencergazda** [comment]
@puzrin I've been using Fontello for about three years, on a weekly/monthly basis. I just didn't notice the Settings button during this time, maybe I should just use my glasses. :-) It was somehow out of my focus area. I am always focusing on the highlighted `Download webfont` button, and it's dropdown with the single `Get config only` option. I could probably find the content of the settings menu easier here, in this dropdown. The current UI also does have a clear and logical structure, so the issue can be due to my inattention.

Thank you for your efforts in making this great tool available for us!
