### ISSUE TITLE
Feature request: Material Icons

### ISSUE THREAD

**Issue by MartCube** [fontello/fontello#726]
I just love using your tools, everything compact, fast and easy.
I wanna suggest to give community to have access to more popular Icon packs.
As title says I'm a huge fan of [Material Icons](https://material.io/resources/icons/?style=baseline)
Would love to see them added to this project.
Keep up the good work guys.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-suggest-font-to-fontello
