### ISSUE TITLE
Fontello-cli does not work

### ISSUE THREAD

**Issue by javadmokhtari** [fontello/fontello#728]
You are free to drop any section below, but note, we should be able to undersand and reproduce reported bug.

**Describe the bug**
Until yesterday, everything was fine. But now I can't install any package.json.

**To Reproduce**
1. fontello-cli install

**Expected behavior**
Install the icon font.

**Screenshots**
Error:

> /usr/local/share/.config/yarn/global/node_modules/fontello-cli/lib/fontello.js:91
>             throw "Failed. Response Code [${response.statusCode}] from ${sessionUrl}/get";
>             ^
> Failed. Response Code [${response.statusCode}] from ${sessionUrl}/get
> (Use `node --trace-uncaught ...` to show where the exception was thrown)
> 

My network connection is fine. Also I have checked with different VPNs and still no chance.
**OS/Browser**
 - OS: Linux Mint 19
 - Browser: Google Chrome

**Font/config**
Archive, created by fontello OR zipped `config.json`.
[config.json.zip](https://github.com/fontello/fontello/files/5684276/config.json.zip)

**Comment by puzrin** [comment]
`fontello-cli` is NOT our package, please contact author.

If you suspect API health - there is example with `curl` how to check https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#geek-way---use-makefile
