### ISSUE TITLE
CSS output is html encoded!

### ISSUE THREAD

**Issue by javadmokhtari** [fontello/fontello#729]
CSS produced by Fontello is HTML entity encoded. And I cannot use it in React.

Fontello Link: https://fontello.com/82445ee7629e593fdf6d2c4428e9458a

![Selection_048](https://user-images.githubusercontent.com/28118126/102006920-f2bf8500-3d39-11eb-93c7-acb834ba0ade.png)

**Comment by puzrin** [comment]
Use `config.json` to generate any CSS you need, if defaults not suitable for you needs. Or report bug to your bundle, because css is valid.
