### ISSUE TITLE
Failed to install and run this project

### ISSUE THREAD

**Issue by railsjack** [fontello/fontello#731]
**Describe the bug**
I tried to install and run this project on my local, but couldn't due to the following errors.

**To Reproduce**
`$ git clone https://github.com/fontello/fontello`
`$ cd fontello`
`$ yarn`
`$ yarn start`

**Note: It was same even when I use `npm` command instead of `yarn`.**

**Expected behavior**
I wanted to be able to run the server like as mentioned in the documentation.

**Screenshots**

![image](https://user-images.githubusercontent.com/1916657/107526951-527bc480-6bf3-11eb-8533-b320551a7824.png)

**OS/Browser**
 - OS: Windows 10
 - Browser: Google Chrome

**Font/config**
There is no config.json file in my project directory.

**Comment by puzrin** [comment]
Fonello has never been tested under win. Use linux please (win have some simulation, but i never used). Or try docker https://github.com/fontello/fontello/tree/master/support/deploy.

**Comment by Jackysi** [comment]
I have the same issue, but how is this connected to Windows?
