### ISSUE TITLE
Typo in FontAwesome icon name

### ISSUE THREAD

**Issue by dogancelik** [fontello/fontello#732]
**Describe the bug**
When I search for `codepen` icon, I can't find the icon by FontAwesome.
Codepen icon in FontAwesome v4.7.0: [fa-codepen](https://fontawesome.com/v4.7.0/icon/codepen)

**To Reproduce**
1. Search for "codepen", no FontAwesome icon.
2. Search for "codeOPEN", there is the FontAwesome icon.

**Expected behavior**
1. Search for "codepen", and you should see the FontAwesome icon.

**Screenshots**
| Search query | Screenshot |
| --- | --- |
| codeOPEN | ![codeopen](https://user-images.githubusercontent.com/486818/109568122-89107500-7af7-11eb-8817-529538f31f51.png) |
| codepen | ![codepen](https://user-images.githubusercontent.com/486818/109568125-89a90b80-7af7-11eb-8658-3c21c9cbbcd2.png) |

**OS/Browser**
 - OS: Windows 10 (64-bit)
 - Browser: Firefox 86.0 (64-bit)

**Font/config**
```json
{
  "name": "fontawesome-custom",
  "css_prefix_text": "fa-",
  "css_use_suffix": false,
  "hinting": true,
  "units_per_em": 1000,
  "ascent": 850,
  "glyphs": [
    {
      "uid": "76675011e906d50af404186b489fc76f",
      "css": "codepen",
      "code": 61899,
      "src": "fontawesome"
    }
  ]
}
```

**Comment by rlidwka** [comment]
fixed, thanks for reporting
