### ISSUE TITLE
Import through API

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fontello/fontello#736]
I checked the documentation and this feature seems not to be covered: I think it would be great to have a way to import SVG fonts and/or icons through the API without an initial config. I think this feature can be separated in two different parts:

1. From an initial configuration import a new SVG icon/image
2. Start a new session without an initial configuration but from a SVG font/icons

**Comment by puzrin** [comment]
I don't understand added value of this request for all.

**Comment by giovanni-bertoncelli** [comment]
Ok, let me describe a use case: I have a SVG font I want to extend with custom icons with an automated process.

RIght now, given a custom icon to add, I have to:

1. Open fontello UI and import the initial SVG font I want to extend
2. Download the configuration in order to have a starting point for my automated process
3. Create a script (nodejs or whatever) that updates the configuration file adding manually the new SVG icons (with unpredictable results in the icon)
4. Use the fontello API to download the new configuration files.

Since there a normalization and rescaling operations during the import process I'm not able to update the configuration with a custom SVG icon since there may be some scaling issues, at least hard-coding the SVG inside the configuration. I was wondering if this can be done by API, so the ideal workflow (completely automated) would be this:

1. Use the fontello API to get a configuration from a SVG font/icon,... (optional, if there is not an initial configuration)
2. Use the fontello API to import new SVG icons in the custom iconset (so I'm sure that the icons are correctly rescaled and normalized)
3. Use the fontello API to download the results

I don't know if this feature can be implemented or it is out of the scope of the project...

**Comment by puzrin** [comment]
IMO you mix completely different abstraction layers and approaches. You could just keep your sources as SVG icons and use `svgicons2svgfont` + `svg2ttf` + `wawoff2`.

**Comment by giovanni-bertoncelli** [comment]
Sure, but I have no access to the original SVG icons except through the icons font. I see that probably this is not appropriate to this project. I'll close the issue then.

**Comment by puzrin** [comment]
https://github.com/fontello/svg-font-dump/blob/master/svg-font-dump.js - that's outdated code, but it can give you idea how to split your font to images
