### ISSUE TITLE
Incorrect declaration of styles for icons

### ISSUE THREAD

**Issue by VadymPogorelov** [fontello/fontello#742]
When downloading an archive with icons, in the file css/fontello.css from the main selector for some reason the space before icon- was removed in [class*="icon-"]:before.
It was:
`[class^="icon-"]:before, [class*=" icon-"]:before {`
Has become:
`[class^="icon-"]:before, [class*="icon-"]:before {`
Because of this, this selector now spoils the styles of all objects containing "icon-" in the class name and not related to fontello

**Comment by rlidwka** [comment]
Fixed, thanks for reporting.
