### ISSUE TITLE
Character Codes Changing When Editing Previously Created Icon Font

### ISSUE THREAD

**Issue by JosephMaynard** [fontello/fontello#743]
**Describe the bug**
I recently started working on a project that has been using Fontello icons for some time. I had to add 
a new custom icon to our font, so I imported the `config.json` file from our repo into the [web interface](https://fontello.com/) and added my SVG and downloaded the newly created archive.

After adding the new fonts to our application, I discovered that a lot (~120 out of ~620) of the character codes had changed on the new font. Initially I thought there may have been an undocumented API change, so I used the `Customize Codes` tab to fix all of the characters, but when I uploaded the new `config.json` from my "fixed" archive, I found the character codes changed again.

Looking at our Git history on the `config.json`, I can see that they have just had one icon added at a time for the last few revisions, so it appears that something has changed on 

**To Reproduce**
1. Upload the `config.json` from the attached archive
2. Download the font
3. Compare the codes in the newly generated font (either from the `demo.html` or `css/fontello-codes.css` files)

**Expected behavior**
I would expect the character codes not to change.

**Screenshots**

**OS/Browser**
 - OS: Mac OS Big Sur
 - Browser Chrome

**Font/config**
See attached archive:
Archive, created by fontello OR zipped `config.json`.
[fontello-character-code-bug.zip](https://github.com/fontello/fontello/files/6708992/fontello-character-code-bug.zip)

**Comment by rlidwka** [comment]
Please check "Advanced Font Settings" -> "Options" -> "Encoding". Please set it to "Unicode" and try again.

By default (in "Private User Area" encoding) fontello will make sure that all characters are within 59392..63743 range (that's PUA in unicode). 

But you have a glyph "note" with code 9834. It doesn't have a code within PUA, so fontello changes it to the next available (then next glyph that uses that next available gets remapped again and so on).

Not really a bug, but yes, this could've been handled much better.

**Comment by rlidwka** [comment]
Fixed in https://github.com/fontello/fontello/commit/e2689251690c53774cde12a843f7d1c6c028ad12, thanks for reporting.

**Comment by JosephMaynard** [comment]
Thanks @rlidwka!

**Comment by rlidwka** [comment]
Gonna close this, please reopen if the bug somehow still exists.
