### ISSUE TITLE
add font-display: swap;  to the generated css

### ISSUE THREAD

**Issue by cfconsultancy** [fontello/fontello#744]
add font-display: swap;  to the generated css

**Comment by rlidwka** [comment]
It should be `block` for icons, which is the default value in most browsers anyways, so I don't see that any change is required (with `swap` browser is gonna quickly show fallback font which for custom icons wouldn't make any sense, [ref](https://developers.google.com/web/updates/2016/02/font-display)).

Can't you add your own custom css with that property (right after fontello css) if you need to override it?
