### ISSUE TITLE
SVG not imported correctly (drag drop)

### ISSUE THREAD

**Issue by geri777** [fontello/fontello#745]
I am using the UI of Fontello.com. 
When I upload a selfmade SVG the font is not build correctly.

Original:

[linkedin.zip](https://github.com/fontello/fontello/files/6842780/linkedin.zip)
![image](https://user-images.githubusercontent.com/4689190/126200992-bcd92dab-2589-446e-9778-f0079531b675.png)

Output:

![image](https://user-images.githubusercontent.com/4689190/126201049-edf362ab-f098-4e80-a11d-011decab50be.png)

So the inner parts are missing. Same issue for other SVGs having areas with cut-outs.

**Comment by puzrin** [comment]
Contours should be oriented properly. On import you should see warning with link to instructions.

https://github.com/fontello/fontello/wiki/How-to-use-custom-images#importing-svg-images

**Comment by geri777** [comment]
Thank you. Indeed it was a problem with the svg srtucture.  Thank you for your support. As I am not experienced in vector design I exported the graphics to PNG and used https://convertio.co/de/png-svg/ - and voilá, it worked.
