### ISSUE TITLE
Fontello Bug

### ISSUE THREAD

**Issue by wansim99** [fontello/fontello#746]
**Describe the bug**
When I trying to drag and drop all my icon (275) icon, it couldnt finish upload, only able to see 2 row of icon (38 icon) since last week. Last time dont have this issue.

**To Reproduce**
Scenario 1
1. Drag and drop all my icon (274 icon), but it could finish upload all the icon, it only display 2 row of icon

Scenario 2
1. Drag and drop all my icon (274 icon)
2. Finish upload, but it show all my icon in rectangle border only.
3. I couldn't download (500 internal server error)

**Expected behavior**

**Screenshots**
<img width="1647" alt="Screenshot 2021-08-03 at 9 51 22 AM" src="https://user-images.githubusercontent.com/88308521/127945080-bcc059f7-2278-4ba3-881b-01037efd863a.png">

**OS/Browser**
 - OS: MacOS: Mojave
 - Browser Chrome

**Font/config**
Archive, created by fontello OR zipped `config.json`.

**Comment by puzrin** [comment]
Seems you did not attached your file to drag

**Comment by wansim99** [comment]
[All Icon.zip](https://github.com/fontello/fontello/files/6921231/All.Icon.zip)
Attached icon

**Comment by rlidwka** [comment]
Your have a glyph named `car-plate` that can't be converted to TTF. If you look at SVG path, the very first instruction in it is `M-109563`, which is well outside of int16 `-32768..32767` range allowed by TTF.

Gonna fix that "internal server error" shortly, it should be a better error message.

**Comment by rlidwka** [comment]
Fixed, now it should output better error message (it will be an error because `car-plate` glyph is out of bounds).

**Comment by eduhoribe** [comment]
A little tip for the ones who are having issues with some SVG images and stumbled on this

If you notice that the `viewBox` width and height values are far beyond the `width` and `height` properties, you can try to change the `width` and `height` properties to match the `viewBox` values

For instance, if your `svg` tag is something like this:

```svg
<svg width="24" height="24" viewBox="0 -960 960 960"/>
```

you can try to replace it with this:

```svg
<svg width="960" height="960" viewBox="0 -960 960 960"/>
```

I've done this with some material icons SVGs and the glyphs were built successfully (tho a little more work needed to be done regarding the negative Y axis in the `viewBox`)
