### ISSUE TITLE
Site search field bug 

### ISSUE THREAD

**Issue by slavchic** [fontello/fontello#747]
Browse button overlaps search field in chrome and FF
https://i.imgur.com/tadyUEY.png

**Comment by puzrin** [comment]
I can not reproduce on Ubuntu FF/Chromium.

- Try Ctrl+F5
- Try on another computer
- If still reproducible - add info about OS / Browser versions and so on.

I beleive you have described issue, but don't understand how to make it happen.

**Comment by slavchic** [comment]
Ok. I found the reason.
The problem appears for screen resolution more than 2400px 
I have 2560x1440 now 

here is the screen cast: 
https://i.imgur.com/757gFNK.png

**Comment by nickdekruijk** [comment]
Same issue here on macOS Big Sur with Safari, 2560 width here too.

**Comment by rlidwka** [comment]
fixed (until someone finds a monitor 20x larger than yours that is), thanks for reporting

**Comment by MrMerkin** [comment]
> fixed (until someone finds a monitor 20x larger than yours that is), thanks for reporting

Seems to be working fine now on 5K iMac Pro screen in Firefox (5120x2880).
