### ISSUE TITLE
Add config for `font-display`

### ISSUE THREAD

**Issue by powerbuoy** [fontello/fontello#753]
Could you possibly add the option for users to configure which `font-display` we'd like in the generated CSS file? Both through the UI but in my case more importantly through the API? We can't manually edit the CSS file as it'll be overwritten on every icon build.

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Comment by powerbuoy** [comment]
@webocoders if you use PostCSS we found this handy plugin that solves the problem: https://github.com/dkrnl/postcss-font-display

**Comment by rlidwka** [comment]
if you want to customize fonts, you can add your own css and `@import 'icons/fontello-codes.css'` from within it

(that's minimal css file that is generated exactly for the purpose if including it with custom css wrappers)

see also https://github.com/fontello/fontello/issues/744
