### ISSUE TITLE
Feature request: Smarter config to save paths and inclusion settings

### ISSUE THREAD

**Issue by yyil** [fontello/fontello#754]
Hi team

I use Sass to combine Fontello CSS with my usual website CSS. Due to my project folder structure, my Sass does not compile unless I manually change the paths in fontello.css;

e.g. from "../font/fontello.eot" to "/assets/fonts/fontello/font/fontello.eot"

I need to update these paths every time I update my fonts selections and download a new package.
I was wondering if the paths string could be also saved in the config file, and applied to my downloaded package (i.e. default to "../font/" if not supplied)?

Secondly, I have no need for SVG versions. If options such as "include SVG, IE7 support" etc could be built into the config and applied to downloads would be useful to keep file size low.

**Comment by rlidwka** [comment]
You can create a wrapper script that downloads font from fontello (using api), picks the exact files needed and replaces paths as needed. Changes in config are not required for this to work.

**Comment by puzrin** [comment]
https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#advanced-importexport
