### ISSUE TITLE
Invalid params: - data.config is required (undefined)

### ISSUE THREAD

**Issue by jameslester2004** [fontello/fontello#755]
You are free to drop any section below, but note, we should be able to undersand and reproduce reported bug.

**Describe the bug**
The error message "Invalid params: - data.config is required (undefined)" appears when download is pressed. 

Someone else has created a SO post with the same experience. 

https://stackoverflow.com/questions/69233798/fluttericon-error-invalid-params-data-config-is-required-undefined

**To Reproduce**
1. Add svg icon
2. Try to download 

**Expected behavior**
Get a download? 

**Screenshots**

**OS/Browser**
Same result for Chrome and Safari. 

**Font/config**
n/a

**Comment by hekhy** [comment]
The same error happens to me, does anyone know how to fix it?

**Comment by puzrin** [comment]
According to SO link, question is about fluttericon.com site, not about fontello.com. I can't comment third-party sites, only fontello.com.

**Comment by jameslester2004** [comment]
Anyone know who is behind fluttericon.com ? Bit misleading their git symbol comes here...

**Comment by hekhy** [comment]
I have no idea, in the end if it worked for me and I let it pass but it would be interesting if there is at least a place to talk about the errors.
