### ISSUE TITLE
Ability to add custom svg icons

### ISSUE THREAD

**Issue by SiL3NC3** [fontello/fontello#761]
Thank you for this stunning font-service.

It would be very convenient and as well bringing endless flexibility, when it would be able to add custom svg codes in a custom user related collection, which is always be generated along the other icon selections.

If anyone want to add a custom icon, which is not available for selection, it is really hard work to add this into the fontello package manually for all the generated file types.

**Comment by puzrin** [comment]
SVG import is supported, with some prepare.

https://github.com/fontello/fontello/wiki/How-to-use-custom-images
