### ISSUE TITLE
Dose not support SCSS

### ISSUE THREAD

**Issue by mhl98** [fontello/fontello#764]
I want to use fontello.css as an SCSS file to extend icons in SCSS files.
When I change fontello.css to fontello.scss sometime, icons show like this !

![image_2022_09_04T11_47_57_137Z-21](https://user-images.githubusercontent.com/74253946/189383526-9e0d7731-372d-438e-a459-b21cbbf81be0.png)

**Comment by puzrin** [comment]
Sorry, not familiar with SCSS, can't comment that.
