### ISSUE TITLE
Remove old fonts format

### ISSUE THREAD

**Issue by yukulele** [fontello/fontello#766]
- SVG font format is deprecated and [most browsers no more support it](https://caniuse.com/svg-fonts)
- Is anyone really still developing for ie7?

The output could be simplified by removing some old features.

**Comment by puzrin** [comment]
1. I see no reasons to make breaking changes "just for fun".
2. SVG is still useable as human readable source, to verify result.
3. If you don't like default output, you can make script to customize it for your needs. Wiki has some examples.
