### ISSUE TITLE
OpenType support please

### ISSUE THREAD

**Issue by aarontheman** [fontello/fontello#768]
With Adobe phasing out support for TrueType in 2023, it would be super valuable for fontello to support exporting of OpenType (otf) format.

**Comment by khaledhosny** [comment]
Adobe is phasing out support for Type 1 fonts (`.pfb` and `.pfa` files) not TrueType fonts.

**Comment by aarontheman** [comment]
Thank you for clarifying, Khaled; that is a relief!
